### ISSUE TITLE
Perform a challenge game test

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1002]
Once #1000 is fixed, we need to

- [x] start mainnet agents again

* make a transfer request
* make sure the request is filled by one of the agents
* challenge the corresponding claim
* check whether the agent responds to the challenge
* make another challenge (within the same challenge game)
* check whether the agent responds to the challenge
* do not respond further, making the agent win the game eventually
* wait for the results to appear on the source chain
* check that the agent was able to withdraw

**Comment by fredo** [comment]
additionally we should test that the agent protect the protocol by challenging false claims

- [ ] create a false.claim for existing request I'd
- [ ] confirm that one agent challenged
- [ ] after termination confirm that agent withdrew 
(most likely the agent should already be able to withdraw once the tokens are withdrawn by the real filler)

**Comment by fredo** [comment]
testing non fill proof

- [ ] shut down one agent
- [ ] drain agents funds on boba roll up so that he is out of funds on boba
- [ ] create a request he cannot fill
- [ ] claim the request
- [ ] confirm that agent created non fill proof
- [ ] confirm that agent challenged claim

optionally

- [ ] counter challenge until enough funds are raised
- [ ] wait 7 days
- [ ] confirm that agent resolved on L1
- [ ] confirm that agent resolved claim
- [ ] original user withdraws tokens from expired request

**Comment by fredo** [comment]
> additionally we should test that the agent protect the protocol by challenging false claims
> 
> * [ ]  create a false.claim for existing request I'd
> * [ ]  confirm that one agent challenged
> * [ ]  after termination confirm that agent withdrew
>   (most likely the agent should already be able to withdraw once the tokens are withdrawn by the real filler)

# BOBA

- [x] [Request with id 48](https://bobascan.com/tx/0x53f6a8d078ac54e058f82fbb0f80294dfc8ec2ec84942b910789a0389670ee11)
- [x] [False claim](https://bobascan.com/tx/0x4aabcaef28dde64c1c0d940ef3dfb7b75d73b182433940693abe00e2f8424cb2)
- [x] [Challenged by 0xf6bb6190f48dadf6b25f8d2b7a24ecb9b10c5abd](https://bobascan.com/tx/0xc73aef6239eb8969752823413a3d27fc5ca1bdd49b56366055f8c08810058673)
- [ ] Termination of challenge - Fri Sep 16 2022 11:10:31 GMT+0200 (CEST) (1663319431)
- [ ] Confirm that agent withdrew

# Optimism

- [x] [Request with id 32](https://optimistic.etherscan.io/tx/0x8c5e179b313ff30e0433dbb809610a3eff158d1e04563e295ea2d26f9121a468)
- [x] [False claim](https://optimistic.etherscan.io/tx/0xc464653e329b8cb400019c388a6349c47854c8ee2538c85ee7be1d7fba6cf916)
- [x] [Challenged by 0x61e01a8d1942b0efeaa4b52f06b7bf3a672478d899f16c9ae0cdaaf7ed4ec726](https://optimistic.etherscan.io/tx/0x61e01a8d1942b0efeaa4b52f06b7bf3a672478d899f16c9ae0cdaaf7ed4ec726)
- [ ] Termination of challenge - Fri Sep 16 2022 11:20:15 GMT+0200 (CEST) (1663320015)
- [ ] Confirm that agent withdrew

**Comment by fredo** [comment]
Before finalizing the tests we need to: 

* wait for #1037 
* update agents
* start agents
* investigate challenge issue between the agents

**Comment by fredo** [comment]
closed in favor of #1077
