### ISSUE TITLE
Preparing Request Manager / Fill Manager - Tearing down test agents

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1039]
Before announcing we need to

- [x] shutdown our mainnet test agents
- [x] remove them from whitelist
- [x] add real agents to whitelist
- [x] configure the correct limits in the Request managers

**Comment by istankovic** [comment]
> Agreed transfer limits are 1000 USDC (1_000_000_000). @istankovic can you adjust the limits?

On it. :+1:

**Comment by istankovic** [comment]
Our mainnet agents have been removed from the whitelists:

https://optimistic.etherscan.io/tx/0xc012e8d6cee447e13bcf5fa6b89e14a2eb3bdce88ec87f7eff8f36b9f7d568b8
https://optimistic.etherscan.io/tx/0x3ec1ed6127bbb1fc8064f109c809c0c343eb23cc6a00ad2aeaf418d742cc0743

https://bobascan.com/tx/0xe4f3165a9b3a59e84505fea8866d7f58c187aa8608fd3c909ec609e118cc5b9a
https://bobascan.com/tx/0x08f1bf9161367aac5f44337321770d9d7554ebc6d512b221ab981266e5d3f044

**Comment by istankovic** [comment]
Whitelisted `0xe9070FFc3B1b513F79a35983784C19AeFa093521`:

https://optimistic.etherscan.io/tx/0x546ddb6960431c82638dd2eea6f0b14cad852d34f6dddabda10696807f156e3c
https://bobascan.com/tx/0x363d72ed696fc9412cfaf03ff77e992f200927f48afb6154732c490b55b55e00

**Comment by istankovic** [comment]
This is done now.
