### ISSUE TITLE
Frontend: Integrate chatbot

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1043]
Due to a [marketing decision](https://github.com/beamer-bridge/marketing/issues/112) we need to integrate the following embed snippet on our app in order to enable the chatbot:

```
<div data-tf-popover="DjKClKBT" data-tf-custom-icon="https://images.typeform.com/images/p3kcCHwcwckZ" data-tf-button-color="#FFFFFF" data-tf-button-text="Launch me" data-tf-iframe-props="title=Beamer - Mainnet launch" data-tf-medium="snippet" data-tf-hidden="utm_source=BeamerApp,utm_medium=chatbot,utm_campaign=mainnet,utm_content=feedbacksurvey" style="all:unset;"></div><script src="//embed.typeform.com/next/embed.js"></script>
```

**Comment by andfletcher** [comment]
This should be done shortly before we announce mainnet since we want people to provide feedback.

**Comment by DinaBB** [comment]
@GabrielBuragev @czepluch @andfletcher 

After testing the chatbot in a demo environment, some formatting errors were noticeable. Other than that, it all works fine. Unfortunately, the edits resulted in a slight code change. 

I will let you decide about prioritizing the change according to other to-do's in the context of the mainnet change. Just let me know here by when it can be done. :) 

Here is the embed code:

`<div data-tf-popover="DjKClKBT" data-tf-custom-icon="https://images.typeform.com/images/KN5E4QHWSekY" data-tf-button-color="#FFFFFF" data-tf-notification-days="3" data-tf-tooltip="Hey 👋&nbsp;&nbsp;Let us know what you think!" data-tf-open="scroll" data-tf-open-value="30" data-tf-chat data-tf-medium="snippet" data-tf-hidden="utm_source=xxxxx,utm_medium=xxxxx,utm_campaign=xxxxx,utm_content=xxxxx" style="all:unset;"></div><script src="//embed.typeform.com/next/embed.js"></script>`

**Comment by andfletcher** [comment]
Well now its in the sprint so lets get it done :)
