### ISSUE TITLE
Frontend: Add links to beamer homepage inside footer and header

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1048]
Once the users come to the dApp, there is no way for them to go to the beamer's homepage to read more about our app.
We need anchor links which lead to www.beamerbridge.com.

# Acceptance criteria

- [ ] Beamer logo in the header should link to www.beamerbridge.com
- [ ] "Powered by Beamer" in the footer - "Beamer" link to www.beamerbridge.com

**Comment by andfletcher** [comment]
Can be done without input from design. Needs to be follow current design.
