### ISSUE TITLE
Set minimum fee to $1

### ISSUE THREAD

**Issue by czepluch** [beamer-bridge/beamer#1049]
# Rationale

The gas prices on rollups have changes quite a lot since we initially created the fee model. We should set the minimum fee lower than $5. Currently 1 tx on rollups costs around $0.10 and an agent does 3 per fill. So have some room for fluctuating gas prices, it is suggested that the minimum fee is set to $1.

# Implementation

- [x] Update the minimum fee in the mainnet deployment to be 1 USDC.
- [x] Add "The minimum fee for a transfer is 1 USDC" to the popup text. 
Implementation: (#1082)
- [x] Adapt docs in section `agent fee` in whitepaper

**Comment by andfletcher** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1049?planning-poker) with Zenhub @fredo @istankovic

**Comment by andfletcher** [comment]
@GabrielBuragev please be aware that I added a component for this issue after aligning with Jacob.

We need the sentence "The minimum fee for a transfer is 1 USDC"  at the end of the popup (when you hover the mouse over "?")

**Comment by andfletcher** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1049?planning-poker) with Zenhub @GabrielBuragev

**Comment by GabrielBuragev** [comment]
@andfletcher Should we create 2 separate issues and add them in this issue description and estimate them separately? 
Since this issue covers work on both frontend & backend.

**Comment by andfletcher** [comment]
> @andfletcher Should we create 2 separate issues and add them in this issue description and estimate them separately? Currently this issue covers work on both frontend & backend.

i dont think its worth it. Its a good practice on how we can swarm on issues together to finish them since both acceptance criteria are unrelated but still go towards the same value.

**Comment by GabrielBuragev** [comment]
Where are the fees defined?

**Comment by andfletcher** [comment]
> defined

This is a good point. But currently, we only support USDC, so it should not matter for now.

**Comment by andfletcher** [comment]
> Where are the fees defined?

I dont know but why do you need to know where the fees are defined (just asking)

**Comment by czepluch** [comment]
They are defined in the contract. So you should be able to pull the number from there. Especially since we might need to manually update it in the future based on gas prices.

**Comment by GabrielBuragev** [comment]
@andfletcher As Jacob explained. Need to know where to fetch them from on the frontend.

**Comment by fredo** [comment]
Update Fee

Protocol: 0 PPM
Agent: 3000 PPM 
Fixed Fee: 1000000

**Comment by istankovic** [comment]
Fees updated on Optimism: https://optimistic.etherscan.io/tx/0xf2aaf2c93e41061fc106ea6aa62f186c258d865da31ea26b0e7f6b4468791212

Fees updated on Boba: https://bobascan.com/tx/0xa5b9119ea5a903961352661606b2009d8ab96d334b70e54767a59f333e850d94
