### ISSUE TITLE
Create isWithdrawn() function for requests

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1051]
As a developer I want to read the contract's state and see if a request is withdrawn or not. There is currently no exposed function for this.
Added value is, that developers who build on beamer can easily find out if a request is withdrawn or not. 

PSEUDO
```
function isWithdrawn(bytes32 requestId) public view returns (bool) {
    if(requests[requestId].withdrawnClaimId == 0) {
        return False;
    }
    return True;
```

- [ ] Frontend should be able to use this function

**Comment by andfletcher** [comment]
@fredo can you formulate this issue as a User story e.g. as a user i would like to do **** so that i can *****

**Comment by andfletcher** [comment]
basically elaborate on the user value

**Comment by fredo** [comment]
done
