### ISSUE TITLE
Agent needs to handle claims after L1 resolution

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1052]
## Description
Currently the agent makes an assumption that expiry and therefore creation of claims happens before L1 resolution. This might not be true for target rollups with low finality periods. We need to address this in the agent's state machine.

things like: 

- creating claim in l1 resolved state
- handling invalidation events which came prior to claim creation

needs to be addressed.

## Acceptance criteria
- [ ] Agents can apply events to objects that get created at a later point in time

**Comment by fredo** [comment]
This is already implemented in branch `0.x`

**Comment by andfletcher** [comment]
@fredo if its implemented in branch 0.x what do we need to do to complete this issue?

**Comment by istankovic** [comment]
@fredo Bump.

**Comment by fredo** [comment]
I just analyzed the code: 

We already handle these issues. It was probably already cherry picked from 0.x. From my side we can close it @andfletcher
