### ISSUE TITLE
Plan process of new deployment

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1075]
We need to create a process for deployment.

The reason is that we have a central point where the source of parameters is and a concept of double-checking that everything is correct. 

There should be at least 4  eyes concept of checking parameters before the deployment and checking the correct configuration of deployed contracts. 
Ideally, we have a sheet where responsible persons are assigned and report their findings.
This process is to be repeated for every deployment

When doing a new deployment, we have to take care of a couple of things to provide the service continues to the users.

Things that need to happen: 

- Deploy new frontend / Point URL to new frontend (own issue) https://github.com/beamer-bridge/beamer/issues/1272 (own issue)
- Deploy new contracts - done
- Perform test process on new contracts with own agents (own issue) - not created sofar
- Official liquidity providers need to run agents on new contract #1146
- Official liquidity providers need to run agents on old contracts for a while to finalize claims and challenges #1146

These points have partial dependencies with each other and are not sorted yet.

## Aditional information
This can also be a documentation on what we do for arbitrum

## Acceptance criteria
- [x] Google sheet is created that represents the checklist
- [x] Team is aligned, and people that are responsible for deployment-related todos are informed
- [x] Date and potential time are visible on the sheet

**Comment by istankovic** [comment]
@fredo @GabrielBuragev maybe we can also discuss this one in one of the meetings?

**Comment by andfletcher** [comment]
How long do we expect them to run the agents on the old contracts? More like a day or longer? E.g. if there are running challenges they will need to run it for a week - until its over?

**Comment by andfletcher** [comment]
Contract deployment can be done before frontend deployment?

**Comment by istankovic** [comment]
> How long do we expect them to run the agents on the old contracts? More like a day or longer? E.g. if there are running challenges they will need to run it for a week - until its over?

Yes, the worst case would be 1 week from the moment of request manager deprecation.

**Comment by istankovic** [comment]
I really like how Fred used precise terminology here, differentiating between LPs and agents:

> Official liquidity providers need to run agents on new contract
> Official liquidity providers need to run agents on old contracts for a while to finalize claims and challenges

**Comment by GabrielBuragev** [comment]
Since yesterdays meeting resulted in a spreadsheet with the checklist for the deployment process only, will we need to have more meetings to align on the other processes (for example frontend deployment, agent whitelist etc.)?

**Comment by andfletcher** [comment]
@GabrielBuragev yes but we first need to creat / have all the issues for the frontend. Lets sync

**Comment by istankovic** [comment]
I'm not sure whether this item is considered now done or not, but I think we should at least discuss the topic of #1146, which we mentioned we would do as part of this item. It's also fine to have that discussion separately and unlink #1146 from this issue.

**Comment by andfletcher** [comment]
All done.
