### ISSUE TITLE
Perform agent L1 resolution test

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1077]
### Test
* make a transfer request
* make a transfer request
* make sure the request is filled by one of the agents
* challenge the corresponding claim
* check whether the agent responds to the challenge
* wait for the fill message to finalize
* make another challenge (within the same challenge game) with enough funds to go to L1
* make sure the agent triggered L1 resolution
* wait for the results to appear on the source chain
* check that the agent was able to withdraw

# BOBA
- [ ] make a transfer request
- [ ] make sure the request is filled by one of the agents
- [ ] challenge the corresponding claim
- [ ] check whether the agent responds to the challenge
- [ ] wait for the fill message to finalize
- [ ] make another challenge (within the same challenge game) with enough funds to go to L1
- [ ] make sure the agent triggered L1 resolution
- [ ] wait for the results to appear on the source chain
- [ ] check that the agent was able to withdraw

# Optimism
- [x] make a transfer request
- [x] make sure the request is filled by one of the agents
- [x] challenge the corresponding claim
- [x] check whether the agent responds to the challenge
- [x] wait for the fill message to finalize
- [x] make another challenge (within the same challenge game) with enough funds to go to L1
- [x] make sure the agent triggered L1 resolution
- [x] wait for the results to appear on the source chain
- [x] check that the agent was able to withdraw

# Arbitrum
- [x] make a transfer request
- [x] make sure the request is filled by one of the agents
- [x] challenge the corresponding claim
- [x] check whether the agent responds to the challenge
- [x] wait for the fill message to finalize
- [x] make another challenge (within the same challenge game) with enough funds to go to L1
- [x] make sure the agent triggered L1 resolution
- [x] wait for the results to appear on the source chain
- [x] check that the agent was able to withdraw

**Comment by czepluch** [comment]
I am moving this to the top of the backlog, and I want to be able to pull it into the current sprint as priority once our first external agent is up and running.

**Comment by czepluch** [comment]
Still needs an estimate. @andfletcher can we refine this in the standup tomorrow?

**Comment by andfletcher** [comment]
I added arbitrum todos.

**Comment by andfletcher** [comment]
Will need to be align on in the refinement meeting since i added arbitrum

**Comment by GabrielBuragev** [comment]
L1 resolutions passed and agent automatically withdrew the staked funds from the challenge:
- https://optimistic.etherscan.io/address/0x0B3c3DCf4C9db39B810F306e55Cd14Aed5c19C0b
- https://arbiscan.io/address/0x6d00f6994f36Ec1a3Bd008DBbC84DFa46A939001

Ignoring Boba based on previous decision
