### ISSUE TITLE
Move from brownie to ape for our contract and agent tests

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1079]
Brownie seems to be unmaintained and needs fixing which is frustrating. There is a fork if brownie called [ape](https://github.com/ApeWorX/ape) which seems to be more active. For the most part, it looks like a direct fork of brownie, with added features on top (e.g. support for multiple chains).

We should
- [x] convert contract tests to ape
- [x] convert agent tests to ape
- [x] update docs
- [x] remove `eth-brownie` from our dependencies (`pyproject.toml`)
- [x] update `pylintrc`

**Comment by andfletcher** [comment]
possibly we need to shit this approach. for now, we will wait until ape team gets back to us and then decide on how to continue.

**Comment by bilbeyt** [comment]
@andfletcher I have created 4 issues like we talked in the meeting, and mentioned this issue in their description.

**Comment by istankovic** [comment]
After some more discussion with @bilbeyt, we determined #1286 is not really critical (though very much desired), so we're not marking it as being a blocker for this issue.

**Comment by andfletcher** [comment]
@bilbeyt i understood that the 4 issues are created already within the ape organisation from them? Did i misunderstand it? How are we moving forward on checking progress on the issues, do we need to do them or are we just waiting for them to do it? I understood it in a way that there are issues and we just need to wait for them to finish them?

**Comment by istankovic** [comment]
> How are we moving forward on checking progress on the issues, do we need to do them or are we just waiting for them to do it?

For the one regarding account creation (#1284), we asked them, but there's no guarantee when they're going to work on it, let alone when it will be available. They also told us we're welcome to work on it, which @bilbeyt already started.

For the other 3, we mentioned them, but unlike the 1st one, we have not yet reached an agreement on them. Once we reach an agreement, we will also probably write an issue and likely also contribute a patch.

These are the scenarios I can imagine:
1. we reach an agreement on all issues, write issues for ape and they implement all of them
2. we reach an agreement on all issues, write issues for ape and we implement all of them
3. we reach an agreement on all issues, write issues for ape and we implement some of them, the rest done by apeworx
4. we do not reach an agreement on all issues

I think scenarios 1 and 4 are unlikely, so that would leave 2 and 3, with 3 being less likely than 2.
@bilbeyt feel free to pitch in with your view.

**Comment by bilbeyt** [comment]
They implemented something for #1286 already but when i checked it, it wasn't really working in my view. Tested with only one test but still.

For the others, they have an issue for #1284 but like @istankovic mentioned they offered us to do it, and so i started.

Imo, also 2 is likely.

**Comment by andfletcher** [comment]
Moving this out of the sprint and marking it as blocked by the 4 issues.

**Comment by bilbeyt** [comment]
another problem with ape and using it in tests:

`
assert "LpAdded" in whitelist_[tx.events](https://tx.events/)
`

above expression is not available for ape, instead we can use 

`
[x for x in fill_manager.LpAdded.from_receipt(tx)]
`

this is returning a generator that would have list of LpAdded event objects.

**Comment by bilbeyt** [comment]
all tests using {"from": filler} as parameter for contract call should change to use sender=filler as kwarg

**Comment by bilbeyt** [comment]
transaction receipt has no timestamp, so you need to use `ape.chain.blocks[tx.block_number]` to get the block and get the timestamp

**Comment by bilbeyt** [comment]
contracts can not call another contracts with ape ganache for now: we can check this issue https://github.com/ApeWorX/ape-ganache/issues/16

**Comment by bilbeyt** [comment]
instead of using chain.sleep, ape is using chain.provider.set_timestamp({timestamp})

**Comment by bilbeyt** [comment]
instead of timedelta in brownie chain.mine, in ape deltatime should be used as kwarg

**Comment by bilbeyt** [comment]
instead of `contract.abi` we are using with brownie,  `contract.contract_type.abi`
