### ISSUE TITLE
Don't create unneeded InitiateL1Resolution events

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1085]
We currently create multiple `InitiateL1Resolution` events instead of just one, upon receiving the first challenger's `ClaimMade` event. These events can live in the event for some time, causing multiple futures to be created needlessly. We should change the agent so that we create create only one `InitiateL1Resolution` event, upon receiving the first challenger's `ClaimMade` event.

- [ ] write a test
- [ ] port the changes to the `main` branch

**Comment by fredo** [comment]
As we discussed, Initiating L1 could be done via a flag in the state instead of inducing a new internal event.
The flag would trigger L1 upon `process_request()` or `process_claims()` respectively.
