### ISSUE TITLE
Frontend: Remove unused libraries

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1091]
There this library `vue-select` which is not being used anywhere in the code (nor its css) and yet its listed under `dependencies` inside `package.json` and its css [is being included](https://github.com/beamer-bridge/beamer/blob/main/frontend/src/main.ts#L3) in the app.

We could optimize loading times by completely removing it and possibly other unused libraries if any.

@manuelwedler Can you confirm that this library is no longer being used by the app?

# Acceptance criteria
- [ ] `vue-select` is removed from the `dependencies` inside `package.json`
- [ ] `import 'vue-select/dist/vue-select.css';` is removed from `main.ts`

**Comment by manuelwedler** [comment]
Yes, this can be removed safely. When I implemented our own selector component, this library became obsolete. Missed to remove the dependency.
