### ISSUE TITLE
contracts: replace deprecation mechanism with Pausable

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1105]
[Pausable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/Pausable.sol) is a nice OpenZeppelin mechanism that allows one to pause/unpause contracts. It would be an improvement over our current deprecation mechanism.

- [x] replace deprecation with Pausable in RequestManager
- [x] write a test for pausing/unpausing request manager

**Comment by andfletcher** [comment]
We need to evaluate if we "should" do this from a legal perspective. i will align with jake on this before we start implementing it.

**Comment by andfletcher** [comment]
I did not but there should not be a problem so please go ahead. @istankovic
