### ISSUE TITLE
Prohibit invalidating FillIds of current block

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1112]
The protocol makes the assumption that future fill ids can only be guessed. This is achieved by the fill id being the blockhash of the last block (assuming an honest sequencer).

However, the fillId of the current block is known during execution. It is theoretically possible that both, invalidation and fill are in the same block. Since future fill ids must be guessed and all fill ids from past blocks cannot be invalidated anymore if they are valid (we check against fills), we only run into this problem if the invalidation is in the same block but executed before the fill. 

We can easily prevent that and revert if someone wants to invalidate the fill id  of the current block.

**Comment by istankovic** [comment]
> We can easily prevent that and revert if someone wants to invalidate the fill id of the current block.

Ah, this is actually a very nice solution! Very nice and simple. :+1:

**Comment by istankovic** [comment]
Do you know how we can test this? Because we would definitely like to have a test for this.

**Comment by fredo** [comment]
Testing should be fairly simple. We just need to access the block hash of the latest block and use it as a fill id for an invalidation
