### ISSUE TITLE
Large Gap between recent and previous transactions

### ISSUE THREAD

**Issue by DocSmoove** [beamer-bridge/beamer#1115]
#### System information
There is a fairly large gap between the recent transactions and the previous transactions. This is on the mainnet dApp @GabrielBuragev 

<img width="352" alt="Screen Shot 2022-10-06 at 9 43 39 PM" src="https://user-images.githubusercontent.com/107990484/194530546-b350db5c-8196-412b-aaed-6e31027ceb79.png">

**Comment by GabrielBuragev** [comment]
Closed by #1351
