### ISSUE TITLE
Frontend: "Use max" token amount feature should include fees in final amount

### ISSUE THREAD

**Issue by DBecane** [beamer-bridge/beamer#1127]
## Description of Deliverables(s)

Community member: 
When I have 326usdc in my wallet, choose max, it will prompt that the amount is not enough.
It took a long time to understand this setting because a portion of the amount is left to pay for processing fees
Personally, I think this amount can be set as dynamic, if the remaining amount is not enough to pay the commission, it will be deducted from the selected amount; if the remaining amount is enough to pay the commission, it will be deducted from the remaining amount.
Or when the user clicks max, the amount entered in the input box is automatically subtracted by 1. 

## To Do 

I guess we can make the 'max' input dynamic so it takes the max possible amount deducted from the fees? 

@czepluch I think your input here is needed to make a decision. What's the best way to approach thin in your opinion? Given that we want to give people the choice to deduct or top up the fee amount.

**Comment by czepluch** [comment]
Could you @DBecane or maybe @GabrielBuragev give this issue a more relevant title?

**Comment by DBecane** [comment]
Awesome! LMK if you need anything else from me here and as we will want to announce this feature, keep myself and @DocSmoove in the loop here pls 🙏

**Comment by manuelwedler** [comment]
also I was a little bit confused if we have a max button. Didn't see it at all, as it is only clear when you read the tooltip. I think we should make it clearer that it is clickable. For example by changing the mouse cursor and highlight the color of the balance / adapt it to the look of the other  small buttons (like the add to wallet).

**Comment by GabrielBuragev** [comment]
Yeah, i just added it like that because there was no design at that moment. I thought it's not going to hurt if we have the functionality out there for mainnet even though the action is not so prominent. 
For a proper button/visibility we need a design or at least some input from @olympe-silve here.
