### ISSUE TITLE
Deployment script for subgraph

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1137]
We need to provide a docker compose file to deploy a subgraph. We need to run a subgraph per chain, so this must be addressed in the docker compose file (must be configurable).

The Script need to run the subgraph and an IPFS node to host the DB.

Parameters: 
- [ ] network

**Comment by andfletcher** [comment]
@fredo why do we need to provide a docker compose to deploy a subgraph for a certain chain?

**Comment by GabrielBuragev** [comment]
@fredo I think we can close this issue as the subgraph implementation, together with the deployment scripts & docker compose file, was already done in https://github.com/beamer-bridge/beamer/issues/889, right?

**Comment by andfletcher** [comment]
for now icebox

**Comment by compojoom** [comment]
This can be closed. I've explained in the readme of https://github.com/beamer-bridge/beamer/pull/2127 how the subgraph node can be started with multiple chains support by using an .env variable
