### ISSUE TITLE
Improve sleeping in ContractEventMonitor

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#114]
Currently we have this in `ContractEventMonitor`:

```python
        while not self._stop:
            events = fetcher.fetch()
            if events:
                self._on_new_events(events)
            # TODO: wait for new block instead of the sleep here
            time.sleep(1)
```
(https://github.com/raisync-project/raisync/blob/main/raisync/chain.py#L66-L71)
We sleep for 1s before we fetch next batch of events, which is not that efficient because we may
wake up only to find out that there are no new events because a new block has not been mined yet.
However, we cannot just wait on the new block indefinitely since that would prevent the clean shutdown
of the node via the `self._stop` flag.

Ideally, our sleep time would be either the `time-until-next-block` or `time-until-stop-is-set`, whichever is smaller.

**Comment by fredo** [comment]
closimg as it will be resolved by weebsockets
