### ISSUE TITLE
Document when and how agents are supposed to update

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1146]
In order to bring more clarity and help agents be up to date, we should

- [x] explain our agent versioning scheme, including compatibility considerations
- [x] explain which agent version (series) should be used (e.g. `1.x`, `0.x`...)
- [x] provide an example of how to find the latest version of a version series
- [x] provide pointers to this documentation in the run-your-own-agent repo

**Comment by istankovic** [comment]
@czepluch @DBecane should also comms be involved in some way when we make a new agent release? Feel free to comment on this issue.

**Comment by DBecane** [comment]
Yes, definitely. I need more info on that topic- please give more context in a short call next week, where I will also be able to ask some questions @istankovic @czepluch. Thanks 🙏

**Comment by czepluch** [comment]
I think there's not really anything to add. It's just about the fact that comms should be made aware when we make a new release so that they can tweet about it :)

**Comment by andfletcher** [comment]
Deprecate old RequestManager - add to sheet / checklist

**Comment by andfletcher** [comment]
- Remove agents from whitelist on FillManager (not necessary but just for safety reasons) - add to sheet/checklist

**Comment by istankovic** [comment]
Note that updating to a new version within the same series (e.g. `1.x` -> `1.y`) is somewhat different from updating to a version of a new series (e.g. `1.x` -> `2.y`), because the latter implies that the contracts changed.

It is only in the latter case that we need to consider deprecating/pausing the request manager contract and removing agents from the whitelist(s).

Should we also consider giving agents some time before disabling the old contracts?

**Comment by fredo** [comment]
> Should we also consider giving agents some time before disabling the old contracts?

There is no need to give agents time for this. Disabling old contracts only prohibits the creation of new requests. So agents don't really notice this behavior, it is similar to inactivity on the contracts

**Comment by istankovic** [comment]
@fredo is there anything left to do in this issue?
Have the internal checklists been updated? If yes, I think we can close this.
