### ISSUE TITLE
Frontend: Writing "." as first character inside request amount input breaks app

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1152]
![input-amount-bug](https://user-images.githubusercontent.com/18466333/197740706-c9ae3a53-ee9e-43e7-b33b-8c0c6b9dc772.png)

#### System information

OS & Version: All
Browser & Version: All
Commit hash: when using checkout

#### Expected behavior
User should be allowed to type in ".5" instead of "0.5" as initial input in the request token amount field.

#### Actual behavior
User starts typing ".5" and app breaks because some of the fee calculation logic breaks for the input "."

#### Steps to reproduce the behavior
- Select & connect to a chain
- Select a token
- Type "." in the request token amount input
- App breaks & becomes unresponsive

**Comment by GabrielBuragev** [comment]
Try this out: https://github.com/brainbot-com/PoWDump/blob/main/packages/website/components/input-row/custom-decimal-input.tsx

**Comment by czepluch** [comment]
We should probably prioritize this, since it's a bug @andfletcher
