### ISSUE TITLE
Frontend: Disallow entering non-numerical characters in token amount input

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1165]
Rationale
---
To keep the UI/UX simple & less confusing for the user, as well as the code cleaner & more robust, we need to limit the allowed characters inside the token amount input. The token amount input should only accept numerals and a "." as a decimal separator.
It should work exactly like the token amount input's on PoWDump, Uniswap etc.
Having a free-style input showed us that many things can go wrong at the form validation & contract interaction level when the value for the token amount is invalid in the first place.

Implementation
---
After [my previous failed attempt](https://github.com/beamer-bridge/beamer/pull/918#issuecomment-1225298052) to solve this, i was challenged again to find a solution to this issue by using [this implementation](https://github.com/brainbot-com/PoWDump/blob/main/packages/website/components/input-row/custom-decimal-input.tsx?rgh-link-date=2022-10-27T09%3A01%3A56Z) as reference.
By playing around with this code in Vue i learned this lessons:
- Vue triggers the element's `input` event too late (only after the elements inner value has changed) therefore preventing (blocking) the input is impossible for these events.
- The `change` event is triggered when the input loses focus apparently, so its quite different than the onChange event in React, therefore it is useless for our case.
- The only events you can play with are the keydown, keypress & keyup events however these are emitting a KeyboardEvent which only contains info about the keyCode that was pressed. This explains the background of my attempt in the past to fix it by detecting the keyCode which rendered useless in the end because of the cross-browser/device incompatibility.

However, by extracting the regexp from the reference code & playing around with the input event together with the `HTMLInputElement` API i was able to come to a solution that works.

The solution is to use `HTMLInputElement.value` to overwrite the value (with the previous input value) once it goes from a valid state to an invalid state (validated by the regexp).

**Comment by andfletcher** [comment]
sound good  @GabrielBuragev i will pull this into the sprint since it can be connected to #1152

**Comment by andfletcher** [comment]
@GabrielBuragev please add story points
