### ISSUE TITLE
Write whitepaper

### ISSUE THREAD

**Issue by czepluch** [beamer-bridge/beamer#118]
I believe that we should have a whitepaper for Raisync. There are two main reasons for it. 

1. External people can review and provide input regarding the soundness of the protocol
2. Investors will most likely be asking for something like this before they want to invest (similar to point 1, yes). Projects like li.fi will also ask for a whitepaper before they will list us.

Other reasons:
* We can have a shared understanding and vocabulary to use within the team

## Acceptance Criteria

The document should explain the protocol at a detail level that's good enough for an external researcher to read it and understand how the protocol works and the security model it has.

**Comment by istankovic** [comment]
The whitepaper has been merged into our docs. There are still some things to work on, but I believe it already meets the acceptance criteria.
