### ISSUE TITLE
frontend: MetaMask shows errors for provided chain data

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#1183]
When a user does not have a network and the dapp triggers to add the network, MetaMask shows an error and a warning that the chain data might not be correct. The issue is that MetaMask checks against this list: https://github.com/ethereum-lists/chains

We should make sure to use the same network name, currency symbol, etc. as in the repo. It might make sense to just fetch it from the list when we generate the configuration files.

#### Expected behavior
No errors / warnings in MetaMask.

#### Actual behavior
![image](https://user-images.githubusercontent.com/34456797/200811139-9f02599a-4ca7-4bf8-a545-5ac955b4dc18.png)

#### Steps to reproduce the behavior
(Remove network in case you already have it)
Select a source chain and let the dapp trigger the chain switch.

**Comment by GabrielBuragev** [comment]
Good idea, lets do this!

**Comment by andfletcher** [comment]
@GabrielBuragev to create followup issue to address the actual problem for future rollups-
