### ISSUE TITLE
Beamer Agents Analytics

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1191]
# Rationale
Currently agents running the agent software have hard time figuring out what their balance is, how much money they have locked in the contract or how much fees they have earned. This information is dispursed between different contracts and it's hard to manually calculate.

Why should this feature exist?
Improve agent user experience

# Implementation

Create a dashboard style website where agents could see that information.

things to display
- balance
- [x] available (through the rpc)
- [x] locked (unclaimed, claimed, finalized)
- [ ] challenged
- [x] last unclaimed fills
- [x] data is aggregated for all roll-ups, but can be filtered down per roll-up
- [x] Fees for transactions
- [x] collected fees
- [x] Gains

**Comment by andfletcher** [comment]
Feedback from one of our agents:
Beamer Agent Desired Stats
Below points are a braindump of things we can do to prevent problems when shutting down agents and other general improvements.

Shutdown mechanism (stop filling request, and then shutdown after timeout period)
Service to claim on behalf of agents
Stats to see amount of claims, locked capital, available capital, missed claims, current 24h vol, fees earned,
RPC stats to see speeds,
General agent software monitoring, telegram bot?, hardware monitoring
NET ROI on ETH and tokens
General status overview: Open claims, price of shutting down,

**Comment by andfletcher** [comment]
keep in mind that this does not need to be perfectly styled.

**Comment by andfletcher** [comment]
Check if we can do this easily with dune, if not rethink if we should not start with #1215

**Comment by compojoom** [comment]
The agent dashboard should now be done and lives over here:
https://dune.com/beamerbridge/beamer-v1-agent-dashboard

I've written docs in the knowledge base for those who want to get up to speed with dune. 

Other than that - Some quries that filter on the agent would need to be modified at about the middle of february, because dune is going to change the column type of address fields. Currently it is varchar, but it will be a binary. 

We have quries like this:

```sql

SELECT
  *
FROM
  beamer_bridge_v1_optimism.RequestManager_evt_ClaimMade
where
  requestId not in (
    SELECT
      requestId
    FROM
      beamer_bridge_v1_optimism.RequestManager_evt_DepositWithdrawn
  )
  AND 
        (
        CASE
          WHEN '{{agent}}' != 'all' THEN claimer = lower('{{agent}}')
          ELSE claimer != ''
        END
      )

```

The agent is a parameter and currently I treat the value passed to it as a string. The problem is that whenever the column data changes to binary this query won't filter. 

Ideally the change I wanted to be would be:
```
CASE
          WHEN '{{agent}}' != 'all' THEN claimer = {{agent}}
          ELSE claimer != ''
        END
```

The problem with this is that it fails whenever the user has selected `all` as parameter. 

A suggestion from discord is to do it like:
```
SELECT
  *
FROM
  beamer_bridge_v1_optimism.RequestManager_evt_ClaimMade
where
  requestId not in (
    SELECT
      requestId
    FROM
      beamer_bridge_v1_optimism.RequestManager_evt_DepositWithdrawn
  )
  AND 
        (
        CASE
          WHEN '{{agent}}' != 'all' THEN cast(claimer as varbinary) = cast('{{agent}}' as varbinary)
          ELSE claimer != ''
        END
      )
```

This is a little verbose and I didn't do it, because I still think that I might come with a better solution. 

We currently have one agent claiming that there might be an edge case in the data, but I think that we can close this issue and open new for whatever else we need.

**Comment by fredo** [comment]
what's the status here?

**Comment by andfletcher** [comment]
Done
