### ISSUE TITLE
Increase Minimum Validity Period in contracts

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1199]
We have a minimum validity period of 5 minutes and maximum of 30. The validity period determines the time window where the agent can safely make his claim. 5 minutes might be too low.

@andfletcher we need a decision on the values here.

## Acceptance criteria
min: 30 min
max 48 hours

To give us the flexibility in the next deployment in casy of anything happens. Will be reevaluated before the next (next) deployment.

**Comment by istankovic** [comment]
Regarding the minimum value, at the retreat @fredo mentioned 20-30 min would be reasonable. I'm leaning slightly more towards 30 min, to be a tiny bit more conservative.

Regarding the maximum value, I'm thinking of a couple of hours, say 3 or 4. (I don't consider this too critical.)

There is one other value we should consider -- the one in the frontend, which will presumably be used by the vast majority of transfers. From my point of view, I think the current value of 30 min is a well balanced value so I think we should just continue using it.

**Comment by fredo** [comment]
Decided to 
min: 30 min
max 48 hours

To give us the flexibility in the next deployment in casy of anything happens. Will be reevaluated before the next deployment.

**Comment by andfletcher** [comment]
Additional information: 
the frontend will have the min time. 48 hours just gives us the flexibility on increasing if we really need to.
