### ISSUE TITLE
Allow new claims after request expiry

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1202]
Claiming is only possible before the request expiration. After expiration it is only possible to withdraw the tokens and send them back to the user. This is a hard 0/1 requirement.
We initially introduced this condition to enforce the agent not to fill requests after expiration. Because he wouldn't be able to claim the tokens back, it wouldn't make sense to fill it in the first place. Even if the fill was correct it would effectively be giving tokens away for free.
Thinking about this I don't see any harm to allow claims after request expiration. The effective change here would mean that a user is still able to withdraw its tokens, with the same conditions as today (there must not be any active claims), but it is also possible for an agent to claim that he filled the request.
It still does not make sense for the agent to fill requests after expiration because the user has the option to withdraw its tokens, so most likely the agent software would not change, and the above measurements are still enhancements to the current code base.
For a rationale behaving agent it would simply be to risky filling a request which is expired or close to expiration, because he risks losing its tokens (same as in the current code base).
But if any unforeseen events happen and the agent was not able to claim a valid fill, he would still have at least the chance to rightfully claim its tokens. I don't really see a new attack vector opened to this change and don't see the point of not allowing new claims after request expiration.

Upon trying to claim in `beamer.chain.claim_request()`, the agent should not transition the request into the ignored state, if it is expired. This is because it is theoretically always possible to claim (not only before the request is expired)

### What is the benefit for the agent?
If in any case the agent software is too slow to claim or has a downtime, then the agent will still have the possibility to claim back the tokens if the user did not withdraw. In all cases where (honest) users only wait for the fill and then move on (i.e. users of our frontend), the agents will most likely be able to claim the tokens at a later point in time.

Open questions:

We would need to think about the flow in the frontend that it supports such events (basically enabling the withdraw button after expiration, but also disable the button again if a claim arrives. Additionally, continue to listen for fills and mark the request as being filled if a valid fill arrives, even though the request already expired) @GabrielBuragev Let's discuss this.

## Acceptance criteria
- [ ] agent can withdraw after request expiration 
- [ ] there exists a final timeline after which no claims are allowed (24 hours)

## Additional information
this is for an honest case (the agent was not able to claim in time) so we will give him more time to claim but it will not have a change on the user's side

**Comment by andfletcher** [comment]
https://github.com/beamer-bridge/beamer/issues/1211 frontend end issue.
