### ISSUE TITLE
Agent checks time until expiry

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1203]
The agent should check how much time is left until expiry before filling a request. Ideally, the agent should be able to configure a value where he is comfortable with filling.

In this way, the agent can go up online and only fill requests which are long enough valid as configured by the entity behind.

- Default value 10 minutes
- Users get a warning message once at startup if they configure the check time to be greater than the maximum validity period.

**Comment by andfletcher** [comment]
We currently did not include giving the user a warning if the time is set to low. Maybe when this issue is done we have a better understanding of what we would consider as to low.
