### ISSUE TITLE
Frontend: Rephrase "Use Max" button & related tooltip content

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1206]
# Rationale
We need to provide a more intuitive label for the "Use Max" button & it's related tooltip text.
Currently it is not so clear that the button is clickable.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/18466333/203093696-4928cf17-5833-465e-a2c3-ca79afd0966a.png">

---

TLDR; of the discussion in this issue and what needs to be done:
- [ ] Follow sushiswap's approach - change the text inside the button to "Balance: xxx USDC" and leave the `click` functionality.
<img width="393" alt="image" src="https://user-images.githubusercontent.com/85872820/204548569-38ccca77-df7e-4758-86bb-30f14d3065c2.png">

- [ ] Change button tooltip text to `You have {{tokenAmount}}  {{ tokenSymbol }} in your wallet`

**Comment by DBecane** [comment]
I would simpy use "Max" as this seems to be the most intuitive. We do not need to display the maximum amount that people have available - they can figure out by clicking "Max"

<img width="387" alt="image" src="https://user-images.githubusercontent.com/85872820/203591048-fbfc9d54-7d79-45c5-b798-a3e5d3d28858.png">

**Comment by GabrielBuragev** [comment]
The reason why we don't have a "Max" button is because the whole form is currently too small, which makes the input field pretty limited with space and therefore adding a "Max" button inside it would look too crammed.

@olympe-silve Do you have any idea how to approach this?

**Comment by GabrielBuragev** [comment]
After a quick discussion with @DBecane, we both agreed that the current form size is hindering the improvement of the UI/UX and therefore needs to be addressed now.

In order to tackle this issue we will need to:
- Increase the width of the whole form (for big screen devices) to allow the inclusion of elements such as the "MAX" button as shown in the example screenshot posted in the comment above.
- @DBecane will try to find a solution for an icon substitute to the "MAX" label for mobile devices so we can be sure it fits on small screens as well.
- The tooltip showing the exact token amount inside the user's wallet balance should still stay but with shorter text:
`You have X {{ tokenSymbol }} in your wallet`
- Remove the current text below the token amount input


@olympe-silve @manuelwedler What do you think?

**Comment by manuelwedler** [comment]
I just think @olympe-silve should decide on that. Having different layouts for mobile and desktop also increases the complexity of the frontend. Besides, the tooltips on the buttons don't really work on mobile.

**Comment by GabrielBuragev** [comment]
@DBecane I like the sushiswap version. I think we can proceed with your suggestion for the time being.

I updated the issue description so it can be properly estimated and planned upon.
