### ISSUE TITLE
Frontend: Implement a toast notification reusable component

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1210]
# Rationale
In order to improve UX we need to integrate a toast notification component which will allow us to give feedback to the users on certain actions on our app and/or status of transfer/transaction requests.

# Implementation specs
- Implementation should be generic and reusable. (easily adding new notifications across the app codebase)
- Preferably, it should be implemented/integrated as a floating card that fades away after N seconds by default or closeable by a user action.
- The position of the card should be configurable. 
- Top-right by default? (most intuitive position IMO)

**Comment by andfletcher** [comment]
Close and added acceptance criteria into https://github.com/beamer-bridge/beamer/issues/1209
