### ISSUE TITLE
Frontend: Allow new claims after request expiry

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1211]
# Rationale
Once https://github.com/beamer-bridge/beamer/issues/1202 is implemented on the contract level, we have to update the frontend accordingly.
This contract update affects the way the frontend evaluates expired requests. 

Currently, the frontend marks a request as expired once it passes several condition checks (triggered only once):
- Request expired by local clock (by comparing against `validUntil` timestamp)
- Request expired by RPC clock (by comparing against `validUntil` timestamp)
- Request has no active claims

What this contract update means for the frontend is that we cannot mark a request as expired after passing the previous mentioned conditions once. That means, we will have to re-evaluate if these conditions are still true even when the user sees the "Withdraw tokens" button and tries clicking on it.

# Acceptance criteria 

- [ ] Check if we can have a realtime check by using global filter for ClaimMade events
- [ ] Frontend needs to reevaluate transfer expiry on clicking "withdraw tokens" and allow/disallow withdrawing accordingly
- [ ] Give the user some feedback in case he cannot withdraw his tokens - sentences to be aligned on during the work on this issue.

**Comment by andfletcher** [comment]
https://github.com/beamer-bridge/beamer/issues/1202

@GabrielBuragev please add description and missing acceptance criteria

**Comment by GabrielBuragev** [comment]
:heavy_check_mark:
