### ISSUE TITLE
Frontend: Fix layout & paddings

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1213]
<img width="286" alt="image" src="https://user-images.githubusercontent.com/18466333/203241638-14c950d5-324a-4dec-bbae-90596f0cb4c4.png">

# Rationale
Many community members expressed the inconvenience of the paddings around the "Terms & Conditions" check input below the form. Currently it's really hard to press the check input due to its small size & paddings.
We should rethink how we display this check input and/or increase the paddings between the elements.

## Acceptance Criteria
- [x] Paddings between the elements is increased
- [x] Check button size is increased
- [x] Form layout is improved so it allows new elements to be inserted at the end of the form without the need of absolute positioning

**Comment by manuelwedler** [comment]
Is this something @olympe-silve should be involved?

**Comment by GabrielBuragev** [comment]
Yes, for the first 2 tasks.

**Comment by GabrielBuragev** [comment]
Closed by #1351

**Comment by andfletcher** [comment]
Checkbox was move to wallet connect part.

**Comment by andfletcher** [comment]
closed also since we have #1219
