### ISSUE TITLE
Subgraph: Improvements

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1215]
# Rationale
During implementation of #1191 it turned out that the generated subgraph currently only stores the event in a plain form. This makes it hard to query for this specific use case in the issue - like getting the unclaimed, claimed and finalized requests. 

# Implementation
The new graph should have an entity for Request, Claims, Fills - the request should have one-to-many relations with the claims and fills. And depending on the status of the fills be "unclaimed, claimed, finalized".

**Comment by compojoom** [comment]
No, we aren't using the graph in the monitoring script. As to whether this is required - I don't know. We'll have to discuss in the team if we want to invest time in the graph.

**Comment by andfletcher** [comment]
Are we currently using graph for anything? @compojoom ?

**Comment by compojoom** [comment]
Not that I know of.

**Comment by GabrielBuragev** [comment]
The plan was to use the subgraph for this issue: https://github.com/beamer-bridge/beamer/issues/1125

**Comment by compojoom** [comment]
I'm closing this as this is now completed. 

Unfortunately since the bridge events are happening on different chains e.g:
request on chain A
fill on chain B
claim on chain A
etc.

It was not possible to have a single object that contains all the data related to a bridge transfer. (this is still doable by implementing a supergraph that would then fetch from the individual graphs and return one object, but that was not necessary for the moment)

Now the request has a claim and withdraw, but is missing the fill event. In the happy case if you have a request with a fill, one could assume that there is also a corresponding fill, but better to verify by looking for the fills on the target chain subgraph after getting the request from the source chain subgraph.
