### ISSUE TITLE
Frontend: Too many decimals error breaks layout

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#1219]
Small layout issue with the input validation error messages: When using more decimals than allowed by the selected token, the error message breaks the layout by letting the upper box grow. So the box moves in an ugly way while the user types.

Looks like this only happens on Firefox.

#### Expected behavior
The text fits the line below the input.

#### Actual behavior
![image](https://user-images.githubusercontent.com/34456797/203328980-9abe3852-2370-4127-b604-517a889d030b.png)

#### System
Firefox 107.0

**Comment by GabrielBuragev** [comment]
When i was implementing the validation, i struggled finding a good name for this specific message.
I would really like to hear the opinion of others and hopefully improve this!

**Comment by GabrielBuragev** [comment]
Should we consider this a bug?

**Comment by manuelwedler** [comment]
The whole box moves while the user types. I would consider this a bug.

**Comment by GabrielBuragev** [comment]
Same for this error message.

![image](https://user-images.githubusercontent.com/18466333/203508315-93b0918d-3dd0-4f85-9727-a0000524cddf.png)

We can combine them in this issue

**Comment by manuelwedler** [comment]
Cannot reproduce this one :/ For me it is in one line. But I also think the error is a bit misleading as it is only displayed because of the dot.

**Comment by andfletcher** [comment]
fixing this resulted in a bigger redesign / fix of the layout.
