### ISSUE TITLE
Update contributing docs & improve "getting started" steps

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1230]
There is a missing step to build the relayers, otherwise the agent won't run.
Additionally, we have to either fix the make target for relayers that the binaries are stored at `data/relayers` or add an additional step in the docs that one has to do that manually. I prefer the first option.

- [x] Add `make relayers` to contributing docs
- [x] change relayers target in make file so that binaries are stored in `data/relayers` 
- [x] add .gitignore for `beamer/data/relayers`
- [x] the relayers step should not add pkg package - it should be part of the package.json

Currently we can't know whether the docs under the contributing section https://docs.beamerbridge.com/contributing.html are still correct. I propose that we pack all the steps that are necessary to get started in a make "setup-local-dev-environment" and have a circleCI step that executes it in order to make sure that it is still correct.

- [ ] make a "setup-local-dev-environment" step in the make file
- [ ] setup circleCI to execute the above step
- [ ] Think on ways to keep in sync the steps in the make file with the docs contributing page

Other getting started issues. 
If you just run `make`  one would most probably get an error like this:
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/693770/204540871-3b258a71-d9d2-4203-bd38-344bc0a78d34.png">

- [ ] Most people don't have prettier and prettier-plugin-solidity installed globally. Since our project relies on them, we should make sure that they are set as locally required dependencies.

- [ ] the request library https://pypi.org/project/requests/ is being imported directly in the code, but it is nowhere defined in the pyproject.toml file. Currently that works because web3 requires it. 

- [x] fix the typos in the 'beamer-agent' command

- [ ] the docs are written in a way that suggest that you can execute them from top to bottom in the same shell. The problem is that We first for example define a variable `TOKEN_ADDRESS`, but afterwards starts the agent - the agent output is in the current shell, so we have to open a new one. When you open a new one the `TOKEN_ADDRESS` that was defined in the other shell is not there. So one need to re-execute this command. 
- [ ] For MacOS users, `coreutils` is a requirement (`brew install coreutils`). It covers commands like `realpath` which is not found on MacOS by default and yet used by our `arbitrum.sh` script.

**Comment by istankovic** [comment]
I checked the boxes on things that #1239 is fixing.
