### ISSUE TITLE
Test OP relayer in e2e script

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1242]
We want to be able to test the relayers locally. We can integrate them into the e2e test script. 

- [x] turn off relayer instances provided by optimism
- [x] fetch optimism addresses from local L1
- [x] provide them to the relayer
- [x] adapt the relayer that it can consume a custom network for optimism
- [x] adapt the scripts to run the optimism relayer

**Comment by andfletcher** [comment]
@andfletcher create a followup issue for arbitrum

**Comment by GabrielBuragev** [comment]
@andfletcher have you already created a followup issue for arbitrum?
