### ISSUE TITLE
Validate json schema of deployment config file before deploying

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1275]
# Rationale
In order to improve the deployment process we need to validate the deployment config file before or at run-time of the deployment script. This will prevent running the deployment process when the config file contains invalid properties and value types. 
We gain two benefits from this:
- Avoiding costs for re-deploying due to invalid config file structure
- Less time spent for debugging when deployment fails

We can do this by using a json schema validator to validate the corectness of the deployment config files (`scripts/deployment/*.json`).
# Acceptance criteria

- [ ] Json schema is being validated on run-time of the deployment script
- [ ] Deployment script throws an error and stops when an invalid schema has been detected. (no contracts are deployed)

**Comment by istankovic** [comment]
Thanks @GabrielBuragev for creating this issue. :bowing_man: 

I would also add that we should make sure that all the addresses present in the config file are checksummed addresses.

**Comment by GabrielBuragev** [comment]
@istankovic I believe this will be closed as a part of the https://github.com/beamer-bridge/beamer/pull/1577 PR?

**Comment by istankovic** [comment]
> @istankovic I believe this will be closed as a part of the #1577 PR?

Yes, exactly.
