### ISSUE TITLE
Relayer: Implement Boba network relayer

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1277]
# Rationale
While working on https://github.com/beamer-bridge/beamer/issues/687 i realized that we are lacking support for Boba network inside our relayer implementation.

Talked to the boba people and i got the following response: 
`We handle the tx from L1 to L2, but not from L2 to L1.`

This means that a relayer implementation in the direction `L1 -> L2 Boba`  is not needed but `L2 Boba -> L1` is necessary. 

### Why should this feature exist?
The relayer is one of the crucial components of our bridge. It is responsible for relaying the messages that are sent between the rollups. This happens when a challenge on one of the rollups needs to be relayed to L1/destination L2.
  
### What are the use-cases?
The relayer needs to support sending messages / challenge resolutions from L2 Boba via L1 to the destination L2.

# Acceptance criteria

- [x] Boba relayer service is implemented
- [ ] Relayer program is able to recognize boba as a supported network (mainnet & Goerli) & run the boba relayer service

**Comment by andfletcher** [comment]
@GabrielBuragev is this something that the agents will then run or do we need to run this centralized?

**Comment by GabrielBuragev** [comment]
The agent software is running the relayer on demand. We are not hosting this.
