### ISSUE TITLE
Ape ganache implementation should support gas profiling

### ISSUE THREAD

**Issue by bilbeyt** [beamer-bridge/beamer#1286]
This is a subtask of #1079 and this is needed for us to profile gas in tests.

This issue is needed because we had this option in brownie, but with ape-ganache this is not working anymore. This is a nice to have feature.

Acceptance Criteria:

[ ] Check ape-ganache and implement the feature then talk with ApeWorx to merge it.

**Comment by istankovic** [comment]
@bilbeyt this still relevant?

**Comment by bilbeyt** [comment]
> @bilbeyt this still relevant?
No, closing it
