### ISSUE TITLE
Relayer: Add CI tasks for relayer

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#1291]
# Rationale

The relayer grew bigger and gets its own tests, linting and build. All of these should be checked in the CI.

# Implementation

Just add the workflow for running the respective npm scripts to our CircleCI configuration. Should follow the config of the frontend CI.

**Comment by GabrielBuragev** [comment]
Close here https://github.com/beamer-bridge/beamer/pull/1312
