### ISSUE TITLE
Relayer: add unit tests

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#1296]
We merged the new relayer without having unit tests. We decided to use jest as a test runner. We should achieve basic coverage with the unit tests. We decided to not unit test the inner relaying mechanisms (subclasses of `BaseRelayerService`) because they heavily rely on libraries which are difficult to mock.

**Comment by istankovic** [comment]
@GabrielBuragev shouldn't this be closed now?
