### ISSUE TITLE
Perform agent L1 resolution test on Goerli testnet

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1300]
### Setup

- [x] Setup agents in server for goerli

### Test
* make a transfer request
* make a transfer request
* make sure the request is filled by one of the agents
* challenge the corresponding claim
* check whether the agent responds to the challenge
* wait for the fill message to finalize
* make another challenge (within the same challenge game) with enough funds to go to L1
* make sure the agent triggered L1 resolution
* wait for the results to appear on the source chain
* check that the agent was able to withdraw

# BOBA
- [x] make a transfer request
- [ ] make sure the request is filled by one of the agents
- [ ] challenge the corresponding claim
- [ ] check whether the agent responds to the challenge
- [ ] wait for the fill message to finalize
- [ ] make another challenge (within the same challenge game) with enough funds to go to L1
- [ ] make sure the agent triggered L1 resolution
- [ ] wait for the results to appear on the source chain
- [ ] check that the agent was able to withdraw

# Optimism
- [x] make a transfer request
- [x] make sure the request is filled by one of the agents
- [x] challenge the corresponding claim
- [x] check whether the agent responds to the challenge
- [x] wait for the fill message to finalize
- [x] make another challenge (within the same challenge game) with enough funds to go to L1
- [x] make sure the agent triggered L1 resolution
- [x] wait for the results to appear on the source chain
- [ ] check that the agent was able to withdraw

# Arbitrum
- [x] make a transfer request
- [x] make sure the request is filled by one of the agents
- [x] challenge the corresponding claim
- [x] check whether the agent responds to the challenge
- [x] wait for the fill message to finalize
- [x] make another challenge (within the same challenge game) with enough funds to go to L1
- [x] make sure the agent triggered L1 resolution
- [x] wait for the results to appear on the source chain
- [ ] check that the agent was able to withdraw

**Comment by GabrielBuragev** [comment]
@fredo @istankovic should we close this issue or should we do another round of tests after the automatic withdrawal is implemented on the agent's side?

**Comment by GabrielBuragev** [comment]
Ignoring boba as we decided to stop the support there.

**Comment by fredo** [comment]
> @fredo @istankovic should we close this issue or should we do another round of tests after the automatic withdrawal is implemented on the agent's side?

I would definitely do another test round once #1324 is fixed

**Comment by bilbeyt** [comment]
@GabrielBuragev if mainnet works fine with withdrawls and boba is discarded, can we think of this as done ?

**Comment by GabrielBuragev** [comment]
@fredo your thoughts?

**Comment by bilbeyt** [comment]
@fredo what do you think ?

**Comment by fredo** [comment]
@bilbeyt @GabrielBuragev Yes I'm with you, closing in favor of successful mainnet test
