### ISSUE TITLE
contracts: Add automatic withdraw inside ArbitrumL1Messenger

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1314]
# Rationale
In order to avoid confusion & forgotten funds inside our Messenger contracts by our agents, we should add support for automatic withdrawing of the deposited funds at the time of a `sendMessage` execution.
Currently, we expect the agents to have a decent amount of funds deposited inside the ArbitrumL1Messenger in order to relay an L1 resolution message. 

After discussing this with @fredo we agreed that by invoking the `withdraw` function inside the `sendMessage` function we will be able to reduce the costs for this operation from `2x 0.00021 ETH (gas limit) + opcode fees` to `0.00021 ETH + opcode fees`.

# Acceptance criteria
- [ ] Contracts return the deposited funds right after propagating the message that is being executed on L1
## Additional information
- [ ] Manual withdraw will be kept the way it is

**Comment by andfletcher** [comment]
Done
