### ISSUE TITLE
Agent: Avoid running multiple relayer subprocesses in parallel for the same challenge game 

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1320]
#### Expected behavior
Agent should spawn only one relayer subprocess for a specific challenge game at a time.

#### Actual behavior
Agent is spawning the relayer subprocess for every `ClaimMade` event found in the challenge game. The more challenges were made the more instances of this subprocess are created in parallel.

# Acceptance Criteria
- [ ] Agent is spawning only one relayer subprocess at a time for a specific challenge game

**Comment by istankovic** [comment]
How hard would it be to add a test for this to our test suite?

**Comment by fredo** [comment]
I think here it would be easy to fix this because we already store a flag in the agent that a process is running. 
We just have to check the flag before creating a new process.
a test for this should be trivial

**Comment by istankovic** [comment]
Possibly related to #1085.
