### ISSUE TITLE
Incorrect token allowance

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1340]
Use current master and launch app with --mode staging. 
Try to transfer from optimism to arbitrum (maybe from where to where doesn't matter, but haven't tested).

Set an amount that you want to transfer that is higher than anything you've allowed. Submit. Metamask asks you to confirm the allowance and once we do the transfer fails with  insufficient balance.

![image.png](https://images.zenhubusercontent.com/57fc927995e42b6c5baa439a/bedcd17a-1018-450f-b43b-b5210192fa99)

I think that the issue is that we don't account for the transfer token fees. 
So, if I transfer 50, we actually need 51, but we only set the allowance to 50.

**Comment by manuelwedler** [comment]
If I start with a new account that has not given any allowance to our contracts, the failure immediately happens with the first transfer I try to do in any case. That's really bad. 
I checked the values and it is actually the case that the fee is not included in the allowance.
