### ISSUE TITLE
Rework agent's config to address multi rollups support

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1353]
The config currently is not really designed to serve for multiple rollup to rollup connections. As we will merge agent instances into a single process in #654, we should also address this in the config.

My idea is to have high level keys for a chain (we already have this for rpcs) and store all information regarding this chain under this key. This would also include tokens. 

This issue needs more discussion and should be blocked by #654

**Comment by andfletcher** [comment]
This issue can be closed.
