### ISSUE TITLE
Investigate chainlink sequencer health oracle

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#137]
See https://docs.chain.link/docs/l2-sequencer-flag/

This might be helpful when deciding of we take new requests.

**Comment by istankovic** [comment]
@fredo do you know what this is about?

**Comment by fredo** [comment]
this could have something to do with downtimes of the sequencer but I really don't know

**Comment by istankovic** [comment]
As it stands, there is not much sense to keep this open anymore so I'm going to close it.
