### ISSUE TITLE
Insuficient allowance

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1389]
Some of the transactions made end up with "insuficient allowance" error on chain. This happens only if the user has submitted a tx and doesn't wait for it to get mined, but immediately starts a second transfer for the same amount or lower. 

When he does this - we check that he his allowance is correct on chain, but since the allowance was set by the previous transfer, but the actual transfer has not yet happened the returned check is OK and we proceed to submitting the transaction. Now since the user has 2 tx in the queue - the second transaction fails because the first exhausted the allowance. 

The only good solution I could think of is to forbid a second transfer while there is still a pending tx (not a pending fill, but an agent, but a pending user tx)

So forbid the transfer if there is a transfer with any of the following steps active:
- ensureTokenAllowance
- sendRequestTransaction
- waitForRequestEvent

**Comment by istankovic** [comment]
This happens only if the user is doing this for the same (chain, token) pair, right? In other words, we should not see the issue with unrelated tokens and chains, right? If so, I would then only restrict if the second request is related to the same (chain, token) pair.

**Comment by compojoom** [comment]
yes, yes... Started working on this yesterday already. Currently writing tests...
