### ISSUE TITLE
Flickering when transfer in progress

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1390]
If you have a previous transfer in the queue the previous transfer flickers in the UI. For some reason the min-height property is always changing between 20px and 470px

![2023-01-19 09 17 02](https://user-images.githubusercontent.com/693770/213389917-c0c53434-f80a-4234-bb85-960a2f633208.gif)

**Comment by istankovic** [comment]
Thanks for creating this issue, I experienced this too!
