### ISSUE TITLE
Relayer: Allow custom networks to be used for Arbitrum

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1413]
# Rationale

Now that we have the relayer implementation for all rollups and basic unit test coverage, we want to expand it by integrating it into our local E2E tests.
Our relayers are currently supporting only known chain ids (Goerli & Mainnet). 
This means that we need to extend its implementation to support running on local networks by allowing custom network configurations.

## How to implement
The current design comprises of separate relayer services for each rollup that we support. 
After a discussion with @istankovic we decided that we will keep the logic for extending network support inside the specific relayer classes instead of writing a separate E2E bootstrapping module (as initially proposed).

In order to achieve this we need to:
- extend the relayer CLI to accept 2 more optional arguments (file paths) for specifying the config files from which the relayer services will read & extend their SDK's.
- Reading, parsing & extending the SDK will be done inside a method in the rollup specific relayer implementation
- Triggering the network configuration will be delegated by the main service file after successful detection of the passed arguments.

# Acceptance criteria 
- [ ] Arbitrum relayer has its own implementation for custom network support.

**Comment by andfletcher** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1413?planning-poker) with Zenhub @bilbeyt @istankovic @compojoom @GabrielBuragev

**Comment by istankovic** [comment]
This has already been done and the code will be incorporated in the PR done under #627.
