### ISSUE TITLE
Add aeth and oeth to our bridge

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1424]
## Description
As an additional token but also in preparation of us allowing bridge volume between rollups and the Ethereum chain we want to enable beamer users to bridge rollup "nativ" eth

## Acceptance criteria
- [ ] Users are able to bridge eth between Arbitrum and Optimisim

**Comment by fredo** [comment]
why do we need this as preparation?

**Comment by andfletcher** [comment]
more business and marcomms related.

**Comment by andfletcher** [comment]
Frontend: 
Add token config file
Include token in the chain config files

**Comment by andfletcher** [comment]
Ok so replaced weth with eth that is dedicated to the individual rollup, aeth and oeth.
