### ISSUE TITLE
Add multiple EventProcessors based on configuration

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1427]
We consume the configuration and need to create multiple EventProcessors per chain pair per direction. 
The Eventprocessors need to subscribe to the correct EventMonitors.
The web3 objects and contract objects should be cached only created once (and reused in the EventProcessors).
Additionally, we should take care about the logging. Chain Ids shouild be added so that we understand where the logs come from.

- [x] Create EventProcessors per chain pair and direction
- [x] Update documentation
- [x] Update run your own agent files

**Comment by bilbeyt** [comment]
https://github.com/beamer-bridge/run-your-own-agent/pull/13 for run-your-own-agent

**Comment by fredo** [comment]
this can be closed, right? @bilbeyt

**Comment by bilbeyt** [comment]
> this can be closed, right? @bilbeyt

was pretty sure i closed this, but sometimes it happens i guess
