### ISSUE TITLE
Max Amount Error - Report from Community

### ISSUE THREAD

**Issue by DocSmoove** [beamer-bridge/beamer#1439]
#### System information

Below is the video that the community member noticed. When a user clicks "max amount" and then deletes the amount, an error appears. 
Uploading 010101011 (1).mov…

#### Expected behavior
The error should not appear
@GabrielBuragev

**Comment by andfletcher** [comment]
@DocSmoove can you reupload the video and wait a bit longer. You created the issue without the video being uploaded.

**Comment by DocSmoove** [comment]
https://user-images.githubusercontent.com/107990484/216257746-3b2c1e75-33d8-4354-8262-09108a5eef7a.mov

Ah, my bad. Here is the uploaded video. @andfletcher @GabrielBuragev
