### ISSUE TITLE
Frontend: Metamask redirects to onboarding even though extension is installed

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1449]
A few community members reported this bug.

#### Expected behavior
When MetaMask extension is installed the MetaMask wallet selection on the frontend should open the extension connection pop-up.

#### Actual behavior
Sometimes, even though MetaMask extension is installed, when the user clicks on MetaMask wallet selection they are being redirected to the onboarding page (extension install).

#### Steps to reproduce the behavior
Not yet clear. Happens rarely and on different browsers and different versions of MetaMask.

**Comment by andfletcher** [comment]
8 hours timebox

**Comment by GabrielBuragev** [comment]
So, here is a report from my findings.

In my case, i had installed ["Frame Companion" browser extension](https://addons.mozilla.org/en-US/firefox/addon/frame-extension/) a while ago just to try it out. From that moment on i had 2 wallet provider extensions installed in my browser and that was causing the issue.
Please note that this issue was persistent across all dApps out there not only on Beamer.

By looking at the ["Frame Companion" repo](https://github.com/floating/frame-extension/blob/master/src/frame.js#L41-L51) it is clearly seeable that they are simply overwriting whatever is located at `window.ethereum` without worrying if they are overwriting other wallet provider injections (unless this is explicitly configured inside their desktop app)... I don't believe there is a way to prevent this on our end. We just need to be aware of this problem and prepare/give the right responses to our users.

I was able to catch this error from metamask: `@metamask/detect-provider: Non-MetaMask window.ethereum detected.`.
I think we can utilize this to show some error message to the user to at least let him be aware what the problem might be.

---
For those that are curious about our metamask onboarding flow.

On click of metamask wallet connection option:
1. Try to detect if metamask is injected as `window.ethereum`
    1.1 If metamask object is detected then proceed with metamask connection otherwise go to 2.
2. If metamask object is not detected proceed with onboarding
3. Onboard user by redirecting him to metamask extension installation page
4. Return on page after user installed & configured metamask

**Comment by GabrielBuragev** [comment]
Opened an issue [here](https://github.com/MetaMask/metamask-onboarding/issues/101) in case we want to be able to handle this issue nicely and display the user a proper error message. Until this issue has been resolved, we are not able to provide the user an error message ..

**Comment by istankovic** [comment]
> By looking at the ["Frame Companion" repo](https://github.com/floating/frame-extension/blob/master/src/frame.js#L41-L51) it is clearly seeable that they are simply overwriting whatever is located at `window.ethereum` without worrying if they are overwriting other wallet provider injections (unless this is explicitly configured inside their desktop app)... I don't believe there is a way to prevent this on our end. We just need to be aware of this problem and prepare/give the right responses to our users.

@GabrielBuragev This sounds like a bug in their app. Should we consider submitting a bug report to them if so?

**Comment by GabrielBuragev** [comment]
@istankovic I will try to communicate with them these days. They do however offer the option for the browser to use the metamask injection instead of their injection but it takes some effort to configure that in their extension. 
If a user has just installed Frame Companion and is not extensively using it (is aware of the option to use the metamask injected wallet instead) he will definitely not know why he cannot connect to any dapp out there (just like my experience).

I will proceed like so:
1. Currently MetaMask is logging this message: `@metamask/detect-provider: Non-MetaMask window.ethereum detected.` when we call this: `await detectEthereumProvider({ mustBeMetamask: true })`. 
I believe this should be an exception instead of a simple log as we are specifying in the arguments that we are expecting an exact match for MetaMask. 
[This issue](https://github.com/MetaMask/detect-provider/issues/73) is focused on that and i will submit a PR for it these days.
2. We catch the error by MetaMask and give feedback to the user that he has conflicting wallet extensions(possibly with a hint to disable one).

I also noticed they are really unresponsive and new contributions have a really hard time going through. Check it out: https://github.com/MetaMask/detect-provider/pulls

In parallel, i will try to see if this can be solved on Frame's side and i already have a reference solution for them to use.

**Comment by istankovic** [comment]
> I also noticed they are really unresponsive and new contributions have a really hard time going through. Check it out: https://github.com/MetaMask/detect-provider/pulls

@fredo @andfletcher @compojoom do we have any contacts there so we can push through?

**Comment by istankovic** [comment]
> @istankovic I will try to communicate with them these days. They do however offer the option for the browser to use the metamask injection instead of their injection but it takes some effort to configure that in their extension.

That's nice of them, but it doesn't really change the fact that they have a bug in their default behaviour. I'm guessing not very many people would change the default. So my thinking is we should report bugs both to them and Metamask.

**Comment by istankovic** [comment]
> Yeah, i already saw how Coinbase does it (when you have both Coinbase & MM extensions installed) while i was integrating it and seems like that is the right approach for us the integratoors. Instead of overwriting the complete object, they are creating an array of providers inside `window.ethereum.providers` (which holds both MetaMask & Coinbase) so then the dapp can filter out and decide which provider inside that array is matching the provider options of the app.

Right, that sounds like a reasonable approach.

**Comment by GabrielBuragev** [comment]
MetaMask issue: https://github.com/MetaMask/detect-provider/issues/73
PR for this MetaMask issue: https://github.com/MetaMask/detect-provider/pull/74

**Comment by andfletcher** [comment]
I pinged the person i know
