### ISSUE TITLE
Research Bedrock upgrade

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1456]
Optimism will undergo quite some big architectural change called Bedrock.
We should research if changes affect our contracts and/or if we can optimize our contracts with the upgrade.

**Comment by GabrielBuragev** [comment]
@fredo Can be closed?

**Comment by fredo** [comment]
We need to research the impact of reorgs on L1 still

**Comment by GabrielBuragev** [comment]
We have a separate issue for that: https://github.com/beamer-bridge/beamer/issues/1939

**Comment by fredo** [comment]
closing in favor of #1939
