### ISSUE TITLE
Write L1&L2 messengers contracts for Polygon zkEVM

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1487]
Polygon zkEVM's messenger bridge doesn't really fit our current messenger model. We need to find a valid adaptation for it. 

### Sending message
This is quite trivial. The bridge has the following interface: 

```sol 
    function bridgeMessage(
        uint32 destinationNetwork,
        address destinationAddress,
        bool forceUpdateGlobalExitRoot,
        bytes calldata metadata
    ) external payable;
```

[source](https://github.com/0xPolygonHermez/code-examples/blob/main/zkevm-nft-bridge-example/contracts/polygonZKEVMContracts/interfaces/IPolygonZkEVMBridge.sol#L80-L85)

### Claiming message
On the receiving side the message seems to be needed to be claimed. The interface: 

```sol 
    function claimMessage(
        bytes32[32] calldata smtProof,
        uint32 index,
        bytes32 mainnetExitRoot,
        bytes32 rollupExitRoot,
        uint32 originNetwork,
        address originAddress,
        uint32 destinationNetwork,
        address destinationAddress,
        uint256 amount,
        bytes calldata metadata
    ) external;
```
[source](https://github.com/0xPolygonHermez/code-examples/blob/main/zkevm-nft-bridge-example/contracts/polygonZKEVMContracts/interfaces/IPolygonZkEVMBridge.sol#L100-L111)

### Message receiver
In contrast to our other implementations, the message receiver (in our case the request manager for L1->L2 and the resolver for L2 -> L1) have to implement a certain interface:

```sol
interface IBridgeMessageReceiver {
    function onMessageReceived(
        address originAddress,
        uint32 originNetwork,
        bytes memory data
    ) external payable;
}
```
[source](https://github.com/0xPolygonHermez/code-examples/blob/main/zkevm-nft-bridge-example/contracts/polygonZKEVMContracts/interfaces/IBridgeMessageReceiver.sol#L8-L14)

This means, it cannot be an arbitrary call, but this call has to implement the above interface. So we cannot call the resolver directly since it doesn't implement the MessageReceiverBridge.

## Suggested solution
We have two things which are different to our current model - The message receiver interface and getting the origin address

### Implementing MessageReceiver interface
Since this is special to the Polygon zkEVM bridge, this should not be reflected in our general purpose contracts but rather handled in the messengers.
In order to make this work we know that the cross chain call will only be stored in `data` and handled as bytes not as calldata. In order to receive the message on the other side we need a intermediate contract which will implement the above interface and be the receiver of the L1 message. It can also directly verify that the origin address is expected (verify the trusted call chain) as it gets the origin address passed along with the message. Then it takes the message and executes it on the resolver.

The trusted call chain for the Polygon case would look like 

`Fill manager -> L2 Messenger -> NATIVE BRIDGE -> Receiver -> Resolver -> L1 Messenger -> NATIVE BRIDGE -> Receiver -> Request Manager` 

(We could think of merging some of the contracts but it's not necessary). 

### callAllowed check
The call Allowed check is there to check the origin address for this particular message. Polygon zkEVM doesn't provide such a resolution. However the origin address can be verified upon claiming the message directly, as it gets passed to the message receiver.
In order to make callAllowed work as intended we could introduce an origin address mapping in the receiver contract which could be checked during callAllowed. Thus the Receiver, located in the trusted call chain directly after the native bridge, takes up some of the duty other native bridge provide by themselves.

**Comment by fredo** [comment]
In general we could think about taking over this kind of message bridging interface and standardize our trusted call chain communication (it may come at the cost of additional noop calls for chains where we could directly call the resolver).
