### ISSUE TITLE
research on Polygon zkevm messenger

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1491]
**Description**
Polygon ZKEVM is our next desired rollup, but we are unsure how the messaging works. So we should invest some time in this. 

We are in contact with the Polygon ZKEVM team and they have provided us with this document: 
https://docs.google.com/document/d/176_eB9eIy3quWPLbmlKyNCaAkiqvTouqh-iy9Cogq2g/edit

@fredo also created 2 tickets on https://developersupport.polygon.technology/ 

## Acceptance criteria

We have a clear understanding on 
- [x] Messaging
- [ ] how we get data on the original sender
- [x] how we can test this

**Comment by andfletcher** [comment]
@fredo can you add the two links of the tickets you created if you have them?

**Comment by andfletcher** [comment]
timeboxed for 8 hours

**Comment by fredo** [comment]
https://zkevm.polygon.technology/setup-local-node

**Comment by fredo** [comment]
https://github.com/0xPolygonHermez/code-examples/blob/main/zkevm-nft-bridge-example/contracts/ZkEVMNFTBridge.sol
