### ISSUE TITLE
Add DAI to our bridge

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1498]
As a User I want to be able to bridge DAI

- [x] Add DAI to the token list 
- [x] Create DAI token contract config file 
- [x] add DAI token to the chainconfig file
- [x] add DAI to runyourown agent docus

**Comment by andfletcher** [comment]
Add separate issues for following:
- [ ] Add DAI to dune dashboard
- [ ] Add DAI to the monitoring script

**Comment by fredo** [comment]
what about the task: 

- [ ] UpdateToken for DAI on current deployment

**Comment by manuelwedler** [comment]
Yes, when do we want to release the DAI functionality to the public? Also if we want to have another frontend deployment before I should not update the chain config there.

**Comment by andfletcher** [comment]
Done
