### ISSUE TITLE
System UnExpected behavior

### ISSUE THREAD

**Issue by kingwill3** [beamer-bridge/beamer#1504]
#### System information

OS & Version: Windows/Linux/OSX
Browser & Version: Chrome/Firefox
Commit hash: when using checkout

**Comment by GabrielBuragev** [comment]
Hey @kingwill3 thanks for submitting an issue!

Can you provide us with more information on the bug? 
A screenshot or an error message and some instructions on how to reproduce it on our end should suffice.

**Comment by andfletcher** [comment]
Closing since no real content.
