### ISSUE TITLE
Data on failed transaction

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1538]
For our fee calculation we would need some data on how many failed transaction we actually have for every successful transfer. 
this data could be fetched from dune.

**Comment by andfletcher** [comment]
needs to be included in the calculation

**Comment by GabrielBuragev** [comment]
Prepared the data & queries by using Dune, you can find them here:
https://dune.com/queries/2164770

**Comment by GabrielBuragev** [comment]
Closing as completed.
