### ISSUE TITLE
Support new Fee structure from frontend

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1567]
We will need to make changes to how the frontend pulls the minLPFee and fee duo to #1533 

## Acceptance criteria

- [x] Front end is able to support new fee structure

**Comment by fredo** [comment]
@GabrielBuragev @manuelwedler whats the status here?

**Comment by manuelwedler** [comment]
We didn't merge the PR yet because it could have caused issues if we wanted to deploy the frontend another time before the launch

**Comment by GabrielBuragev** [comment]
We can merge after https://github.com/beamer-bridge/beamer/pull/1686 gets merged
