### ISSUE TITLE
Adjust L1 resolution gas limits

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#163]
Currently the gas limits in the `CrossDomainMessenger.sendMessage` calls are arbitrary chosen.

We need to measure the cost of them and adjust accordingly.

**Comment by istankovic** [comment]
@fredo what do we do here?

**Comment by fredo** [comment]
I think it is fine to stick with the current abitrarily chosen value (1000000). we have seen gas usage of around 800k per L1. not priority right now

**Comment by istankovic** [comment]
Ok, then closing this for now. We can reopen or make a new issue once it becomes relevant.
