### ISSUE TITLE
Write Dune queries for calculating fees on Ethereum

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1632]
# Rationale
Currently we only have queries for Optimism and Arbitrum. 
We need to do the same for Ethereum once the contracts have been deployed on mainnet.

Reference queries:
- ARB: https://dune.com/queries/2255423
- OP: https://dune.com/queries/2250280

**Comment by fredo** [comment]
@bilbeyt is this done?

**Comment by bilbeyt** [comment]
@fredo yes closing.
