### ISSUE TITLE
Adjust all dune queries to use latest deployed contract addresses

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1633]
After re-deploying on mainnet, we need to adjust all the contract addresses used by our dune queries.
Before doing that, we need to submit the latest ABI's to dune for decoding and wait for an approval.

# Acceptance Criteria
- [x] once we have the addresses of the contracts, we need to upload the new ABI in dune to decode
- [x] we wait for them to approve
- [x] fork the dashboard
- [ ] correct all queries

**Comment by compojoom** [comment]
I've now forked the dashboard and forked all queries and changed them to use beamer_v2 contracts. 

Making changes to the fees or adding new queries to output agent earnings on mainnet are currently hard to do as the mainnet contracts don't really have data at this point and all queries return "no results from query"...

I suggest we continue with the modifications of the queries next week when we do the official launch on mainnet or right after our internal tests.

**Comment by compojoom** [comment]
I think that all queries are done now.
