### ISSUE TITLE
Use type 2 transactions for L1 with own gas price strategy

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1657]
The agent is currently using type 0 transactions. Type 0 transactions are pre EIP-1559 transaction types which define `gasPrice`. This leads to the problem that a validator can use up to the full amount of `gasPrice - baseFee` as a tip. 
So we either overprice transactions very much to be sure to be included in time or we risk of not being included due to rising baseFees. 

We can highly optimize this with type 2 (post EIP-1559) transactions. In type 2 transactions we define a `maxFeePerGas` and a `maxPriorityFeePerGas` where `maxFeePerGas` describes the maximum price we are willing to pay. `maxPriorityFeePerGas` describes the maximum tip we are willing to pay for the validator.

So in practice we don't need to "guess" the perfect gas price where we definitely cover the base fee (otherwise the tx cannot be included in the block) and don't overpay the validator.
With type 2 transactions we only pay the base fee + the max priority fee what we have set, even though we would have been willing to pay more if the base fee had been higher.

Update: 

I have found out that web3.py actually uses dynamic fees (post 1559) per default. Only if there is no `maxFeePerGas` or `maxPriorityFeePerGas` and a gas price strategy set or `gasPrice` set in the tx params then static fees are applied. We use a gas price strategy and that's why we use type 0 transactions.

But Removing that is not enough. We need to manually adapt the maxFeePerGas parameter. This can be done via a middleware, but whatever is returned by the RPC is often not enough. I haven't seen `maxFeeStrategies` analog to what we have for the old gasPrice key.
We have have to write our own middleware for this.

[code in web3.py where dynamic or static fees are selected](https://github.com/ethereum/web3.py/blob/3c00810e9a3563c69901549a6a54d4fe19c9d6a9/web3/_utils/transactions.py#L100)

[default values for dynamic fee parameters](https://github.com/ethereum/web3.py/blob/3c00810e9a3563c69901549a6a54d4fe19c9d6a9/web3/_utils/transactions.py#L68)

**Comment by istankovic** [comment]
Thanks for writing this issue, this is quite important!
