### ISSUE TITLE
Automatically pull contract addresses from deployment to relayer

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1660]
Similar to other experiences in the past we encountered a wrong address because it had to be copied by hand into the relayer. 

The relayer could however automatically read all the necessary contract addresses from the deployment.json upon runtime.

An alternative could be to build a deployment specific relayer and read addresses during build time.

**Comment by istankovic** [comment]
> The relayer could however automatically read all the necessary contract addresses from the deployment.json upon  runtime.

:+1:

**Comment by andfletcher** [comment]
closing since duplicate https://github.com/beamer-bridge/beamer/issues/1548
