### ISSUE TITLE
Share experience via twitter after bridge transfer

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1684]
## Description
As a User, I want to share my bridging experience via Twitter once I completed a bridge transfer to share the positive user experience and speed of Beamer Bridge.

## Acceptance criteria
The information displayed on the toast is also sharable via twitter. #1209
Users can share this experience with a prewritten text on Twitter (i have seen this on some other pages, so this might be a Twitter feature.) that includes the information mentioned above (don't include fees or amount transferred)

**Comment by manuelwedler** [comment]
Related: https://github.com/beamer-bridge/beamer/issues/1209

**Comment by andfletcher** [comment]
> @andfletcher I was having an impromptu meeting with Gabriel about the notification system (which I was also not informed of) when he showed me this issue...and I'm confused as to where this decision to add to the user flow comes from. 
> Have you checked with Marketing @DBecane  if a share button is needed ? 
> It is a very small change, sure, but all small changes add up to a more complex UX flow. I'm not against having this feature, but would like to be kept in the loop as to why it is needed (just an @ on the issue is sufficient) and who asked for it. 

@olympe-silve also the desicsion was made by me.

**Comment by andfletcher** [comment]
> @andfletcher I was having an impromptu meeting with Gabriel about the notification system (which I was also not informed of) when he showed me this issue...and I'm confused as to where this decision to add to the user flow comes from. 
> Have you checked with Marketing @DBecane  if a share button is needed ? 
> It is a very small change, sure, but all small changes add up to a more complex UX flow. I'm not against having this feature, but would like to be kept in the loop as to why it is needed (just an @ on the issue is sufficient) and who asked for it. 

@olympe-silve issue #1209 was however a suggestion that was provided to us during the ux audit Session we had as far as i remember correctly.  My add here is just that it is sharable.

**Comment by GabrielBuragev** [comment]
@DBecane @andfletcher i will need your input regarding the text content of the tweet. 
How should the "prewritten text" look like?

**Comment by andfletcher** [comment]
```
I just used @beamerbridge to seamlessly and securely transfer #token from xxx to yyy in xxx seconds! 🔥

Unlock lightning-fast and secure bridging with Beamer today 💪💫 and don't miss out on Beamer's #layerupfest! #beam2L2
https://app.beamerbridge.com/#/
```

**Comment by DBecane** [comment]
Since the Layer Up fest is over, the mention of it needs to be deleted. We'll be leveraging this feature for EThCC @andfletcher to keep track of the fastest transfers at the conference

**Comment by andfletcher** [comment]
@DBecane so is there something that needs to be done here ? Remove the layer up reference? Should we replace it with polygon zkevm ?

**Comment by DBecane** [comment]
Before the 0-Fee campaign: 

```I just used @beamerbridge to seamlessly and securely transfer #token from xxx to yyy in xxx seconds! 🔥

Unlock lightning-fast and secure bridging with Beamer today 💪💫  Now also live on Polygon zkEVM!
https://app.beamerbridge.com/#/```


During 0-Fee campaign- this is a suggestion that might need edits based on the emojis we finally decide to go for. I recommend we keep the Zebra however: 

```Insane! @beamerbridge unlocked 🦓🚣‍♀️  - we don't know for how long, so don't sleep on it 👀

I just securely transferred #token from xxx to yyy in xxx seconds with 🦓🚣‍♀️ and you can do too! 🔥

Unlock lightning-fast and secure bridging with Beamer today 💪💫
https://app.beamerbridge.com/#/```

**Comment by DBecane** [comment]
During 0-Fee campaign- this is a suggestion that might need edits based on the emojis we finally decide to go for. I recommend we keep the Zebra however: 

```Insane! @beamerbridge unlocked 🦓🚣‍♀️  - we don't know for how long, so don't sleep on it 👀

I just securely transferred #token from xxx to yyy in xxx seconds with 🦓🚣‍♀️ and you can do too! 🔥

Unlock lightning-fast and secure bridging with Beamer today 💪💫
https://app.beamerbridge.com/#/´´´

**Comment by manuelwedler** [comment]
Could we create a new issue in the future when such changes are needed? This is messing ZenHub up otherwise.

**Comment by andfletcher** [comment]
@manuelwedler yes not sure why this issue was reused to do this.

**Comment by andfletcher** [comment]
@manuelwedler is it possible to only tweet this message if the fees have been subsidized and if not, show the old message?

**Comment by manuelwedler** [comment]
@andfletcher Yes, that is possible. Can added it to my PR.

Would the fallback then be the following (live on Polygon)? The PR I created is only for this because Dina said we want to show this before the 0-Fee campaign.

> Before the 0-Fee campaign (if necessary and not too much work, otherwise we can discard this change here and directly move to the one below):
> 
> ```
> I just used @beamerbridge to seamlessly and securely transfer #token from xxx to yyy in xxx seconds! 🔥
> 
> Unlock lightning-fast and secure bridging with Beamer today 💪💫  Now also live on Polygon zkEVM!
> https://app.beamerbridge.com/#/
> ```

**Comment by GabrielBuragev** [comment]
> @andfletcher @DocSmoove
> 
> During 0-Fee campaign- this is a suggestion that might need edits based on the emojis we finally decide to go for. I recommend we keep the Zebra however:
> 
> ```
> Insane! @beamerbridge unlocked 🦓  - we don't know for how long, so don't sleep on it 👀
> 
> I just securely transferred #token from xxx to yyy in xxx seconds with 🦓 and you can do too! 🔥
> 
> Unlock lightning-fast and secure bridging with Beamer today 💪💫  
> https://app.beamerbridge.com/#/
> ```

We are reaching the max. character length of the tweet with this text. See screenshot:

![image](https://github.com/beamer-bridge/beamer/assets/18466333/4bc7b780-9609-443d-8513-a07b9808d750)

**Comment by GabrielBuragev** [comment]
@andfletcher We might need to reduce the size of the text

**Comment by andfletcher** [comment]
@GabrielBuragev use this:
"Unbelievable! Just unlocked 🦓 @beamerbridge - it won't last, so don't miss out! 👀

Sent #token from xxx to yyy securely in xxx seconds using 🦓. You can do it too! 🔥

Get lightning-fast and secure bridging with Beamer now 💪💫
https://app.beamerbridge.com/#/"

**Comment by GabrielBuragev** [comment]
`Just unlocked 🦓 @beamerbridge` should be `@beamerbridge just unlocked 🦓` right?

**Comment by GabrielBuragev** [comment]
btw, this also wont work. 21 characters too much

**Comment by GabrielBuragev** [comment]
Ah sorry, my mistake. Your new proposed text works on mainnet however not for the testnet networks (since they have longer names).

**Comment by andfletcher** [comment]
@GabrielBuragev ok for testnet we will need to just keep it shorter but that's not important now.
