### ISSUE TITLE
Change Arbitrum banner into Ethereum banner

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1690]
# Rationale
Launch on Ethereum will replace the Arbitrum launch banner on the website and dapp

# Implementation
Change wording into: "Layer up! You can now bridge from Ethereum L1 to rollups"

**Comment by olympe-silve** [comment]
@andfletcher is this copy validated by marketing @DBecane  ? I'm not in favor of using brackets in info stripes, it adds an extra layer of commentary. If we want to go more specific I would rather just write L1 Ethereum and L2 Rollups and make a decision on semantic consistency

**Comment by andfletcher** [comment]
> @andfletcher is this copy validated by marketing @DBecane ? I'm not in favor of using brackets in info stripes, it adds an extra layer of commentary. If we want to go more specific I would rather just write L1 Ethereum and L2 Rollups and make a decision on semantic consistency

@olympe-silve yes, I copy-pasted it. 
@DBecane your call. but please hurry up.

**Comment by DBecane** [comment]
> @andfletcher is this copy validated by marketing @DBecane ? I'm not in favor of using brackets in info stripes, it adds an extra layer of commentary. If we want to go more specific I would rather just write L1 Ethereum and L2 Rollups and make a decision on semantic consistency

Fully agree with this

**Comment by DBecane** [comment]
"Layer up! You can now bridge from Ethereum L1 to rollups"

**Comment by olympe-silve** [comment]
@GabrielBuragev see the final decision above ! To use on both the website news stripe and the app news stripe. 
Keep the little stars also !
