### ISSUE TITLE
Relayer: Prevent deposits when message was already relayed but not yet finalized

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1693]
# Rationale

The current relayer design has no prior knowledge if the message has already been relayed. In some cases, this leads to redundant multiple deposits in the Messenger contract. 

### Example:
Direction: Any rollup -> Arbitrum

For a message that has already been relayed, any future attempt to relay the **same message** leads to the relayer depositing additional funds into the ArbitrumL1Messenger contract. 
Instead of this, the relayer should skip the `prepare` (depositing) step and move on to the next steps.

# Acceptance criteria
- [ ] Relayer checks if message has already been relayed and skips the logic for preparing (depositing) and relaying the message

**Comment by manuelwedler** [comment]
With my changes to the architecture of the relayer, this is easy. Will address it with my PR

**Comment by GabrielBuragev** [comment]
Hey @manuelwedler, did you make any progress on the relayer architecture? I tried looking for the PR where these changes were incorporated but i couldn't find anything.

Did we simply forgot this? 😄

**Comment by manuelwedler** [comment]
It was shortly before the Ethereum release and there were other priorities, so I simply forgot it. It was also not fully implemented. I just adapted the last relayer service and pushed it here: https://github.com/beamer-bridge/beamer/tree/relayer/step-completion. But there are neither unit tests nor manual tests I did. Have a look, if the architecture makes sense like this.
