### ISSUE TITLE
Collect costs of failed fill transactions for determine contract parameters

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1716]
Currently we multiply only the fill transaction cost with the `failed_fill_transactions` factor. 
For Ethereum costs of a failed fill transaction are only 25% of a successful fill. We can easily extend the query to get the average costs of the failed fill transactions and add the multiplied value to the transfer cost. Therefore estimated costs are more close to real costs.

# Acceptance criteria
- [x] Get avg and median failed fill transaction cost
- [x] Get avg and median successful fill transaciton cost
- [x] Make sure that the failed fill factor is only counting failed fills per successful
- [x] Update the Google Sheet for correct transfer cost calculation

**Comment by GabrielBuragev** [comment]
Dune queries are ready for review:
ETH: https://dune.com/queries/2378580
ARB: https://dune.com/queries/2378578
OP: https://dune.com/queries/2378576

What has changed from the previous queries:
- Updated the queries to include the avg/median for both failed & successful fill transaction cost
- Included these values in the final `transfer_cost` calculation
- Extended the output columns to show all the newly added values
- Slight refactor of the name abbreviations as they proved to be confusing (fpw, fpc, fpf etc.)

Would like to get these forked queries reviewed first by the Dune Wizard @compojoom before overwriting the code in the original queries.

**Comment by fredo** [comment]
@compojoom please close this issue if done

**Comment by compojoom** [comment]
I think it's ok. Padawan @GabrielBuragev has outgrown his master. 😛
