### ISSUE TITLE
Improve code reuse

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1745]
In order to be able to share more code among different software components, including various scripts that import the `beamer` package we should move common, useful functionality and modules from the `beamer.agent` subpackage to the toplevel `beamer` package i.e. one level up.

 Tasks:
- [x] make the `account` argument from `beamer.agent.util.make_web3` optional and use the same function in `health`, removing the duplicate there
- [x] move most of `beamer.agent.util` to `beamer.util`; the token checker related things should stay in `beamer.agent.util`
- [x] move  `beamer.agent.middleware` to `beamer.middleware`
- [x] move  `beamer.agent.typing` to `beamer.typing`
- [x] move  `beamer.agent.events` to `beamer.events`
- [x] move  `beamer.agent.contracts` to `beamer.contracts`
- [x] move `beamer/agent/data/abi/StandardToken.json` to `beamer/data/abi/StandardToken.json`
- [x] rename `beamer.agent.l1_resolution` to a more-appropriate `beamer.agent.relayer`
- [x] move `TokenDetails`, `get_token_details`, `get_token_balance`, `get_token_amount_in_decimals`  from `beamer.health.util` to `beamer.util`
- [x] remove `beamer.health.util` (should not be necessary now)
- [x] turn `load_ERC20_abi` into a private function, which is called only once to initialize a singleton `_ERC20_ABI` object, introduce a new function `get_ERC20_abi` that returns the singleton and convert all existing callers of `load_ERC20_abi` to use the new getter; this will avoid repeatedly deserializing the ABI data
- [x] fix the fallout in tests and CI

**Comment by istankovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1745?planning-poker) with Zenhub @fredo @bilbeyt @compojoom @GabrielBuragev @manuelwedler

**Comment by fredo** [comment]
great summary!
