### ISSUE TITLE
Agent passive mode / safe shutdown

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1757]
Recent events have shown that the agent needs to be able to run in a safe mode where it maintains the current position but does not engage in new positions. 
The main reason for it is, that the agent is required to have a certain amount of ETH to function properly. But currently the agent is designed to only spend ETH, eventually depleting its ETH funds.

With each filled request, the agent requires to have a certain amount of ETH to settle the transfer correctly (claim stake, tx costs). Imagine a case where the funds are depleted on the source side. The agent would continue to fill on the target side (entering into new risk positions) but being unable to claim.
Economically speaking, there can be a threshold set, at which the agent is not safe to fill a request.
Once we have such a feature, we could build the following things on top:

* Run agent in passive mode, to not fill but handle all claims until withdraw (necessary when an agent wants to exit)
* Shutdown agent safely (at least claim, unclaimed fills while not filling new requests before shutdown) (Note this doesn't help for challenges, but less risky compared to now)
* Only fill if enough ETH
* Only challenge if enough ETH

Currently, LPs have to deal with managing ETH balances on all chains and making sure that there is always enough on all chains. Recent example what happened on mainnet: Agent staked all his remaining ETH in challenge on (source chain), continued to fill requests on other chains, but wasn't able to claim them due to insufficient funds on source chain. Note, that this happened in a matter of minutes, hard to deal with as a human.

**Comment by andfletcher** [comment]
The issue should be split into two issues:
- passive mode
- shutdown mode (default shutdown should be safe)

**Comment by andfletcher** [comment]
Docker-compose down should result in the agent shutting down but still staying up long enough to claim all outstanding fills. 

Alternatively do a shutdown and start in passive mode

**Comment by fredo** [comment]
closing in favor of #2012 and #2013
