### ISSUE TITLE
e2e tests wait until message is finalized

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1805]
We currently have flaky tests because we don't wait until a message is finalized before calling the relayer. On local tests finality period is near 0. That's why we have this race condition. 

Three options to solve this problem

1) If relayer crashes, retry
2) wait a fixed amount of time
3) wait until message is finalized and ready for execution.

I think 3) is the cleanest solution and we could even think about implementing this into the relayer. If not, as the status quo, we need to externally make sure that the relayer only runs after finalization.
Otherwise we could also implement the check into the e2e test shell script.

**Comment by istankovic** [comment]
Shouldn't this be actually handled by the relayer itself?

**Comment by fredo** [comment]
> we could even think about implementing this into the relayer

As I wrote here, yes. We can replace `could` with `should` ;)

**Comment by GabrielBuragev** [comment]
I also think we should hand over this responsibility to the relayer. For most of the cases we will have a proper way to check if message is finalized and ready for relaying by using events/contract state. 

But i think this introduces another variable/requirement when integrating new chains (please correct me if i am wrong). If there is no way to properly detect if a message has been finalized (even though thats highly unlikely) what do we do? We could make the relayer crash/return an error like now but then we end up with a non-consistent behavior.

Before we decide to handle this on the relayer side, we need to think about the following things:
- What would be the waiting strategy?  Examples: retry every X seconds until the relayer succeeds, sleep until the message is ready based on the configured finality periods in our contracts ..
- Is the agent software/e2e test negatively affected by this? Are there any timeouts set when calling the relayer as a subprocess from the main processes?
- What to do when there is no way to check for message finality based on events/contract state?

**Comment by istankovic** [comment]
The way I look at it:

- the agent is primarily concerned with the Beamer protocol and needs to send appropriate transactions for the protocol to work; this also includes taking care about timings of events in the system
- the agent shouldn't really know about the details of cross-chain messaging; I see those details as a bit of outside of agent's scope
- the relayer is our component primarily concerned with messaging i.e. to ensure correct message arrival "on the side"

Put another way, I see the agent concerned with _L1 resolution_, and the relayer concerned with _cross-chain messaging_.

**Comment by fredo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1805?planning-poker) with Zenhub @bilbeyt @compojoom @istankovic @manuelwedler @panpilkarz @GabrielBuragev
