### ISSUE TITLE
Pylint not properly configured

### ISSUE THREAD

**Issue by panpilkarz** [beamer-bridge/beamer#1812]
While working on https://github.com/beamer-bridge/beamer/issues/1339 it was noticed, that `pylint` is not reporting obvious coding issues, and the root cause is `disable=all` directive in [pylintrc](https://github.com/beamer-bridge/beamer/blob/main/pylintrc#L29):

```
[MESSAGES CONTROL]

disable=all
enable=
    assert-message,
    bad-except-order,
    del-method-used,
(...)
```

I guess the idea here was to disable all rules and enable some, but it is apparently not working as expected.

After the `disable=all` directive was removed, `pylint` outputs 822 lines.

```
$ pylint beamer/ scripts/ 2>/dev/null  | wc -l
     855
```

## Solution

While `pylint` has ~400 rules I think the better approach is to disable some annoying rules instead of enabling some rules.

The work to be done:

- [ ] remove `disable=all`
- [ ] remove `enable=`
- [ ] add the list of disabled rules
- [ ] review the output of pylint and adapt codebase if needed 

 

___

I recommend to rename `pylintrc` into `.pylintrc` in the repo. The effect for `pylint` execution is the same, while having `.pylintrc` consistent with `.flake8` and hidden from `ls`.

**Comment by istankovic** [comment]
Thanks for writing this!

> I recommend to rename pylintrc into .pylintrc in the repo. The effect for pylint execution is the same, while having .pylintrc consistent with .flake8 and hidden from ls.

Totally! :+1:

**Comment by fredo** [comment]
@panpilkarz canthis issue be closed?
