### ISSUE TITLE
generate-abi.py script is broken

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1814]
Since we changed the artifacts structure the generate-abi file has difficulties processing the artifacts and generating the abis.

#### Expected behavior
To get ABIs

#### Actual behavior
No ABIs :(

**Comment by istankovic** [comment]
We should fix the script and also make it use proper artifact infra.

**Comment by istankovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1814?planning-poker) with Zenhub @bilbeyt @fredo @GabrielBuragev @manuelwedler @panpilkarz @compojoom
