### ISSUE TITLE
Add beamer config command to docs

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1833]
We need to add documentation on how to use the `beamer config` command. 

The command exists of three subcommands: 

* read
* write
* modify

We need to explain the usage of all of these and what inputs they demand + what outputs they generate.

Additionally: 

It needs to be explained the structure of the input files: 

* update file with its minimal DSL
* State representation file 

Also we need to describe the purpose of the checksum and how we validate a correct state file before executing state changes on chain.

**Comment by istankovic** [comment]
Done.
