### ISSUE TITLE
Release first version of npm package

### ISSUE THREAD

**Issue by compojoom** [beamer-bridge/beamer#1838]
With our latest changes to the npm deployment package: https://github.com/beamer-bridge/beamer/pull/1816 we are in a state that we can release our first "stable" version to npm. 

We had a meeting and agreed that we basically will follow this strategy:
- whenever something in the artifacts folder change - we automatically release a dev release. The dev release version number is a prerelease and also contains the commit prepended)
- we only release a new "stable" release whenever we change the package.json file and we update the version number there (once the PR is merged in main). 

The version number for "stable" releases would be always a major version - this way it is clear that any new release can contain breaking changes. 

- [x] we need to put the commit ID into a file in the dist. This way we can figure out which commit generated a release.

**Comment by andfletcher** [comment]
@compojoom docs still need to be added
