### ISSUE TITLE
Add 0xa48B6821024ff16884763A21CE149d3412a933E2 to dune dahsboards

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1848]
##Description 
`0xa48B6821024ff16884763A21CE149d3412a933E2` is a new agent that was whitlisted but not included in the dune dashboards we have. We should add it.

**Comment by compojoom** [comment]
Ok, done

**Comment by andfletcher** [comment]
By using chatgpt https://knowledge.brainbot.com/docs/Development/ai/chatgpt/chatgpt_for_the_boring_stuff
