### ISSUE TITLE
Deploy on Polygon ZKEVM mainnet

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1864]
After finishing up all the contracts/infrastructure for supporting polygon zkevm we need to deploy on mainnet. 

**This issue only covers the deployment on Polygon ZKEVM NOT the other rollups.** 

# Acceptance Criteria
- [x] Contracts are deployed on mainnet - only what is needed to be deployed on Polygon ZKEVM 
- [x] Contracts are correctly configured
- [x] Contracts are verified

**Comment by andfletcher** [comment]
Add configuration to this issue.
