### ISSUE TITLE
Flaky PolygonZKEvm E2E test 

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1893]
Since we integrated PolygonZKEvm in our local e2e tests we saw inconsistent behavior in the local environment, presumably due to a bug in their zkevm-node service.

The initial assumption is that the problem comes from the improper assignment of nonces to txs when they are being submitted/executed via their node.
The state synchronization between L1 <-> L2 stops working once the nonces get mixed up and the following errors are being logged in the `zkevm-node` service:
```
2023-05-30T11:09:14.197Z    ERROR    ethtxmanager/ethtxmanager.go:392    failed to send tx 0x01ecc3739866c23073c4b8f8143d6d85abf174e4e4dc883f0a48b2365b743f85 to network: replacement transaction underpriced    {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-3-to-3"}
github.com/0xPolygonHermez/zkevm-node/ethtxmanager.(*Client).monitorTxs
    /src/ethtxmanager/ethtxmanager.go:392
github.com/0xPolygonHermez/zkevm-node/ethtxmanager.(*Client).Start
    /src/ethtxmanager/ethtxmanager.go:214

2023-05-30T11:09:15.202Z    ERROR    ethtxmanager/ethtxmanager.go:392    failed to send tx 0x01ecc3739866c23073c4b8f8143d6d85abf174e4e4dc883f0a48b2365b743f85 to network: nonce too low    {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-3-to-3"}
github.com/0xPolygonHermez/zkevm-node/ethtxmanager.(*Client).monitorTxs
    /src/ethtxmanager/ethtxmanager.go:392
github.com/0xPolygonHermez/zkevm-node/ethtxmanager.(*Client).Start
    /src/ethtxmanager/ethtxmanager.go:214

2023-05-30T11:09:16.209Z    ERROR    ethtxmanager/ethtxmanager.go:392    failed to send tx 0x01ecc3739866c23073c4b8f8143d6d85abf174e4e4dc883f0a48b2365b743f85 to network: nonce too low    {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-3-to-3"}
github.com/0xPolygonHermez/zkevm-node/ethtxmanager.(*Client).monitorTxs
    /src/ethtxmanager/ethtxmanager.go:392
github.com/0xPolygonHermez/zkevm-node/ethtxmanager.(*Client).Start
    /src/ethtxmanager/ethtxmanager.go:214
```

The log traces lead to this line: https://github.com/0xPolygonHermez/zkevm-node/blob/develop/ethtxmanager/ethtxmanager.go#L392

By looking at the function and its purpose, i assume they are doing some sort of checks (in intervals) against the submitted txs and their properties (such as nonces, from/to addresses etc.). Based on that, they edit these properties to prevent certain events from happening (like duplication of txs if the same nonce was submitted multiple times by the sender?).
A tx review process looks like this: https://github.com/0xPolygonHermez/zkevm-node/blob/develop/ethtxmanager/ethtxmanager.go#L537-L559
This tells us that they are overwriting the nonces for some of the tx's as they see fit.

After communicating this bug with the Polygon team, i got the following response:

> Hi Gabriel, In case you have pending transactions please try sending another transaction with a custom nonce equal to the last successful transaction's nonce + 1. (If the last successful transaction from the sender's side had a nonce of 42, the new nonce has to be set to 43). Use this script here and let us know if the transaction succeeds: https://github.com/nonceblox/polygon-edge-tutorials/blob/master/clear_pending_txns.md

I personally think there was a missunderstanding from their side on what we are trying to achieve (or they just wanted to get rid of my ticket) and therefore i consider the answer to be irrelevant.

# Acceptance Criteria
- [ ] Research the internals of the ethtxmanager and why this error is being hit
- [ ] Post an issue on their repository with the findings (failed CI runs, docker logs etc.)
- [ ] Figure out the next steps?

Timeboxed issue, try to figure out whats happening, report, communicate but dont spend too much time.

**Comment by GabrielBuragev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1893?planning-poker) with Zenhub @bilbeyt @compojoom @fredo @istankovic @manuelwedler

**Comment by fredo** [comment]
We need to create an issue in https://github.com/0xPolygonHermez/zkevm-node
