### ISSUE TITLE
Research failing relay execution due to wrong gas estimation

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1924]
2 main problems were discovered when testing the new OP Bedrock setup with the relayer.

1. local e2e test was failing due to a wrong gas estimation. First solution was to set a fixed gas limit of 2_000_000.
We put the same case on the test on Goerli and we managed to reproduce it. At this moment, we considered this serious and went deeper to figure out why a fixed gas limit solves the issue and why the default gas estimation algorithm doesn't work as intended.
The analysis found that the way optimism executes relaying messages confuses the gas estimation process. To be able to calculate the proper estimated min gas limit, one had to trigger an estimation call where the "from" address is set to "0x00...001". This is a little "hack" provided by OP so we are able to calculate right gas limits.
This documentation is only visible in the CDM contract: https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/universal/CrossDomainMessenger.sol#L381-L388 and therefore it took us quite some time to figure this out.

2. https://github.com/beamer-bridge/beamer/issues/1925 
With OP Bedrock, the relay process changed in such a way that the contract that is responsible for relaying messages changed. It is the OptimismPortal's responsibility to take care of this now. 
During the research we found out that a failed message relay (via the OptimismPortal) cannot be replayed via the same contract. Luckily, the CrossDomainMessenger (CDM) is still there and its responsibility haven't changed. 
For such cases, the relayer needs to replay the message relay via the CDM directly.

~ time spent 2 devs for 2 days

**Comment by GabrielBuragev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1924?planning-poker) with Zenhub @bilbeyt @compojoom @fredo @istankovic @manuelwedler
