### ISSUE TITLE
Flaky Arbitrum e2e tests

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1934]
The local Arbitrum E2E tests are sometimes hanging and hitting the timeout limits both on the CI and locally.

The ARB E2E test works in the following way:
- Create a Request on local ARB chain
- Create a Fill for the Request on the same local ARB chain
- Run the relayer with the Fill tx hash and try to relay from ARB back to ARB via L1 (local geth)

From my limited research, my first assumption is that the L2 blocks/batches are not being properly propagated to L1 in some cases.
This is an obvious observation when looking at the logs of the relayer when this failure happens:
```
Performing test fill on L2...
Request ID: 0xdd672a829cacaef6700092b7bbe3eaf9fabc87584fbb02ab302f144f1a747573
Fill tx hash: 0x309937eb5bc14ae86d31137c362be40ff9f4009d5f8614dc37b03118deffd579
Starting relayer...
Preparing Arbitrum Messenger for forwarding the L1 message...
Successfully deposited funds on ArbitrumL1Messenger: 0xc30f7d7215aebdb9eb7d1f626a0dd787473d3f416d8257c32a36a42960748de5
Arbitrum outbox execution
Waiting for outbox entry to show up... <---- Gets stuck here

```
`Waiting for outbox entry to show up` means that the relayer is waiting for the L2 state to show up on L1.

A way to reproduce this:
- Start up the dockerized ARB environment `docker/arbitrum/arbitrum.sh up`
- Deploy beamer `docker/arbitrum/arbitrum.sh deploy-beamer`
- Run E2E tests `docker/arbitrum/arbitrum.sh e2e-test` until you see one hang with similar logs and at the same step as above
 
### Solution?
After reproducing this scenario, my first attempt to solving this was by submitting one more Request & Fill transaction (by calling another e2e-test). 
This triggered a batch post by one of the docker services which included the transactions from the hanging e2e-test, state arrived on L1 and un-blocked the test (relayer picked up the message status changes).
But, please research enough to understand the problem better and construct a proper solution (if possible)

## Acceptance Criteria
- [ ] Arbitrum E2E test is no more flaky 

Timebox research issue. Spending more time is also acceptable.

**Comment by GabrielBuragev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1934?planning-poker) with Zenhub @bilbeyt @compojoom @fredo @istankovic @manuelwedler

**Comment by compojoom** [comment]
I created a ticket in the arbitrum repo for this as it seems to be a problem in the local node setup:
https://github.com/OffchainLabs/nitro/issues/1706

**Comment by compojoom** [comment]
It was a bug in the arbiturm node - fixed by upgrading to the latest arbitrum release.
