### ISSUE TITLE
frontend: Cookie consent popup decision is not stored when accepted in Safe App

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#1935]
> Good morning! QA from safe apps team here 😄
>
> I see that the privacy policy pop up will only disappear when it is declined, might be worth a 👀 : 
> 
> https://github.com/5afe/safe-apps-list/assets/92332710/843e7ba8-4838-41ba-bf5b-bbc16b8d0568
> 
> Cheers!

_Originally posted by @JagoFigueroa in https://github.com/5afe/safe-apps-list/issues/253#issuecomment-1587066567_

**Comment by GabrielBuragev** [comment]
Just tested this on https://app.safe.global and it doesn't seem as it was fixed. Re-opening therefore

**Comment by manuelwedler** [comment]
What browser were you using? I just tested it on Firefox and it worked.

**Comment by GabrielBuragev** [comment]
I tried it out on both Chrome & Firefox. Pressing "Accept" doesn't result in the app remembering my decision.
If i press "Decline" however, it remembers the decision and stops asking on page reload.

**Comment by GabrielBuragev** [comment]
Nevermind. I tested again with cleared browser cache and now everything works fine!
