### ISSUE TITLE
Agent needs to check that he has enough balance to claim a fill

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1947]
The agent does not check before filling if he has enough funds on the target side to claim (I neglect the fact of challenging on purpose, since claiming is much more time critical then challenging).

solution:
Check whether there are enough funds on source side to be able to claim. We could introduce another threshold value when an agent would stop providing the service (currently this threshold is 0, implicitly). For the case of L1, this threshold and the L1 resolution threshold would simply add up.

**Comment by andfletcher** [comment]
Default is non "0"
