### ISSUE TITLE
redeploy goerli frontend 

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1956]
## Description
Redeploy frontend that is on Goerli

## Acceptance criteria

- [x] include polygon zkevm
- [x] run on the most recent branch
- [x] needs to point to correct contracts

**Comment by GabrielBuragev** [comment]
This was resolved as of https://github.com/beamer-bridge/beamer/pull/1981 
The testnet frontend version is now deployed using the `main` branch.
