### ISSUE TITLE
Get listed on L2beat

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1964]
## Description
We want beamers security features to be listed on the L2beat website. Even though they use TVL as a metric that does not work with what we have this is not prior since we want to be able to showcase our security model vs the other bridges. 

## Todo
I talked to some of the L2beat team in EthPrague and they said it would help If we create a PR. Since @compojoom is working with them on a different topic please check how we can get this done.

**Comment by compojoom** [comment]
I've created a PR: https://github.com/l2beat/l2beat/pull/1613

But it might need more work.

**Comment by compojoom** [comment]
done https://l2beat-staging-l2beat.vercel.app/bridges/projects/beamerbridgev2
