### ISSUE TITLE
Implement contract for fee subsidy

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#2020]
## FeeSub.sol
* The owner needs to be able to enable/disable token addresses to be subsidized
* The owner needs to be able to change the minimum amount
* The contract needs to be able to approve the RM to take tokens from FeeSub
* User must be able to create a request if subsidizable and withdraw an expired request
* The owner must not be able to withdraw funds belonging to the user

## Implementation
* Mapping for address to minimumAmount
  * If 0, then it's not enabled to be subsidized
* setMinimumAmount(tokenAddress, minimumAmount)
  * onlyOwner
  * If set to > 0, approve RM to maximum value
  * If set to 0, remove allowance for RM
* createRequest
  * check if >= minimum amount
  * transferFrom user
  * createRequest
  * store requestId => sender
* withdrawExpiredRequest
  * check if request sender is FeeSub on RM
  * check if request withdrawnClaimId is maxInt (withdrawn by withdrawExpiredRequest)
    * if not withdrawExpiredRequest
  * check if requestId => is address(0)
    * if not set to address(0)
    * send request.amount back to user
* Funder accounting
  * TBD

**Comment by andfletcher** [comment]
let's go the easy way, the owner is not able to withdraw what is in the contract. we can figure out how to get tokens out of the contract later.
