### ISSUE TITLE
Add PolygonZKEVM to the website

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#2051]
## Issue Desription
Replace the boba logo with the Polygon ZKEM logo on the website
## Acceptance Criteria

- [ ] Boba is removed and replaced with Polygon zkEVM logo

![image](https://github.com/beamer-bridge/beamer/assets/39694712/e5e9487e-866e-4cfe-943c-b78afe83a24d)

**Comment by andfletcher** [comment]
I understand that we also have the logo still in the background of the website, we will remove that also later on but not now. 

@GabrielBuragev do you have a logo for this? Olympe mentioned that you had looked into this a few weeks ago.

**Comment by andfletcher** [comment]
@GabrielBuragev also feel free to pull into the sprint

**Comment by GabrielBuragev** [comment]
> @GabrielBuragev do you have a logo for this? Olympe mentioned that you had looked into this a few weeks ago.

Found all the logos i need.
