### ISSUE TITLE
Add documentation / process what and how to test new rollups

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#2121]

**Comment by andfletcher** [comment]
We should check/make sure that we have an apparent document on what tests/challenges/invalidations etc, we need to do and how we need to do them when we add a new rollup. 

We have this document, but we should make sure everyone in the team understands it: https://docs.google.com/spreadsheets/d/1w8CgERbHG5WDgW1ib9IU6_jLzPxmhudMnkriWbAKXUE/edit?pli=1#gid=0

**Comment by andfletcher** [comment]
https://docs.google.com/spreadsheets/d/1GQIJcDtIgIWEfFmpuNdlUWz7z1EGOPNf/edit#gid=1237218617

**Comment by andfletcher** [comment]
#1646 block by this issue

**Comment by fredo** [comment]
Created https://docs.google.com/document/d/1_G6u7N7RKvd2Jl2W3TbF1sXkDTqrqjUFZNQ99EvNHZQ/edit?usp=sharing

and documents in 

https://drive.google.com/drive/folders/1kFOHEH9T9RUEvoMWPnlbbev18XrK--zS
