### ISSUE TITLE
Deployment check list for v3

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#2122]
- [x] Prepare all config files @fredo can you list what all config files are, please
- [x] Deploy base (command, not chain)
- [x] deploy chains (Ethereum, Polygon zkEVM, Base, Arbitrum, Optimism)
- [x] configure all chains (Ethereum, Polygon zkEVM, Base, Arbitrum, Optimism)
- [x] Do L1 resolution tests based on the document created from https://github.com/beamer-bridge/beamer/issues/2121
- [x] Setup and fund an agent
- [x] Whitelist the agent
- [x] Do agent Challenge tests based on the document created from https://github.com/beamer-bridge/beamer/issues/2121
- [x] Push deployment files to main
- [x] Check contract addresses in docs
- [x] Release new npm package
- [x] Create a Release VX.0.0
- [x] Deploy a frontend under hard to guess URL for internal testing
- [ ] Update Subgraphs
- [x] Do internal testing
- [x] Deploy FeeSub contracts
- [x] Update Dune Dashboards / create v3 dashboards
- [x] Update Monitoring scripts (health script and liquidity script)
- [x] Update Run your own repo
- [x] Move agents to the new version
- [x] Deprecate the old version

also see #1626

## Acceptance criteria
needs to include https://github.com/beamer-bridge/team/issues/10

**Comment by andfletcher** [comment]
Done
