### ISSUE TITLE
frontend: disable transfer creation if not enough liquidity available

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#2141]
## Issue Desription

We would like to disable the transfer submit button in case the transfer cannot get filled due to liquidity. We should check the token balance of all agents on the target chain and disable if none of them has enough tokens for fulfillment. For this a new validator function needs to be implemented and integrated into the form.

## Acceptance Criteria
- [ ] check the token balances of the agents for the selected token on the target chain
- [ ] disable transfer button in case no agent has as much tokens as the user's input in the amount field

**Comment by manuelwedler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/2141?planning-poker) with Zenhub @bilbeyt @istankovic @fredo

**Comment by fredo** [comment]
how are the agent addresses retrieved?

**Comment by manuelwedler** [comment]
I thought I could get them from the RequestManager contract but just realized that it is implemented as mapping it is not trivial to get them from the chain.

Daniel proposed to hardcode them. Would you be fine with that? @fredo

**Comment by fredo** [comment]
for the beginning yes

**Comment by manuelwedler** [comment]
Sounds good to me :+1:
