### ISSUE TITLE
Node CLI UX

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#228]
We need to decide how the node CLI UX should look like in the end.

Currently it's quite unfriendly:
```
 --l2a-rpc-url http://127.0.0.1:8545 \
 --l2b-rpc-url http://127.0.0.1:8545 \
 --l2a-contracts-deployment-dir contracts/build/deployments/dev \
 --l2b-contracts-deployment-dir contracts/build/deployments/dev
```

This means, that a node only supports a pair of rollups, and only one-directional transfers. So in order to have bidirectional support one would need to start a second node. Things get even more complex with three rollups, where one would need to start 6 nodes to support bidirectional transfers between all.

Another problem is how to get contract information. Currently the node is supplied with contracts to use. But we should check that the underlying resolver is the same.

## Decisions to make
- Should the node support bidirectional transfers for two rollups?
- Should the node support more than two rollups?
- How to supply contract information?
- How to make sure that the rollup deployments share a common resolver?

**Comment by istankovic** [comment]
This has been obsolete for a long time now, closing.
