### ISSUE TITLE
frontend: tooltip describing fees

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#254]
We need to add a helpful text describing the fees in the request form. At the moment there is only this placeholder text:

![Screenshot from 2022-02-28 14-21-50](https://user-images.githubusercontent.com/34456797/155990514-eedcf9c0-4629-409a-871e-802109cf7eed.png)

**Comment by nekhaly** [comment]
This has been implemented already, now we need a suitable text for this tooltip. @czepluch @LoringHarkness

**Comment by manuelwedler** [comment]
This issue is only for the suitable text.

**Comment by istankovic** [comment]
@nekhaly is this still relevant?

**Comment by nekhaly** [comment]
> @nekhaly is this still relevant?

yes, still.. we need the help text to describe the fees!

**Comment by istankovic** [comment]
Here's my attempt to describe what is going on:
```
The fee amount is composed of three parts:
 - the gas reimbursement fee
 - the liquidity provider fee
 - the Beamer service fee

The gas reimbursement fee and the liquidity provider fee are paid out to
the liquidity provider servicing the request, while the Beamer service fee
stays with the contract and supports the Beamer platform development.

Note that the fee is paid on top of the token amount being transferred,
so that the token amount received on the target rollup is exactly the same as
the token amount sent from the source rollup.
```
@czepluch please review whether this is ok.

**Comment by istankovic** [comment]
> How is the Beamer service fee actually implemented right now? Who gets the fee?

The `RequestManager` contract keeps 4.5% of the gas fee as the Beamer service fee. These fees are collected
when claims are successfully withdrawn. There is an ability for the owner (deployer) of the contract to withdraw collected Beamer service fees by issuing a special call.
