### ISSUE TITLE
frontend: Allow user to retrigger switching the chain

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#255]
For listening on the fulfillment on the target chain, a user needs to switch the chain which is triggered automatically. When a user cancels this at the moment, the flow is stuck. We need to add a button for retriggering the switch as it is in the design:

![Screenshot from 2022-02-28 14-25-12](https://user-images.githubusercontent.com/34456797/155991372-676e9bab-406f-4ab1-b063-ff015d68c1c9.png)

**Comment by nekhaly** [comment]
No need for this anymore. Canceled via #419
