### ISSUE TITLE
frontend: Prefill fields in request form

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#258]
Some of the fields in the request form can be prefilled when the page is opened in order to improve usability. The source chain can be set to the currently connected chain. The target address can be set to the address of the current account. 

See also: https://github.com/beamer-bridge/beamer/issues/365

**Comment by weilbith** [comment]
The first part is already done. Second is still relevant and part of UX discussions.

**Comment by manuelwedler** [comment]
Closing in favor of https://github.com/beamer-bridge/beamer/issues/878
