### ISSUE TITLE
frontend: Provide input validation

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#259]
At the moment the user input is not validated. For example it is possible to input any string as the target address. Ether js will throw an error in such cases when the user clicks the send request button. It should only be allowed to set checksum addresses in the field. An appropriate error message should be shown to the user if an invalid value is given. Also the submit button should be disabled until the whole form is valid.

Validate:

- Target address should be checksum
- Amount should be a valid number
- Amount should match token decimals
- Amount should be > 0
- Value + the fees should be <= the balance the user has 

Design needed

**Comment by czepluch** [comment]
@manuelwedler Potentially relevant for this issue too: https://docs.ens.domains/dapp-developer-guide/ens-l2-offchain

**Comment by manuelwedler** [comment]
I would rather keep the PR small and create another afterwards for properly supporting ENS. This should also involve some testing effort, which is not related to the validation. We never supposed it to be supported, so let's use the #914 issue to track implementing this as a new feature.

**Comment by czepluch** [comment]
Yup!
