### ISSUE TITLE
frontend: Show token balance in request form

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#262]
The request form should show the token balance close to the amount field to help the user. Also, a button for setting the maximum amount in the field would be nice.

**Comment by istankovic** [comment]
@manuelwedler @talel @czepluch what is the plan regarding this issue?
As far as I can see, it is the only remaining open issue inside this epic: https://github.com/beamer-bridge/beamer/issues/293

**Comment by czepluch** [comment]
I don't see this as a blocker for announcing the frontend. It's nice to have and something we can add next week.

**Comment by manuelwedler** [comment]
I already started working on this. I can finish it today if there is nothing more important anymore.

**Comment by czepluch** [comment]
Great :)
