### ISSUE TITLE
Allow the node to submit L1 transaction

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#271]
After there are enough funds to go to L1, the node should submit an L1 transaction to resolve the challenge game.

See #185.

When to go to L1:
As soon as there are enough funds.

Mechanics for going to L1:
- [ ] Should trigger when the other party raised us
  - [ ] Should we still counter-challenge to increase the stakes?
- [ ] Have a new state, so not to send multiple transactions.
- [ ] Check if transaction arrived.
- [x] Filter for event from resolution registry.
- [x] Store fill tx hash

**Comment by palango** [comment]
The interface to #185 will be an executable that takes the following parameters:
-    L2 RPC
 -   L1 RPC
  -  L1 wallet
   - Hash of the L2 transaction that includes the message(s) to forward


We still need to decide what should be returned
