### ISSUE TITLE
frontend: Improvements on the design implementation

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#283]
Olympe reviewed the implementation of the design and found a couple of minor things to improve:

- [ ] Inner shadows of the dropdowns should be removed when they are opened
- [ ]  The disabled new transfer button should be shown while the progress is shown in the stepper
- [ ] Process steps should be smaller like in the design. Also the font size does not match. (#257) 
- [ ] The info window in the process view should be adapted. Make it less high and increase the vertical padding.
- [ ] Font proportions should be checked with the design
- [ ] More padding on the right of the arrow in the dropdowns. Arrow should be centered on the right of the rounded end.

**Comment by weilbith** [comment]
All these have become resolved with the latest changes or have become irrelevant with the new design which will become implemented. Thereby this issue is no more necessary.
