### ISSUE TITLE
frontend: Fetch token meta data

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#291]
At the moment the token symbol is hardcoded in the config file. It could be easily fetched on-chain. Also the decimal places and the balance will be useful to fetch. Besides, we should get an icon for the tokens somewhere. The dropdown already supports displaying images.
This requires a batch request mechanism for getting the info for all configured tokens simultaneously.

**Comment by weilbith** [comment]
This issue has become irrelevant. In fact we have decided against this.
Putting the data into the configuration file is incredibly easy in contrast to handle all the asynchronous problems of querying it over and over again from the blockchains. Furthermore we decided to put all relevant information into transfer instances so even in case of removing a token/chain from the configuration, we still have all information available.
