### ISSUE TITLE
Beamer Bridge Minimal Website

### ISSUE THREAD

**Issue by DinaBB** [beamer-bridge/beamer#319]
## Description

When announcing Beamer we want to also have a website for the project.

## Acceptance Criteria

Minimal static website.

**Comment by weilbith** [comment]
Sorry, that we did not push any status updates. A repository beamer-bridge/www.beamerbridge.com has been created. The domain is registered and working (currently only shows `under construction`). The content of the website has been finished and the responsiveness has been heavily optimized. It will need a final look by @olympe-silve but I'm optimistic we are good to go.
