### ISSUE TITLE
Cover the case of `decimals` is not available

### ISSUE THREAD

**Issue by nekhaly** [beamer-bridge/beamer#352]
What happens if `decimals` is not available? ERC20 doesn't require it.

_Originally posted by @palango in https://github.com/beamer-bridge/beamer/pull/351#discussion_r827281039_

**Comment by nekhaly** [comment]
Not yet.. Will resolve when we decide from where should we load tokens configuration.

**Comment by weilbith** [comment]
This is no more the case as decimals are statically configured and do not require the blockchain anymore. This was part of some architecture refactorings.
