### ISSUE TITLE
agent: enable unlimited allowance for FillManager

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#355]
following #353, we can introduce the same change to the agent, saving on transaction per fill by approving an unlimited amount to the fill manager contract.

**Comment by istankovic** [comment]
@fredo this one should be trivial, right?
Check if the token allowance for the agent's address is UINT256_MAX and, if not, approve the max amount.

**Comment by istankovic** [comment]
@fredo ping... :-)

**Comment by czepluch** [comment]
I'd say we should make sure that this is optional. If agents wants to enable it and do it, then fine, but it's a bit of bad practice, so maybe giving the agent / users the choice is the best practice.

**Comment by fredo** [comment]
please note, that every transfer deducts the amount from the contract's allowance. If we make this value configurable with any real number (which IMO is desirable), we need to check the current allowance before any call. 

It then gets a bit tricky. We must decide how the agent reacts when the allowance decreases towards 0. When should the agent re-update the allowance and call `approve()`? It involves a strategy which is not quite trivial. But as always we should go ahead with an easy approach and optimize later.

One suggestion would be: 
Upon every fill check whether current allowance is sufficient (RPC call). If not, call approve to update allowance. I think this is a suboptimal solution but good for now. Note, that the agent will most likely lose the race for that particular fill against someone where allowance is high enough.

**Comment by fredo** [comment]
Additionally, please note that agents which have an unlimited allowance have an advantage over other agents which do not, because such agents don't need the RPC call to check the allowance before the fill transaction. 
This might give them a couple of hundred milliseconds advantage and are more likely to win the "fill race". 
If it becomes financially unviable to run an agent with limits set, must yet to be seen.

**Comment by istankovic** [comment]
> Upon every fill check whether current allowance is sufficient (RPC call). If not, call approve to update allowance. I think this is a suboptimal solution but good for now. Note, that the agent will most likely lose the race for that particular fill against someone where allowance is high enough.

I do not perceive that as a problem, because it arises from the very same thing that would be the solution in this case: configurable allowance.

The extra call is not nice in general, however, it is good enough for now.

**Comment by fredo** [comment]
Not saying that this is a problem. But it needs to be handled by the agent correctly. And again, tehre are various ways to handle it.

**Comment by fredo** [comment]
Picking this up again, as we see now inefficiency in the agents' performances on mainnet.

Currently, agents see a request and most of them start approving. While only one agent will be able to fill, the allowance remains.  Additionally, the agent who fills has one more transaction in total per transfer.

By allowing to approve a bigger amount, the successful agent will have one transaction less. Additionally, all other agents will try to fill directly. The interesting part here is, that if the agent's RPC has the fill of another agent in its state upon filling, the transaction will not be send at all. It will already fail on estimating gas.
This does not happen for approves as they will never fail. This means that we have an upper bound of n-1 failing transactions (where n is the number of agents) but it could and probably will be less on average.

## Implementation
In the past we discussed that the agent should be able to configure the allowed value (MAX_INT could be configured as -1).
Additionally, I realized that the agent can keep track of the allowance in memory without doing an RPC.

* Upon start up check the current allowance for FillManager
* Never do allowance until a specific fill would fail because insufficient allowance
* Call approve for the configured value
* For every successful fill, deduct the filled amount from internal allowance
