### ISSUE TITLE
Make "connected chain not supported" more explicit

### ISSUE THREAD

**Issue by czepluch** [beamer-bridge/beamer#360]
## Problem 
When a user goes to the front-end and is connected to a network that is not supported, there is no information about what to do and which networks are supported.

## Solution
There should be a small explanation on how what networks that are supported and how to add them to metamask if the user doesn't already have them in metamask.

## Acceptance criteria
It is clear to the user what network they should change to in order to use use the front-end

**Comment by nekhaly** [comment]
closed via #349
