### ISSUE TITLE
Add a global error handling module

### ISSUE THREAD

**Issue by nekhaly** [beamer-bridge/beamer#393]
For the sake of consistency over the whole app, there's a need to have a global error handling module so it works with all types of errors that happen inside including those related to Metamask or from the app itself. When it's there, we can depend on `try-catch` and `throw Error` which are more rigid and cleaner and allow us to have user-friendly errors. 

 _Originally posted by @manuelwedler in https://github.com/beamer-bridge/beamer/pull/388#discussion_r829278626_

**Comment by weilbith** [comment]
Idk. The linked one is more detailed. 🤷🏾 
But I would say this is a super epic and need to be split anyway. Though I dunno how in particular. We kinda hit certain language restrictions here.

**Comment by taleldayekh** [comment]
@manuelwedler can you sit down with @GabrielBuragev and see if this issue still makes sense?

**Comment by manuelwedler** [comment]
Closing in favor of #507
