### ISSUE TITLE
Prepare README for the announcement

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#411]
As mentinoned in https://github.com/beamer-bridge/product/issues/39#issuecomment-1072549017, make sure that the README content is up to date and move most of the things to our docs.

**Comment by czepluch** [comment]
Is this done @istankovic ?

**Comment by istankovic** [comment]
> Is this done @istankovic ?

Unfortunately, this issue is not named completely correctly -- the README has been updated, but a subset of the content that was moved to docs is not yet completely updated. That's why I'm leaving this still open. It should be done soon (tm).
