### ISSUE TITLE
Docs: Add a section about timing constraints in the whitepaper

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#427]
From the discussions between @cducrest and me, we derived timing constraints for a bungs of variables which we should gather somewhere.

i.e. see #346

**Comment by cducrest** [comment]
I think most of the timing constraints we have discussed back then have been eliminated with our changes to the non-fill proof and multi-party bidding.
The few timing assumptions we have are made explicit in `protocol.rst` (challengePeriod, claimPeriod, challengePeriodExtension) and in the whitepaper line 377:

> To make sure the proof arrives in time on rollup A, Bob will need to call the ``fill manager`` as soon as he notices a
false claim for a non-filled request. It takes ``finalization time of rollup B`` after Bob's call to be able to send the
proof to the resolution registry, while the challenge period is defined to be
``finalization time of rollup B + challenge period extension``.

Do you still think we need to a new section @fredo ?

**Comment by istankovic** [comment]
@fredo ping....

**Comment by fredo** [comment]
I just read through the documentation again and I think what we have right now is good enough.
