### ISSUE TITLE
Frontend not working in Safari

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#456]
#### System information

OS & Version: OSX
Browser & Version: Safari

#### Expected behavior

Show the formular

#### Actual behavior
<img width="1680" alt="Screen Shot 2022-03-28 at 14 03 13" src="https://user-images.githubusercontent.com/90851/160394000-1d400321-5cc7-41b5-b220-72e73bd345bd.png">

**Comment by czepluch** [comment]
This is because Safari doesn't have a metamask extension, right? We should definitely add support for WalletConnect.

**Comment by palango** [comment]
@nekhaly In case no metamask is found the form isn't displayed?

If so, then feel free to close this issue.

**Comment by nekhaly** [comment]
The form is displayed only if Metamask is available on the browser, whatever the network or the account you are connected to, or even not connected at all. If Metamask is not available, form hiding is the safest and easiest solution to avoid many issues handling. Yes, it's true that in the future we are going to support more wallets, but for MVP, only Metamask is available.  
I think the issue opened for supporting WalletConnect #472 would be enough and we can close this one
