### ISSUE TITLE
Set up a Prometheus endpoint

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#468]
We should do the following:
- set up a Prometheus endpoint within the agent so that the agent can be polled
- add some minimal stats to the data returned by the endpoint:
  - the agent's source and target rollups
  - the agent's uptime
  - the total number of requests filled on the target rollup (regardless of the filler)
  - the number of requests the agent filled on the target rollup during agent's uptime
  - the total number of requests created on the source rollup
- configure the alert mechanism on `metrics.brainbot.com` so that if an agent goes down, the team is notified by e-mail

**Comment by taleldayekh** [comment]
Still missing the `metrics.brainbot.com` configuration.

**Comment by istankovic** [comment]
We now have a dashboard with basic agent status, as well as alerts.
