### ISSUE TITLE
Issue with logo and screen responsiveness

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#469]
Currently on big screen the logo splits from the form, which looks weird.

![Screen Shot 2022-03-29 at 14 38 40](https://user-images.githubusercontent.com/90851/160612980-a25fa3ca-eebf-4b98-903a-0ae01150149d.png)

**Comment by taleldayekh** [comment]
@olympe-silve Can you give your opinion on this. How do you want the logo in relation to the form?

**Comment by weilbith** [comment]
Will become irrelevant with the new header design that is in the making.
@olympe-silve please decide if this issue is still relevant or should be closed.

**Comment by taleldayekh** [comment]
Has been fixed, @olympe-silve if you are not happy with how it currently looks create a new issue.

**Comment by GabrielBuragev** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/18466333/184646392-97be915b-787e-4aeb-84cc-7a942f2ae659.png">

We are going to reuse this issue to fix another issue related to the logo when displayed on small screens.

**Comment by taleldayekh** [comment]
@GabrielBuragev to sync with Olympe.

**Comment by GabrielBuragev** [comment]
This issue will be fixed with #935 since its a part of a bigger issue related to the mobile device layout.
