### ISSUE TITLE
After bridge not received token

### ISSUE THREAD

**Issue by Kuat009** [beamer-bridge/beamer#470]
#### System information

OS & Version: Windows
Browser & Version: Chrome
Commit hash: 0x3200957ccad76d008351f647acd820550412306067b25bce726c44901b1f6173

**Comment by palango** [comment]
Hi @Kuat009. Thanks for reporting this issue.

Just to clarify: Did the tokens appear on the target chain after the long processing time? If so, this will be likely fixed with https://github.com/beamer-bridge/beamer/issues/356

**Comment by palango** [comment]
This will  be fixed in #356
