### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by Killmeaziz** [beamer-bridge/beamer#471]
#### System information
Time processing take too much time

OS & Version: Windows/Linux/OSX
Browser & Version: Chrome/Firefox
Commit hash: when using checkout

**Comment by palango** [comment]
Hi @Killmeaziz . Thanks for reporting this issue.

Just to clarify: Did the tokens appear on the target chain after the long processing time? If so, this will be likely fixed with https://github.com/beamer-bridge/beamer/issues/356

**Comment by palango** [comment]
Thanks, we will track this in #356
