### ISSUE TITLE
bug from faucet

### ISSUE THREAD

**Issue by himunali** [beamer-bridge/beamer#478]
#### System information

OS & Version: Windows
Browser & Version: Chrome
Commit hash: when using checkout

#### Expected behavior
bug fix for faucet

**Comment by palango** [comment]
@himunali Thanks for reporting this!

Do I understand it right that you didn't receive token from the faucet?

**Comment by palango** [comment]
The faucet ran out of funds. Sorry for the inconvenience. It's fixed now.
