### ISSUE TITLE
I cannt get test tokens for boba rinkeby,0x3DD7DE55F5585084AaE15de5f28e2a9CA78c35c2,thanks!

### ISSUE THREAD

**Issue by chenfly76** [beamer-bridge/beamer#479]
# Rationale

Why should this feature exist?
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by palango** [comment]
The faucet ran out of funds. Sorry for the inconvenience. It's fixed now.
