### ISSUE TITLE
Implement proper state management for frontend

### ISSUE THREAD

**Issue by nekhaly** [beamer-bridge/beamer#497]
# Problem

For app performance's sake, in case of, for example, we would like to retrieve historical events for the user to allow checking old transactions, a cached state for the events will help much in decreasing querying blockchain for those old ones. A proper state management tool would help in that!

#Solution

`Vuex` is the direct suggestion to achieve this, but we may look also for other solutions

**Comment by manuelwedler** [comment]
Just a remark: For vue3, [Pinia](https://pinia.vuejs.org/) is the go-to state management library now. Vuex is in maintenance mode.
