### ISSUE TITLE
frontend: white background around dropdown arrows

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#498]
#### System information

OS & Version: Linux
Browser & Version: Firefox 98.0.1
Commit hash: when using checkout

#### Expected behavior
There should be no white background around dropdown arrows, see image below.

#### Actual behavior
![image](https://user-images.githubusercontent.com/1312091/161247765-190bfa0c-a90a-4544-92e9-0c9a716d2100.png)

#### Steps to reproduce the behavior

Go to testnet.beamerbridge.com and try to initiate a transfer from Metis to Boba.

**Comment by nekhaly** [comment]
Closed via #513
