### ISSUE TITLE
frontend: f is undefined

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#499]
#### System information

OS & Version: Linux
Browser & Version: Firefox 98.0.1
Commit hash: when using checkout

#### Expected behavior
No error.

#### Actual behavior
![image](https://user-images.githubusercontent.com/1312091/161263192-11d62ef9-16ec-41ef-93a2-c44807e18f42.png)

![image](https://user-images.githubusercontent.com/1312091/161263388-dc2f1de3-9ec8-4829-a1a1-81c067d53e1a.png)

#### Steps to reproduce the behavior

Try to send a Metis -> Boba transfer using the testnet frontend.

**Comment by nekhaly** [comment]
Apparently, this is connected to this solution https://github.com/beamer-bridge/beamer/pull/516 , but will check further before closing!
