### ISSUE TITLE
Create UX/UI for WalletConnect

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#500]
## Description of Deliverables(s)

Users should have the possibility to connect to Beamer with other providers than just MetaMask.

## Specifications

- [x] Sync with @nekhaly @manuelwedler @weilbith to get a better understanding of WalletConnect.
- [x] Decide on UX flow.
- [ ] Create design mockups.
- [ ] Hand over design mockups to devs.

For which platform and in what size/aspect ratio?

**Comment by nekhaly** [comment]
While implementing the tech part of this issue, I found that there's a need to have a `disconnect` button. It exactly does the opposite function of the `connect` buttons we will have for `Metamask and `WalletConnect`, but it will be only one button to cover both wallet disconnection!
Here's some examples of how it's implemented in other apps:
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/8708085/165296594-a0155a9d-661a-4ed0-b3a9-e92fcdeb007e.png">

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/8708085/165297030-b8190597-4501-4268-a9af-fec7331e831c.png">
