### ISSUE TITLE
Frontend uses the same token address on both chains

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#503]
:warning:
This one needs to be considered high-severity, since the frontend issues requests that cannot be fulfilled at all, rendering the current demo page unusable. 
:warning: 

We have this in `beamer/frontend/src/components/RequestDialog.vue`:
```
const request: Request = {                            
  targetChainId: Number(formResult.toChainId.value),  
  sourceTokenAddress: formResult.tokenAddress.value,  
  sourceChainId: Number(formResult.fromChainId.value),
  targetTokenAddress: formResult.tokenAddress.value,  
  targetAddress: formResult.toAddress,                
  amount: formResult.amount,                          
};                                                    
```
Note that `sourceTokenAddress` and `targetTokenAddress` are set to the same value.
They should be set according to the configuration that was provided, where the token contract address
depends on the chain.

**Comment by nekhaly** [comment]
Closed via #504
