### ISSUE TITLE
Replace `brownie`

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#535]
Recently `brownie` seems to be unmaintained. https://github.com/eth-brownie/brownie

We need to find out if it will be maintained in the future. If not, we should switch so some supported project, e.g. hardhat.

**Comment by andfletcher** [comment]
@fredo @istankovic @bilbeyt this seems to be a duplicate to #1079, or are we using brownie for anything else? If yes, does it not make sense only to use one of these two options?
