### ISSUE TITLE
Infrastructure, Testing and Deployments

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#537]
I hijacked this epic to start a discussion and collect important improvements which make the devs' lifes easier. We need to find a prioritization of those tasks.

This is all about testing infrastructure, agent deployments, CI, versioning.

### CI
* [Move to CircleCI](#848)

### Test Infrastructure

* Dev Testnet so we are not testing on the users' testnet. Allows for more frequent iterations.

### Deployments
* contracts
  * more flexible deployment script
* frontend
  * Autogenerate Config File
* agents
    * single command deployment for all agents
    * Being able to run "infinite" number of agents on different (or the same) network
    * tearing down old agents

### Agents

* Docker compose for agents
* Multi Chain agent

### Versioning
We need a proper versioning to determine compatibility and from where we can trigger new deployments

**Comment by istankovic** [comment]
This epic is already too big, even for an epic. Once #564 is closed, we should also make sure this is closed and not add further things here. For new things we should make separate issues to keep things simpler.

**Comment by fredo** [comment]
closing because of the above mentioned reason
