### ISSUE TITLE
TST tokens do not reach Boba Rinkeby network

### ISSUE THREAD

**Issue by ugurbayrak01** [beamer-bridge/beamer#538]
#### System information

OS & Version: Windows 10 x64
Browser & Version: Chrome 100.0.4896.75
Commit hash: 0xff8b29912b1a0aa62783dc35858ca0d6a9e2223039ed6b3ba58497472e083cde

#### Expected behavior

Transfer of TST tokens from Metis Stardust network to Boba Rinkeby network.

#### Actual behavior

TST tokens do not reach Boba Rinkeby network.

#### Steps to reproduce the behavior

I enter the TST token amount, select the sender network as Metis Stardust and the receiver network as Babo Rinkeby. After that, I enter my wallet address and click the Transfer Funds button and confirm from my wallet.

**Comment by palango** [comment]
@ugurbayrak01 Thanks for the report!

We found some problems with the agents running in the background. They are fixed now. Could you please try again and let us know if it works for you now?

**Comment by ugurbayrak01** [comment]
I tried again and it works perfectly for me.

**Comment by palango** [comment]
Perfect. Thanks for the feedback.
