### ISSUE TITLE
frontend: add TypeChain to generate contract types

### ISSUE THREAD

**Issue by weilbith** [beamer-bridge/beamer#549]
Using [TypeChain](https://github.com/dethcrypto/TypeChain) brings a huge typing advantage. We just need to add a hook script that generates the `*.d.ts` files from the already existing `.json` files with the compiled ABI. Afterwards we have proper typing of the contracts with all functions, events and their parameters.

**Comment by czepluch** [comment]
They have some other great tools worth checking out too https://github.com/dethcrypto
