### ISSUE TITLE
Non-Fill: Check invalidFillHashes upon withdraw

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#567]
Upon withdraw we always check if there is a filler set in `ResolutionRegistry.fillers`. If so, the claim and/or challenge will be resolved and withdrawn immediately.

If there is no filler set (meaning that no L1 resolution happened so far), the request manager has to do another check in the resolution registry. It will have to check whether the corresponding fill hash to the claim is invalid by checking the mapping `ResolutionRegistry.invalidFillHashes`.
If it is invalid, then the challenger wins and the claim will be resolved accordingly.

Note that there is an unlikely if not impossible event semantically, but technically allowed. If the fill hash is in the fillers mapping, we ignore the invalid fill hashes (as described already above).

### Note

Should have test coverage

**Comment by istankovic** [comment]
> Note that there is an unlikely if not impossible event semantically, but technically allowed. If the fill hash is in the fillers mapping, we ignore the invalid fill hashes (as described already above).

Sounds like there should be an additional require in `ResolutionRegistry.invalidateFillHash`:

```
require(fillers[fillHash] == address(0), "Cannot invalidate existing resolutions");
```

**Comment by fredo** [comment]
Unfortunately, that's not enough because those events can be called in any order. But I just got another idea to extend on this, making it explicit if the hash is valid or not. 
This will simplify the code base in the Request Manager, nice!
