### ISSUE TITLE
frontend - add unit tests for non-component modules

### ISSUE THREAD

**Issue by weilbith** [beamer-bridge/beamer#586]
Follow up of #384 and #584

Simply add all the missing unit tests for all modules that are not a Vue component. This includes the state management, the Ethereum providers, all composables, possible route guards, etc. pp. While doing so it should be made sure that the tested code gets adapted to make it become better testable. Usually, when there are no unit tests from the very beginning, the written code becomes hard to get into a test-harness. This needs to be resolved in this phase now. A typical case is the dependency inversion by removing direct dependencies of a modules and replacing it with a dependency injection (e.g. via constructor argument).

The unit tests should be very focused and stripped down to the unit. Everything that is not part of this unit should be strictly mocked. Unit tests of a component should not fail by changes to another component. This becomes very simple with good testable code due to included refactoring. Everything else goes into the direction of integration tests, which will follow, but focus on different parts of code properties.

**Comment by weilbith** [comment]
A very interesting question here becomes the decision Mohammed and I took in terms of the dependencies between composables. We need to investigate how easy it is to mock them properly and if we want to keep rather the composables clean and independent than the Vue components.

**Comment by manuelwedler** [comment]
For testing the composables, please consider this section of the vue documentation: https://vuejs.org/guide/scaling-up/testing.html#testing-composables
