### ISSUE TITLE
Frontend: Add unit tests for simple Vue components

### ISSUE THREAD

**Issue by weilbith** [beamer-bridge/beamer#587]
Follow up of #384 and #584

Sibling issue to #586 and #589, focusing on simple Vue components. The point is that testing Vue components works slightly different. The components to focus on here are the simple and re-usable components. Those who don't include any logic about the core business logic. The goal is to identify these components and if they do not yet fulfill these requirements, refactor them. In the end it should be possible to test them all with a shallow mount (feature of the Vue test utils). The latter explicitly ensures that this are unit tests and are not affected by other components. In worst case the "unit" tests of one component need to satisfy the requirements of a child-component. This should **not** be the case for these kind of tests.

The team should argue and exchange experience if snapshot tests are a good addition here or not. The upside is that it saves the developers a lot of manual test code to ensure the component renders as expected. The downside is that the handling of failing snapshot tests needs care and should **not** be simply accepted without further investigation (simply too easy to do in comparison to adapt the tests if necessary).

We should agree to use a special selectors to all DOM elements that are in interest of a test case.

**Comment by weilbith** [comment]
Our library for the state management `pinia` has some utilities and [documentation](https://pinia.vuejs.org/cookbook/testing.html#unit-testing-components) for unit testing of components. From my perspective it is not optimal, but very good.

**Comment by manuelwedler** [comment]
Reopening because tests for `RequestDialog` and `RequestFormInputs` are still missing. I am taking them over now.

**Comment by GabrielBuragev** [comment]
Most of the simple & reusable components hold tests respectively. The overall test coverage for all of them is ~97%.
I would suggest we try to push the coverage in the 99-100% range so we can close this issue finally.

**Comment by manuelwedler** [comment]
I don't think we need to strive for such a high coverage. Imo tests that are implemented to achieve a high coverage are sometimes too tightly coupled, and not adding much value. The goal should just be to have tests that ensure the basic functionality of the components, because there are no tests at all for some components.

**Comment by GabrielBuragev** [comment]
Thanks for the input Manu!
Okay, lets focus on writing basic tests for those simple components that are missing them and if possible increase the coverage on the current reusable components but not that far that we cover the complex intertwined cases.

**Comment by istankovic** [comment]
> Imo tests that are implemented to achieve a high coverage are sometimes too tightly coupled, and not adding much value.

I think this is a valid point and agree to a larget extent with it, but also feel like if the tests are making everything tightly couple, you're doing it wrong. IOW, I do believe coverage can be improved, while not sacrificing abstractions.

I highly recommend this talk on testing and "where it all went wrong":
https://www.youtube.com/watch?v=EZ05e7EMOLM

Food for thought: what do you think "unit" refers to in "unit testing"?

**Comment by manuelwedler** [comment]
The components which don't have tests at all are:

- `Disconnect`
- `ConnectionError`
- `WalletMenu`
- `RequestFeeTooltip`
- `Feedback`

**Comment by manuelwedler** [comment]
Ah yes. Somehow overlooked them :sweat_smile:
