### ISSUE TITLE
Wrong value in token balance label

### ISSUE THREAD

**Issue by nekhaly** [beamer-bridge/beamer#598]
#### System information

OS & Version: All  
Browser & Version: All

#### Actual behavior

After a successful transaction, target chain token balance label shows double the amount of transferred token sum instead of the actual amount. For example (first screenshot), `1 TST` from METIS to BOBA, balance is `22 TST` on Metamask, while token balance label shows `23 TST = 21 + (1 x 2)`. 2nd screenshot, `3 TST` from METIS to BOBA, balance on Metamask is `25 TST`, while token balance label shows `28 TST = 22 + (3 x 2)`. This behavior occurs for a few minutes and then the balance returns to the right one matching Metamask! 

![](https://user-images.githubusercontent.com/8708085/165046071-17388170-86d7-4e81-9a9f-de5537e16abb.png)

![](https://user-images.githubusercontent.com/8708085/165047380-78130af3-b976-4e12-b625-f8b756b9b021.png)

#### Expected behavior

Token balance label value should match Metamask one at all times!

#### Steps to reproduce the behavior

Create a request and check the target chain balance just after making it!

**Comment by taleldayekh** [comment]
@weilbith How do you want to move forward with this? Do you need to discuss this with @manuelwedler or will you be able to give an estimate on the refinement?

**Comment by fredo** [comment]
@andfletcher @compojoom had the same issue. Can you explain how to reproduce the bug?

**Comment by taleldayekh** [comment]
@weilbith  can you give a new look into this? Sync with @andfletcher and Daniel.

**Comment by nekhaly** [comment]
A small help to reproduce the issue as the repo is public and I still receive notifications from it :laughing::

1- Check the token balances on both networks before making a transfer request (check the value below the amount box and compare it to Metamask as well).  
2- make a transfer.  
3- check the new balance for the "target" token (from the label below the amount). It doesn't equal the balance on Metamask (which is the right one)!

Have a nice day :)
