### ISSUE TITLE
frontend - proper multi step actions with data persistence

### ISSUE THREAD

**Issue by weilbith** [beamer-bridge/beamer#605]
While working on tasks of the state management with stores, testing, refactoring and also having #367 in mind, I realized that our current data representation of requests and their state is not optimal. Especially having extensibility, testability and code quality in mind.

Currently we have two different interfaces (`Request` and `RequestMetadata`) to represent a request. Additionally there is the `RequestState` which is (now, after refactoring) decoupled form both.
When the user initiates a request, multiple functions are involved into this process. These functions are defined within composables. The Vue component that includes the trigger has an internal state reference of the requests its state that and provides it to all these functions. Each function then sets this reference to new values depending on what they did.
The type of the state is an enumeration which a strict sorting. In fact this means strings mapped to numbers in a sorted array. Each update means to set the number reference to a new number. It is assumed that the number gets always increased, usually by one for each step. Visual components make use of this assumption and render each number with some text and colors. Comparing the current number to the list of numbers, the component knows which steps have been completed and what's next.
Somehow it has now been tried to add another state to represent a failing state. The state it's under-the-hood number is bigger than all other states. In turn all states are "completed" once an error occurs. If it would now be desirable to fail an any intermediate state/step it would be necessary to add new enumeration entries in the correct order.

If the above summarized concept should be unclear, please ask or look at the code from commit 79d971d08935b679aeef6997dcdf69f7693afbb8 (current HEAD, where this is the de-facto state).

This approach comes with a bunch of flaws. First of all, the concept of the sorted enumeration that maps to numbers is very implicit and fragile. The code is not very expressive and it is incredibly easy to make mistakes and mess it up. This also goes for the integration of failure states which are horrible to add into this structure. Finally the actual data representation is not stable for updates. That means when we develop #367 and safe past requests to local storage, this data must be read and parsed on each new load of the frontend. Due do the approach with a numeric enumeration, the stored data will be just pure numbers. In result the meaning of this number depends on the mapping in the enumeration. Should the enumeration ever change in a non-appending manner (means injecting or removing), the parsed data meaning changes from what it originally was. So for example this could lead to the case that a user made a request that failed at step number 3. Later, with a new version of the frontend, he loads his history again and now the step has completed or failed in a different step because number 3 maps to a different enumeration entry now.
A second part that does not work out too well is the fact that multiple functions manipulate the same state reference variable. Again very implicit and volatile code. Also it is not possible to have multiple requests at the same time. This can definitely happen if a request is not attractive to be fulfilled and will expire after a few days.

What we need to solve is the following:
  - find a data structure to represent a requests state and progress that is resistant to code changes and extensions
  - find an execution flow that guarantees a correct order of steps and the respective state updates
  - make it generic enough so that all included parts can be tested independently
  - make it generic enough so parts of it can be exchanged and/or re-used not only for requests

---

The solution approach we come up with is the following.
 
First of all, what has been called a `request` till now will in the following be named a `transfer`. A transfer names the whole concept that starts from getting user inputs, making a request transaction, waiting for fulfillment and possibly have to retract the request funds. This process can be separated into multiple steps and a resulting state.

A new class `Step` (in lack to find a more expressive name...) that looks like that will be added:

```ts
class Step {
  readonly identifier: string
  readonly label: string

  public active = false
  public completed = false
  public error: string | undefined
  
  constructor(identifier: string, label: string) {
    this.identifier = name
    this.label = label
  }
}
```

It is in first place a class for convenience so it is very easy and short to define a step like `new Step('id', 'label')` without having to define all the other properties. Each step is will be mapped to an executable function. For reasons I'll explain later this gets decoupled from the data. So there is no `step.method` property or similar (using the term `method` here, because `function` is a reserved syntax word). Furthermore, not present in the above code, all modifiable properties should be also become protected and special set functions ensure the correct usage (e.g. only once setting an error, can't be set active if completed, etc).

A multi-step action can now be represent by sorted `Array<Step>`. Additionally there will be a mapping of `Step.identifier`s to callable methods `Record<string, Callable>`. The usage of an identifier is used to map between steps and methods. The advantage over two plain arrays of the same length is explicity and stability. So for example is it possible to support legacy steps by injecting also methods for these steps (having possibly more methods than steps in result). Or if the length/order of new step sequences have changed, the methods still work for old instances too. A practical example would be a transfer that got not yet fulfilled when the user quit the browser. The next time he opens the application, the code has been updated. The old step sequence of the still pending transfer gets loaded from the users local storage. Due to the identifier matching, it is possible to easily continue this transfer by identifying that it is still waiting for a fulfillment and execute the according method. It doesn't matter if anything else has changed in how the steps for new transfers look like.

The generic processing function for this whole action will then look like that:

```ts
async function executeSteps(steps: Ref<Array<Step>>, methods: Record<string, Callable>): Promise<void> {
  if (anyStepHasFailed(steps)) {
    throw new Error('Attempt to run already failed step sequence.')
  }

  if (anyStepIsActive(steps)) {
    throw new Error('Attempt to run already in progress step sequence.')
  }

  const notCompletedSteps = getNotCompletedSteps(steps)
  const stepsWithMissingMethod = findStepsWithMissingMethod(notCompletedSteps, methods)

  if (stepsWithMissingMethod.length > 0) {
    throw new Error(
      `Can not (continue) execution of step sequence. Missing methods for steps: ${stepsWithMissingMethod}`
    )
  }

  for (const step of notCompletedSteps.value) {
    const method = methods[step.identifier]
    step.active = true

    try {
      await method()
      step.completed = true
    } catch(error) {
      step.error = error.message ?? error
      throw error
    } finally {
      step.active = false
    }
  }
}
```

The `Ref<>` is used to make the whole step updates reactive with the usage within Vue. Furthermore this function is capable to continue stopped step sequences, but detects if a references sequence is already in progress or has failed.

Having the methods not within the `Step`s has two reasons. First of all for the general concept to separate data and logic (also slightly improves testability). Second and most important reason is the handling of method arguments and the data persistence.
First of all, it is the general idea to have all these methods somewhat pure alike function. In the end this means only the following. They just receive arguments but never return anything (simply because nobody can handle their output). But it is possible to inject reference argument that can be modified (e.g. to persist the request transaction hash and identifier). Thereby a sequence of methods must be always re-generated for each new set of parameters using anonymous functions like that:

```ts
function foo(f: string) { /* ... */ }
function bar(b: string) { /* ... */ }

const steps = ref([ new Step('foo', 'foo label'), new Step('bar', 'bar label') ])
const methods = { foo: () => foo('f'), bar: () => bar('b') }

executeSteps(steps, methods)
```

Depending on the context and technical requirements method functions (yes I mean that) can also be context bound:

```ts
function foo(this: { f: string }) { ... }
function bar(this: { b: string }) { ... }

const steps = ref([ new Step('foo', 'foo label'), new Step('bar', 'bar label') ])
const methods = { foo: foo.bind({ f: 'f' }), bar: bar.bind({ b: 'b' }) }

executeSteps(steps, methods)
```

The first attempt to use anonymous functions can be also helpful to explicitly give access to the surrounding environment by the nature of arrow functions.

The most important part about the data-logic-separation is the persistence feature. It is intended to store some data to the users local storage. For example the transfer history. For various reasons the step associated methods should not be part of this persistence. So a transfer should be stored with all its metadata and also with the current state of all steps it has defined. When the persisted data gets then reloaded, just pure data gets read and parsed. The whole execution logic with the methods is separated from this. This avoids many issues, technical limitations and potential bugs. And as we have already seen, if there should be the need to continue an already started step sequence, this is simply possible by defining the methods and parameters again and go. The previous shown `executeSteps()` function is already capable of doing this. Though additional checks in the wrapper function should be made. For example if the connected chain is still correct etc. Once a sequence has failed, it is (should be) not re-executable again. Though this could be discussed and adapted in future.

---

After all, we get to the integration with the Vue store. In fact the step sequences will be part of larger data structures like a `Transfer` which will be put into the store. The `executeSteps()` function must be enabled to update the steps their properties in a manner so that components rendering transfers get updated. Therefore we must create (recursive) reactive references into the transfer history store. Thereby any code snippet that triggers a step sequence will first create the store entry (if necessary) and then creates a reactive reference to the steps property of it. This reference will then be passed to `executeSteps()`.
This approach also solves the problem to allow the caller to follow the progress of what happens asynchronously. So for example a Vue component triggered by the user can create a new Transfer by the user inputs, add this transfer to the transfer history store, get a reference to this history entry in the store, create a reference to the steps property of the Transfer and then executes the steps. It must not `await` for its completion but can just use the already existing step reference (or the Transfer itself) to follow what is going on. Having this allows us to have features like waiting for the user to confirm the request transaction on-chain and only then change the UI to show the progress of the transfer. If he declines, the UI does not change or just display that state differently (e.g. error message of failed step).

It must be tested how well it works to define a step sequence within other data structures and give the step methods access to this outer data. For example in a Transfer, the method of the step to make the request transaction will need to set the request identifier in the Transfer object. This is currently expected to be handled by creating steps dynamically with each new Transfer object and injecting `this` as parameter to the methods. This will be verified with a first simple function test soon.

There is also the intention to integrate all necessary information into a preserved data object. So for example will a transfer include information about source and target token. This information should be enriched with all additionally necessary information like token decimals and symbol to show a formatted amount. This data should not be re-fetched over and over again. This is not only inefficient, slow (imagine a very long transfer history), but can also cause issues with preserved legacy data.

Furthermore it is the idea to enrich steps data with getters/computed-values. So can the Transfer class implement a getter to get the error with which it failed, no matter in which step. Or if a transfer is fully completed. This makes working with steps simpler and derived states easier to access.

Such classes must be easy to be instantiated with the raw data. The raw data is an object that can be serialized and persisted to storage. This includes also the steps. The class additionally provides all the functionality to interact with this data like the just mentioned getters. Additionally it provides the step methods to execute the steps. The constructor function should always take a whole object as first parameter. This simplifies the parsing of data from storage. All properties which do not exist from the beginning (e.g. the request identifier to a new Transfer) must be optional. It will be either set when interacting with the transfer or when loading the data from storage. The same goes for all newly added fields after the first version. The whole de-/serialization topic needs some additional work.

**Comment by weilbith** [comment]
@manuelwedler please check if I did not forget anything or made a mistake. Was a quite long session by us. 😬 
@nekhaly please have a look and put in all your experience to make this the best solution we can have.

**Comment by weilbith** [comment]
I'm currently writing some experimental tests. Especially for the serialization. Trying to come up with some restricting types/interfaces to support us.

**Comment by manuelwedler** [comment]
Looks very good! Good Job! I am happy that we are making so many architectural decisions at the moment.

> It must be tested how well it works to define a step sequence within other data structures and give the step methods access to this outer data. For example in a Transfer, the method of the step to make the request transaction will need to set the request identifier in the Transfer object. This is currently expected to be handled by creating steps dynamically with each new Transfer object and injecting `this` as parameter to the methods. This will be verified with a first simple function test soon.

Just one additional idea about that part. Wouldn't it be possible to define the Transfer as a class and the methods as the classes' methods? The steps could be created in the constructor and no injection of `this` would be necessary. 
Could look like this for example:
```js
class Transfer {
   steps;
   methods;   

   constructor(...) {
      this.steps = ref([ new Step('execute', 'exec label')])
      this.methods = { execute: () => this.execute('f')}
   }

   execute() {...}
}
```
