### ISSUE TITLE
Zenhub Board Usage Check List

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#615]
We should create a check list for ANY dev to check if issues on the board are in the correct state. We also have to find an easily accessible place where the list is stored.

- Are the issues in the right column?
- Are all issues in `in progress` or `to review` attached to the current sprint?
- Are all issues which are in the current sprint estimated?
- Do all issues `in progress` have an assignee?
- Are all PRs attached to the respective issue?

@taleldayekh @istankovic @palango @weilbith @manuelwedler @nekhaly Please edit if something is missing

**Comment by istankovic** [comment]
> What happens to issues which are not done, but sprint is over? Moved to the next sprint?

Yes, that part is done automatically by Zenhub.

**Comment by istankovic** [comment]
Thanks for compiling this list, @fredo ! :heart:

**Comment by istankovic** [comment]
What are the next steps with this, @fredo?
I'm not sure how to proceed with this one.
