### ISSUE TITLE
Arbitrum E2E test on CI

### ISSUE THREAD

**Issue by cducrest** [beamer-bridge/beamer#627]
Before we can start with E2E test, we need to
- [x] rebase the existing Arbitrum branch on top of latest `main`
- [x] make sure the contracts still work with our latest `main` and Arbitrum's latest `master`

For the E2E test we need to
~- [ ] fork the latest Arbitrum Nitro repo and apply our patches to facilitate local E2E testing~
~- [ ] fork the latest arbitrum-sdk repo and apply our patch to facilitate local E2E testing (we might avoid this, but this needs to checked)~ (addressed by using our relayer)
~- [ ] clone our Nitro fork, making sure to use the patched branch~
~- [ ] clone our arbitrum-sdk fork, making sure to use the patched branch~  (addressed by using our relayer)
- [x] start all Nitro containers
~- [ ] from the forked arbitrum-sdk repo invoke `yarn gen:network` to generate a custom network config~
- [x] run the `e2e-test.py` script
- [x] run the relayer, configured with the local Nitro RPC and the custom network config
- [x] verify the results

We also need to
- [x] update CircleCI config to also run Arbitrum E2E, in parallel with other E2E tests
~- [ ] submit relevant patches to Arbitrum repos~

### Acceptance criteria
- Arbitrum E2E test is run successfully under CircleCI

**Comment by andfletcher** [comment]
@istankovic can you please Update the issue description if it needs updating

**Comment by istankovic** [comment]
Thanks for the reminder, I've updated the description.

**Comment by andfletcher** [comment]
@fredo, you mentioned to me that we don't need to do everything that is listed here. That's why I asked @istankovic to update the issue description. However, there are now more todos. Did I misunderstand that we don't need everything, or should you align with @ivan (vice versa)?

**Comment by fredo** [comment]
more points does not necessarily mean more work. maybe more detailed description.

It remains that the inclusion into the CI does not necessarily need to be done in order to verify that the contracts work. 
this was the point of our discussion.

for everything else please align with @istankovic

**Comment by andfletcher** [comment]
@istankovic do we need to do #1242 before we can close this issue or will this issue result in #1242 not needing to be done?

**Comment by istankovic** [comment]
Done in #1433.
