### ISSUE TITLE
RequestId isn't checked on invalidateFillHash()

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#644]
#628 introduced passing the request id down the line. The request id initially is passed as an argument into the network upon calling `invalidateFillHash()`. 
The value is used for agents to coordinate an invalid fill hash to a request in its internal storage.

The request id isn't checked at all if it corresponds to the request hash. This could lead to agent failures assigning fill hashs to other requests and eventually not acting properly.

The agent should at least check if the request id fits to the request hash / fill hash. But should avoid passing wrong request ids in the first place.

**Comment by palango** [comment]
To do that we would need additional information which isn't currently available in the call.

So, we need all the below, but they are only available in `fillRequest`.
```sol
BeamerUtils.createRequestHash(
    requestId, sourceChainId, block.chainid, targetTokenAddress, targetReceiverAddress, amount
);
```

But we only have
```sol
    function invalidateFillHash(
        uint256 requestId,
        bytes32 requestHash,
        bytes32 fillId,
        uint256 sourceChainId
    )
```

**Comment by fredo** [comment]
I see your point but I'm still not very satisfied with this potential leak.

Especially, we added this the L1 pipeline because of the way we implemented the agent. So it is not strictly necessary to have it but adapted it due to our agent implementation. I think that's not the right way to go. The events have all information necessary and we should rather adapt the agents logic instead of the other way around. 

The problem is that we have the fill hash as an identifier but do not have our claims indexed by it. Maybe we can come up with the solution how the agent can easily assign the event to the right claim.

**Comment by istankovic** [comment]
I'm not sure that I fully understand the issue here.
If we would like to not have to pass the request ID around, then that should be feasible, because a claim has both the request ID and the fill ID. If we modified the claim tracker to keep a separate mapping of fill IDs to request IDs, it should be a relatively straightforward thing to look up the relevant request. But I'm not sure if this is what is being talked about here.

**Comment by fredo** [comment]
That's exactly what I am suggesting

**Comment by istankovic** [comment]
I agree, and I think your concern is valid. The only remaining question for me here is: what do we do in case a fill hash is invalidated, but no claim has been made?

**Comment by fredo** [comment]
Decision

We adapt the agent to find corresponding requests (or corresponding claims) to the event and apply.  (i.e. look up table or iterating through the list)


When invalidFillhash event arrives but there is no corresponding claim to it, we leave the event in the loop until
- request expires
- no claims for that fill hash are there
- drop event
