### ISSUE TITLE
Support multiple chain pairs

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#654]
In order to support multiple chain pairs in a single agent instance, we need to do the following:
- [ ] for each L2 chain specified by the configuration file, set up an event monitor that feeds the event processor
- [ ] ensure that all events have a chain ID that indicates which chain they're related to (this also pertains to synthetic events)
- [ ] adapt the event processor to be able to handle events from multiple chains
- [ ] make sure that chain ID is included in log entries as appropriate to make it easier to interpret logs
- [ ] add a test that
       - starts a single beamer agent with a specific config with two chains
       - submits a request on both chains, to transfer tokens to the other chain
       - checks that both requests are filled
- [ ] emit a deprecation warning for `source-chain` and `target-chain` configuration keys
- [ ] update documentation
- [ ] update instructions in https://github.com/beamer-bridge/run-your-own-agent

Note: this is an unoptimized variant where we don't have a per-chain transaction queue, so slower chains might cause trouble.
Per-chain transaction queue can be added as part of another issue.

**Comment by weilbith** [comment]
Just for the protocol: the frontend should be pretty well prepared for such a change.

**Comment by fredo** [comment]
close in favor of #652
