### ISSUE TITLE
Adapt message relayer for Arbitrum

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#687]
We need to add support for Arbitrum to our relayer.
This means we need to:

- [x] refactor the existing relayer so that it hands over control to the chain-specific relayer code based on the L2 chain ID
- [x] implement a relayer using the Arbitrum SDK

The Arbitrum relayer needs to run roughly like this:
```
- check if the outbox entry exists; if it does not exist, exit
- while 1:
  - fee = arbitrum_l1_messenger.calculateRetryableSubmissionFee()
  - dfee = 1.1 * fee - arbitrum_l1_messenger.deposits[sender_address] 
  - call arbitrum_l1_messenger.deposit() with value dfee
  - l1_txhash = execute the outbox entry
  - if successful, break the loop

- wait for the ticket on L2
- redeem the ticket
```

**Comment by palango** [comment]
See also:
- https://github.com/OffchainLabs/arbitrum-tutorials/tree/master/packages/outbox-execute
- https://github.com/OffchainLabs/arbitrum-tutorials/tree/master/packages/greeter

**Comment by fredo** [comment]
Add execution on Arbitrum for retryable tickets.
