### ISSUE TITLE
Frontend: Detect wallet disconnection from inside the wallet provider

### ISSUE THREAD

**Issue by weilbith** [beamer-bridge/beamer#692]
Currently, the user can disconnect the wallet from the wallet itself but such disconnects are not being recognized by our app (state is not being updated)
We should recognize that properly.

There is a simple event we can listen to. So if the user disconnects, we recognize this via an event handler in the EthereumProvider, we can unset the signer and most of the app is fine and allows to reconnect.

**Extra:**
We also might want to update the state that keeps the last connected wallet (used for auto-reconnect on page load). A reset to this state will make sure we dont spam the user, on every page load, when he chooses to disconnect from one wallet provider.
This requires a new relation. This means we either need to observe a reference of the provider instance or the provider must become an event emitter.

**Comment by manuelwedler** [comment]
One note: When a user disconnects WalletConnect, the dapp does not recognize at all and still shows that it is connected.

**Comment by weilbith** [comment]
Yes, there is a simple event we can listen too. But it is more complicated for the case the user did this while the app is offline.
One problem is to handle this with the user configuration of the wallet too. So if the user disconnects, we recognize this via an event handler in the `EthereumProvider`, we can unset the signer and most of the app is fine and allows to reconnect. But the next time the app gets loaded, we will still try to automatically connect to the last wallet. So on disconnection we also need to adapt this information. But this requires a new relation. This means we either need to observe a reference in the provider instance or the provider must become an event emitter.
