### ISSUE TITLE
frontend - correctly abbreviate long token amounts

### ISSUE THREAD

**Issue by weilbith** [beamer-bridge/beamer#698]
Currently, in the header of the transfer history, we display a shorten version of the token amount that was sent. The value get shorten to two decimals after the dot. While this seems fine for DAI, this falls of for WETH. So we need a smarter solution here.
Please note that within the expanded body of the transfer, the exact amount is always visible.

**Comment by GabrielBuragev** [comment]
The same issue can also be found inside the user's token balance message.

<img width="467" alt="abbr_issue" src="https://user-images.githubusercontent.com/18466333/183948943-216e31a7-ad63-4e10-8a3f-52cda0801d99.png">
