### ISSUE TITLE
Add limits to the initial version of mainnet contracts

### ISSUE THREAD

**Issue by czepluch** [beamer-bridge/beamer#709]
### Motivation
Since this is the first mainnet release it makes sense to have limits to the transfer amount initially in case something unforeseen goes wrong. It is not necessary to have functionality to remove the limits, since it makes more sense to do this with a new release of the contracts once we are confident that everything works as expected.

### Acceptance criteria
There is a limit to the maximum amount that one transfer can have. My initial suggestion is $10,000. @LoringHarkness @fredo please chime in with any opinions or concerns.

**Comment by fredo** [comment]
We should spin off a frontend issue which takes the limit into account when doing input validation

**Comment by taleldayekh** [comment]
Related to #259

**Comment by LoringHarkness** [comment]
I'm fine with whatever limit you decide. 

Orbiter did a nice trick: They started with a very low level ($1,000), and then raised it bit by bit ($5,000, then $10,000). This allowed them to debug at lower risk points. And they used each increase as a social media opportunity.

**Comment by istankovic** [comment]
> And they used each increase as a social media opportunity.

Now, that's creative. :smiley:

**Comment by czepluch** [comment]
> > We could consider doing that. It would increase the complexity of the issue, since we would need to introduce ownership to the contracts.
> 
> I'm not sure whether you mean the same thing here, but our contracts already have a concept of ownership (they derive from OpenZeppelin's `Ownable`) and we make use of this for things like allowing LPs, updating fee data etc.

Ah, true. Yes, then no worries. That's what I meant yes

**Comment by czepluch** [comment]
It does however add a bit of complexity still to add a separate function to update the limit.
