### ISSUE TITLE
Package agent and relayer for external usage

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#739]
For external parties that want to run an agent, we should provide a package that contains both the agent and required dependencies such as the relayer.

We decided that we want to package the agent and publish it on PyPI. This package should include the relayer binary (#609), so that we can ensure compatibility and users only have one package to install.

- [x] Package the relayer, handled in #609
- [x] Include relayer into the agent python package
- [x] Create CI workflow, that builds relayer and agent packages when a tag is pushed to `main`

**Comment by istankovic** [comment]
Done.
