### ISSUE TITLE
frontend - reduce stress on RPC endpoints

### ISSUE THREAD

**Issue by weilbith** [beamer-bridge/beamer#741]
This primarily targets the waiting for fulfillment or expiration.
Currently we listen on every new block since we created the request. This does the job and works fine for test networks. On production roll-ups this looks different. Roll-ups can produce quite a number of blocks per time. Doing multiple requests per each block can lead to becoming blocked by the RPC endpoint.

For the fulfillment we already have adaptive syncing for past events, and a strict filter for future ones. That looks good and there is possibly no further improvement than that.

For the expiration part, we can improve two different parts. First of all, we can skip the whole time window where the request is still valid. So we can "sleep" until the expected expiration date. In-between it is basically not possible to expire. But due to the unsynchronized clocks, the sequencer can be behind our time, so we still need to verify the block timestamp as before.
Once the validity period is over and there are still active claims, we do not need to check the claim number with every block. We can listen to `ClaimStakeWithdrawn` events for our specific request. Only in case of such an event, the number of active claims gets reduced again and might become zero.
Putting those together, we can safe a mass of RPC requests and should be really good prepared for production environments.

**Comment by taleldayekh** [comment]
@GabrielBuragev Check if we need to do anymore improvements.
