### ISSUE TITLE
Robustness of the relayer 

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#747]
- [ ] wait until message is finalized before calling the relayer
- [ ] kill subprocess when parent dies

# optimizations
- return tx hash from the relayer to reduce relayer running time
    - transaction management (gas price adaptions)
    - agent handles the L1 tx

**Comment by taleldayekh** [comment]
@istankovic @palango Is this epic done?

**Comment by istankovic** [comment]
I think this is now done. @palango ?

**Comment by palango** [comment]
Yes
