### ISSUE TITLE
infrastructure: improve scripts for running testnet agents

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#765]
The scripts to run an agent on our servers are not designed to run multiple instances of an agent with different configurations at the same time. 

While we can pull the latest docker image, the agent binds configuration from a local repository. If the agent restarts it will bind it again regardless whether we updated the repository. 

Especially if we create a new testnet deployment, which we aim to do frequently, we would like to run agents on two different deployments at the same time for a short period of time. Once the testnet frontend has been updated we can turn off the old agents.

This functionality should be reflected in the scripts.

**Comment by taleldayekh** [comment]
@istankovic fix agent naming then close issue.

**Comment by istankovic** [comment]
This has been resolved with the new droplet setup.
