### ISSUE TITLE
scripts: Deployment script to pick up where it crashed

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#767]
We discovered the deployment scripts to crash for a specific reason. 

Deploying a contract and waiting for the transaction timed out due to gas price fluctuation. Increasing the timeout did not help.
Once the script crashes it is not possible to pick up where it left. Also no deployment information are written to the deployment file.

This means we are currently deemed to a successful outcome of the script. If not all the funds are wasted.

We can adapt the script so that it writes information after each deployment of a contract and make it pick up (optionally) partial deployments to continue.

This could be also used for integrating new roll ups.

**Comment by istankovic** [comment]
Moved this out of the sprint as it is not critical for mainnet deployment. We should also reconsider and discuss a new approach for the deployment script.

**Comment by taleldayekh** [comment]
Covered in #769.
