### ISSUE TITLE
deployment script: Better gas price strategy for mainnet

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#768]
We need to come up with a better gas price strategy for the mainnet deployment. Focus should lie on fast inclusion and not so much on getting best prices.

**Comment by palango** [comment]
I'd propose to use the `faster` strategy from raiden: https://github.com/raiden-network/raiden/blob/develop/raiden/network/rpc/middleware.py#L17=

**Comment by taleldayekh** [comment]
Multiply the better gas strategy with 1.x.
