### ISSUE TITLE
Optimize number of requests needed for L1 resolution checks

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#784]
See 
- https://github.com/beamer-bridge/beamer/pull/754#discussion_r902404372
- https://github.com/beamer-bridge/beamer/pull/754#discussion_r902622035=
- https://github.com/beamer-bridge/beamer/pull/754/files/e94c0cb4e0c5225ccd66d062753116efc3ffcf89..eff09627d2eb3b7233dc0ec7a1c245ea3bec01ff#r902584553=

**Comment by fredo** [comment]
related to #783
