### ISSUE TITLE
frontend: Warn the user if there is not enough liquidity in the system

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#786]
All the agents are currently whitelisted. Thus we can see that there is not enough (or low) liquidity in the system if a user wants to start a request.
Although the agents are using hot wallets and they can add liquidity on the spot, a warning for the user would be nice that the request might not be fulfilled due to low liquidity.

This was experienced on testnet. Request expired and no feedback to the user.

**Comment by andfletcher** [comment]
This feature will be redundant once we implement #1663. Even with the whitelisted agents issue #1663 might push for having low liquidity within the agent hot wallet. So this feature here might not be worth it anymore. I am closing it but @fredo please let me know if you still think we should talk about it.
