### ISSUE TITLE
agent: Agent does not correctly add filled requests to the metrics

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#787]
The agent will increment filled requests to the metrics whenever he processes a `RequestFilled` event. If the `RequestFilled` event cannot be processed it will increment it again on the next try. This will tamper the metrics.

We need to properly handle it.

**Comment by istankovic** [comment]
We also have #718.

**Comment by fredo** [comment]
which is probably unrelated to this issue IMO
