### ISSUE TITLE
Sometimes faucet mints 100000 tokens

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#791]
@andfletcher experienced several times that he received 100k test tokens from the faucet. So he was able to quite easily drain the agent.

**Comment by fredo** [comment]
The reason was found. The faucet was recently increased to 100k. 

As a countermeasurement we can always allocate the amount of tokens to the agent as the user gets from the faucet.

**Comment by palango** [comment]
Reset the minted amount to 100, and made the faucet mint to the agent as well. However this is only on the base chain, so the L2 won't be minted for.
