### ISSUE TITLE
Revisit PyPI package publishing

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#843]
Currently there is now way to publish a package under a different name without renaming the underlying module.

As `beamer` is already taken on PyPI, we have to use a different name. However, we currently do not know how to do this, and as this is not important for the mainnet release we decided to postpone this task to a later point in time.

The CI workflow was removed in b36b75cf5ba446843a8f9898a57cc79eff6fe230

**Comment by istankovic** [comment]
Not relevant anymore.
