### ISSUE TITLE
Boba RPC is broken

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#844]
The Boba RPC at https://mainnet.boba.network/ is broken, see https://github.com/bobanetwork/boba/issues/239.
Due to this, the agents will not see new events and therefore will not fill new requests. 

@LoringHarkness @czepluch

**Comment by czepluch** [comment]
Yeah, as discussed we should strongly consider going back to focusing on Arbitrum instead. How did the testing go on that @istankovic ?

**Comment by istankovic** [comment]
> Yeah, as discussed we should strongly consider going back to focusing on Arbitrum instead. How did the testing go on that @istankovic ?

Today I finally managed to get L2 -> L1 messaging working locally, which took a great deal of time. This is not something Arbitrum is ready for (also their words) so I had to improvise a lot. But at least that part of the puzzle is working.

What is missing is L1 -> L2 messaging, and for that we will need to change the interface and all our messenger contracts (probably also resolver and more).... 

So for Arbitrum I would say the next steps would be:

# do a quick prototype of L1 -> L2 Arbitrum messenger and test in the same local environment to verify that the second half of L1 resolution works
# once it works, update the messenger interface, all messengers and other contracts to propagate information about the originator (agent) of the L1 resolution call
   (this is needed so that the Arbitrum can refund excessive gas and submission cost to the correct address)

**Comment by czepluch** [comment]
@fredo What is your opinion on this?

**Comment by fredo** [comment]
Can be closed, as Boba RPC is supposed to be fixed. Will be reopened if it occurs again.
