### ISSUE TITLE
Add dApp disclaimer

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#847]
There is a disclaimer in place that only allows user to use the dApp once agreed on.

Details [here](https://github.com/beamer-bridge/product/issues/67).

**Comment by taleldayekh** [comment]
@manuelwedler can you add a story point to this?

**Comment by manuelwedler** [comment]
New requirement: checkbox state should be stored

**Comment by manuelwedler** [comment]
Not done, as the requirements changed in the product issue https://github.com/beamer-bridge/product/issues/67
