### ISSUE TITLE
Frontend: Transfer history lazy loaded only when label in view

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#851]
![Screencast from 14 07 2022 13 33 29](https://user-images.githubusercontent.com/34456797/178974088-1ffeeab1-d221-4f1b-bed4-8ea19295919c.gif)

#### Actual behavior
When in the transfer history and you scroll to the bottom, the upper elements won't load until the label of the transfer group is in the view.

#### Expected behavior
The transfers should load immediately when they would be in the view.

#### Steps to reproduce the behavior
Make a couple of transfers. Let the some time pass so they are grouped by older and last week. Scroll to the bottom. Slowly scroll up again.

**Comment by weilbith** [comment]
Sorry, wrong PR got linked due to issue number typo.
