### ISSUE TITLE
Integrate Polygon zkEVM

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#877]
I had a talk with Jordi from zkEVM. They announced testnet of their EVM compatible zk rollup during ETHCC. It will be deployed on Rinkeby.
From our discussion they support all the features we need for integration. Additionally, they committed to support us along the way during the integration process.

We can start as soon as they are live on testnet.

**Comment by GabrielBuragev** [comment]
@fredo I guess we can close this in favor of #1486

**Comment by andfletcher** [comment]
done
