### ISSUE TITLE
frontend: Close Modal by click on backdrop

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#883]
At the moment in the Terms & Conditions and Imprint Modal, you have to scroll down to close the Modal by clicking on "ok". The scrolling is quite cumbersome. It would be nice to be able to close by clicking on the backdrop.

**Comment by GabrielBuragev** [comment]
I started working on a solution for this. 
Just need to write tests for it and i will submit a PR.

**Comment by manuelwedler** [comment]
Thanks for your effort @GabrielBuragev , but I'm very sorry to tell you that we made an internal decision to move the imprint and the terms to the Beamer website. Therefore, we don't need the modal anymore.

**Comment by GabrielBuragev** [comment]
Oh, okay. I anyway wrote a small reusable directive for the required functionality. 
Maybe If we need that in the future we can just pull it out.

**Comment by manuelwedler** [comment]
Such features are always nice to have. I'm sure we can use it some time :)
