### ISSUE TITLE
Frontend: Alphabet character input inside request form breaks app

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#887]
https://user-images.githubusercontent.com/18466333/181225686-fa822ba5-b136-4ac7-ba68-2e5a4d73bd30.mp4

#### Expected behavior
Alphabet character input should be forbidden inside the amount input fields to prevent exposure to unforeseen errors. 
By forbidding alphabet character input we will satisfy both the underlying amount parser implementation, which expects a strictly numeric value provided as `string` and also mobile UX design (numeric keyboard pops out on input focus instead of normal keyboard).

#### Actual behavior
User is allowed to enter alphabet characters inside the token amount inputs. 
Due to the implemented amount parsing which, in fact, expects only numeric values as input the app breaks and becomes unresponsive to user interaction.

#### Steps to reproduce the behavior

- Select a source chain and token. 
- Start entering alphabet characters instead of numeric characters inside the amount input.
- App becomes unresponsive to user interaction

**Comment by manuelwedler** [comment]
Thanks a lot for the bug report!
