### ISSUE TITLE
Build a minimal monitoring system

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#890]
For mainnet we would like to have a script what uses the subgraph and checks the following:

* false claims
* challenged claims

This is separate from our Grafana dashboard which shows us agent related information. In the long term it is not a good design to ask agents for contract state. A subgraph is an easy way to gather those information.

**Comment by czepluch** [comment]
### Beamer Agent Desired Stats 
Below points are a braindump of things we can do to prevent problems when shutting down agents and other general improvements.
* Shutdown mechanism (stop filling request, and then shutdown after timeout period)
* Service to claim on behalf of agents
* Stats to see amount of claims, locked capital, available capital, missed claims, current 24h vol, fees earned, 
* RPC stats to see speeds, 
* General agent software monitoring, telegram bot?, hardware monitoring
* NET ROI on ETH and tokens
* General status overview: Open claims, price of shutting down,

**Comment by andfletcher** [comment]
We want to use the script and have a rocket chat bot update us on a daily base of the outcome of the script in a separate dedicated channel. @compojoom .

@fredo can you link the script here please.

**Comment by andfletcher** [comment]
We could run this multiple times during the day, correct?

**Comment by fredo** [comment]
> We could run this multiple times during the day, correct?

correct

**Comment by compojoom** [comment]
@fredo - I updated the script. It now sends the notifications to rocketchat on a fill without a claim and on challenged claims.

Is this enough to close this issue, or do you need something more?

**Comment by fredo** [comment]
when is fill without a claim posted? at one point all fills are without a claim (right after the fill).
It would be ideal to check whether the request is expired
