### ISSUE TITLE
RequestManager whitelist

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#893]
Currently, only the FillManager respects a whitelist of agents who are eligible to fill requests. If only a set of addresses is allowed to fill then only the same set should be allowed to claim.

In order to not need to maintain multiple lists, we can introduce the whitelisting process on L1 and send the allowances to the respective chains. 

It would also reduce an attack vector where the network could be spammed by false claims.

**Comment by taleldayekh** [comment]
@fredo create new issue and close this one.

**Comment by istankovic** [comment]
> In order to not need to maintain multiple lists, we can introduce the whitelisting process on L1 and send the allowances to the respective chains.

How would "send the allowances" actually look?

**Comment by fredo** [comment]
similar to calling the resolution registry via L1, a L1 whitelist registration would send a message to the respective roll ups and call the "addWhitelist" function on the respective contracts.
same as for "resolve" , we would need to make sure the this function is restricted to be called by a certain L1 contract.

**Comment by istankovic** [comment]
> In order to not need to maintain multiple lists, we can introduce the whitelisting process on L1 and send the allowances to the respective chains.

But we would still end up with "multiple lists", right? Both the fill manager and the request manager would have a list of allowed fillers/claimers, right?

**Comment by istankovic** [comment]
After a discussion with @fredo we decided to

- [ ] add a whitelist to `RequestManager`
- [ ] modify the agent to check whether it is whitelisted in the source `RequestManager`

**Comment by fredo** [comment]
can we also add 

- [ ] adapt `call_contracts.py whitelist` to whitelist directly on all corresponding contracts
