### ISSUE TITLE
Frontend: Chain selection view cannot be closed once opened

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#898]
<img width="349" alt="ss_20220801_164929" src="https://user-images.githubusercontent.com/18466333/182177049-bf65f23e-0792-43f8-9bf4-36b45717ddb6.png">

At this moment, there is no way of closing the chain selection view without selecting a chain from the list of options. 

#### Why should this feature exist?
It would be nice to provide this feature to the users so they don't need to select a chain just because they want to go back to the request form view.
Also, if we don't provide them with a `close` function they will be forced to choose a chain and therefore possibly need to add that chain's RPC config inside their browser wallet. This action is triggered by our app when we detect that the user doesn't have that network yet configured inside his wallet provider.

**IMO**: Users should have the option to close the selection view if they cannot find their chain under the list of available chains on the beamer app, hussle free.

#### Steps to reproduce this behavior
Click on any chain selection input and try to close the view that follows without selecting a chain.

#### Specification
Decision made in accordance with Olympe:
- A button showing a left arrow should be shown on the bottom left of the big box. Clicking it closes the selector
- The "Transfer" button should be hidden while the selection is open to reduce distraction

**Comment by manuelwedler** [comment]
Good catch! I already talked with Thore about this last week. @olympe-silve should be aware of this issue and will add a way to close the selection view to the design.

As part of fixing #892 I implemented at least the possibility to close it by pressing escape.

**Comment by manuelwedler** [comment]
We aligned with @olympe-silve and will add a little button showing a left arrow to the bottom left of the box. The "Transfer" button should be hidden while the selection is open.
