### ISSUE TITLE
Frontend: Error Message cut by borders

### ISSUE THREAD

**Issue by DocSmoove** [beamer-bridge/beamer#904]
#### System information

OS & Version: (WIP)
Browser & Version: (WIP)

#### Expected behavior
Not have the message cut out by the borders

#### Actual behavior
There seems to be an issue with the UI; the error message was cut. Please see the image below

Below is also a comment from the member.
"Like this obvious address format error, it should be prompted in the previous step, not an error during the conversion process, and this is a suggestion hope it helps"

I have also opened a thread in Discord if you guys need to contact the guy.

#### Steps to reproduce the behavior
"When I was operating, I deliberately entered the wrong address format, and it did not remind me the first time. It would be better if the user is told that the address is in the wrong format before processing the transaction."

**Comment by DocSmoove** [comment]
<img width="524" alt="Problem with Beamer" src="https://user-images.githubusercontent.com/107990484/182619905-b8a53609-377a-40ec-8020-cd0302db4801.png">

**Comment by GabrielBuragev** [comment]
Thank you for submitting an issue!
The info you provided was really helpful to track down the problem easier.
The team is already working on a solution for this by implementing input validation on the user input form.

Related issue #259

**Comment by manuelwedler** [comment]
The input validation definitely solves the specific error seen here. But I think it would be beneficial to slightly adjust the CSS, so in case there is such an error (we never know what weird unseen errors might be thrown by MetaMask). Normally with the validation such errors long error messages should not occurr but I would do it just to be safe.
So I would break the text in case of an overflow or use an ellipsis with a tooltip.

Also "normal" error messages can break the layout, this looks a little weird already I think: 
![Screenshot from 2022-08-11 08-58-56](https://user-images.githubusercontent.com/34456797/184080061-c9c4ff23-08e4-4116-a0bc-9c271ea400a0.png)

I think it would be good to have a fixed width for the container of the steps.

**Comment by GabrielBuragev** [comment]
I agree, i will move this issue out of the fix scope of the input validation PR so we can tackle it separately.
