### ISSUE TITLE
Frontend: App crashes when inputted amount decimals exceeds token allowed decimals 

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#911]
[New Recording - 8_5_2022, 9_47_14 AM.webm](https://user-images.githubusercontent.com/18466333/183029613-1bc8dbdd-6fba-413e-8fb2-1e989a5cb5b5.webm)

There is a bug in the request form which makes the app unresponsive.
When the user types an amount which has more decimals then the allowed `token` decimals the app crashes and becomes unresponsive.

#### Steps to reproduce the behavior

- Select a token. TST in the provided video which has 18 decimals 
- Type in a number with more then 18 decimals in the `amount` input
- App crashes and becomes unresponsive to user interaction

**Comment by istankovic** [comment]
It's great to see this kind of testing. For some reason the video does not work for me:
![image](https://user-images.githubusercontent.com/1312091/183032405-b4ffe899-2987-420c-b499-6a5aacbd76dd.png)

**Comment by GabrielBuragev** [comment]
https://user-images.githubusercontent.com/18466333/183630079-177c1340-8143-42f1-91cf-0f7a20242461.mp4

How about this one @istankovic ?

**Comment by GabrielBuragev** [comment]
So, there are a few ways to go with this one:

- Wait for input validation PR #918 to get merged and then reuse the `isMatchingDecimals` validator function inside the `RequestSourceInputs.vue` file as following:
```
const { amount: requestFeeAmount, loading: requestFeeLoading } = useRequestFee(
  computed(() => selectedSourceChain.value?.value.rpcUrl),
  computed(() => selectedSourceChain.value?.value.requestManagerAddress),
  computed(() =>
    selectedAmount.value && 
    selectedToken.value && 
    // Add this line
    isMatchingDecimals(selectedToken.value.value.decimals)(selectedAmout.value)
      ? TokenAmount.parse(selectedAmount.value, selectedToken.value.value)
      : undefined,
  ),
  true,
);
```
This will prevent the `requestFee` from being calculated when decimals are out of boundary, which currently causes the crash. Not sure about other places where this might cause a crash tho... Curently only aware of this.
**Least elegant solution** 

- Create a reusable directive which will enable us to attach it to any basic input. The basic functionality of the directive will be to watch and react when the condition `user_inputted_decimals === allowedDecimals` is met. When this condition is met, the directive attaches `onKeyDown` event handler on the input and prevents (with `event.preventDefault()`) any character input except "Backspace" (keycode: 8). 
**More elegant solution**

- Refactor `useRequestFee` composable to return a function which can be called outside of the composable for fetching the current `requestFee` value for provided token amount `x`. This way we also allow for better composability since we are able to apply any logic & checking conditions wherever this function is used from, instead of inside the composable.
**More elegant solution**

Open for discussions and/or better approaches.

**Comment by istankovic** [comment]
> How about this one @istankovic ?

This one works perfectly. Thanks.

**Comment by GabrielBuragev** [comment]
Due to refactoring of the `RequestSourceInput` component in #918, as a positive side effect, this issue will be solved.
