### ISSUE TITLE
Fix Agent Setup Kit issues found by Jannik

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#919]
We need to:

- [x] improve clarity around the account keyfile (keystore is customary)
- [x] add a Rinkeby testnet config file and instructions
- [x] make the agent exit with a better error message when the chain ID is not found in the deployment data
- [x] say how people can check that everything works fine (just the command to show the latest logs and make them verify it says “Sync done” or something)

**Comment by fredo** [comment]
this can be closed @istankovic , right?
