### ISSUE TITLE
Frontend: Add placeholder for SelectorOptions without imageUrl

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#933]
At this moment, inside the token selection we don't show the token icons.
It would be way more convenient for users to see their token icon, if available.
If no icon is available for their token, we would like to show a placeholder icon with a question mark for example.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/18466333/185062243-d9b0235f-b85d-41ef-9872-03e7565be03a.png">

**Comment by istankovic** [comment]
That would be a very nice addition indeed. :+1:

**Comment by manuelwedler** [comment]
This is already supported! In the config file you just need to add an `imageUrl` to a token, just like for the rollup. The reason why no image was showing up is just that we don't have one for the test token. 
We could still add the placeholder. I would add it in the `Selector` component directly if there is no `imageUrl` on the `SelectorOption`.

There is also the list maintained by MetaMask: https://github.com/MetaMask/contract-metadata
