### ISSUE TITLE
Frontend: Mobile - layout not fitting

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#935]
#### System information

OS & Version: Android
Browser & Version: Chrome Android
6.5" device

#### Expected behavior
The dialog is centered in the view and no scrolling is needed.

#### Actual behavior
[<img src="https://user-images.githubusercontent.com/34456797/185084780-1aa9c3a5-dae0-4ecb-a714-5600981d35bc.jpg" width="300">](https://user-images.githubusercontent.com/34456797/185084780-1aa9c3a5-dae0-4ecb-a714-5600981d35bc.jpg)
[<img src="https://user-images.githubusercontent.com/34456797/185084787-9816002d-58ec-4b1f-a477-a0efceeab38a.jpg" width="300">](https://user-images.githubusercontent.com/34456797/185084787-9816002d-58ec-4b1f-a477-a0efceeab38a.jpg)
I have to scroll down to see the footer line and the Beamer logo is partially hidden.

**Comment by GabrielBuragev** [comment]
@olympe-silve any idea how to solve the issue with the beamer logo on mobile devices?

![photo_2022-09-05_10-20-59](https://user-images.githubusercontent.com/18466333/188402960-2dda6c84-41be-4641-8090-8d2b94339f75.jpg)

**Comment by olympe-silve** [comment]
> @olympe-silve any idea how to solve the issue with the beamer logo on mobile devices?
> 
> ![photo_2022-09-05_10-20-59](https://user-images.githubusercontent.com/18466333/188402960-2dda6c84-41be-4641-8090-8d2b94339f75.jpg)

@GabrielBuragev I will send you an idea today
