### ISSUE TITLE
Frontend: Mobile - Input fields turn white

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#936]
#### System information

OS & Version: Android
Browser & Version: Chrome Android

#### Expected behavior

The fields stay in the same color.

#### Actual behavior

On mobile, when writing a value to the input field, the the color of the field turns white.
![Screenshot_20220817-091828_Chrome](https://user-images.githubusercontent.com/34456797/185097356-a40a257c-07fe-4435-822a-a2204367ef08.jpg)

**Comment by taleldayekh** [comment]
Will this be fixed if #962 gets resolved?

**Comment by GabrielBuragev** [comment]
Yes, i believe this is a duplicate issue.
