### ISSUE TITLE
Frontend: Add tailwindcss plugin to prettier

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#938]
I just found out that there is a prettier plugin for sorting the tailwind classes in our templates. Would be nice to add it. It's much easier to get what the classes do, if they follow a specific order.

See https://github.com/tailwindlabs/prettier-plugin-tailwindcss

# Acceptance criteria
- [ ] Plugin is intergrated
- [ ] Whole frontend codebase is formatted

**Comment by GabrielBuragev** [comment]
Nice one! We will also be able to learn the ordering pattern of the tailwind classes with the help of this plugin.
