### ISSUE TITLE
Decimals of fee value

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#941]
We discovered an issue with the fixed fee value (reimbursement value). We currently have one value for all tokens. The problem is that different tokens might have different size of decimals (i. e. USDC only having 6, DAI having 18). 

Starting with only one token it's not a problem. As soon as we have multiple tokens we might run into a problem. 
Possible solutions require a redeployment which should be done soon but after launch. 
This is also a good test to how redeployments work since it is a critical process in the product liveness.

Solutions: 

Option 1: Have a constant decimal fee value
We could define a constant decimal fee value. Upon request we pad the value with the number of zeros required for this token dynamically. The number of decimals can be fetched from the contract.
- This leads to still allowing all tokens to be transferred
- Only works for tokens with equal USD value. (5 USD != 5 ETH)

Option 2: Have a mapping per token
We can have a fee per token with the correct value. This leads to the following situation. Either we will have a whitelist of tokens or we will have a default fee value (i.e. "0") for tokens which are not in the list.
Here we could adjust for different tokens which are not stables. 

## Outcome
Agreed on the following:

We are gonna have a mapping on a per token basis:

values: protocolFee, lpFee, minLpFee, transferLimit
function: addToken, removeToken (onlyOwner)
events: TokenAdded, TokenRemoved, TokenChanged

Open question/partially open:
I would also like to add a tokenChanged event. This should reflect whenever fees were changed. I had a discussion the other day with an agent how to reflect the earned fees, and we actually never know when fees were changed. By having this event, we always know the current fees when a request was created by processing the tokenChanged event first.
(Could also be done by emitting another TokenAdded event, I don't have strong opinions on that).

**Comment by fredo** [comment]
This should also be implemented before the audit

**Comment by istankovic** [comment]
Before we decide on an option here, I think it would be useful to know about our strategy for supporting tokens.
@czepluch will there be a whitelist of tokens?

**Comment by czepluch** [comment]
It's a good question. Maintaining a whitelist definitely makes it easier for us to make sure that our frontend reflects the supported tokens and we would also have some level of quality assurance. It would however introduce additional centralisation too. And I would say that ultimately we should not choose the tokens, but rather tokens should be added from the agents where they see that there is a demand. 

I know this doesn't really answer your questions yet, but I think it starts a discussion needed to come to the best solution.

**Comment by istankovic** [comment]
> Option 2: Have a mapping per token
> We can have a fee per token with the correct value. This leads to the following situation. Either we will have a whitelist of tokens > or we will have a default fee value (i.e. "0") for tokens which are not in the list.

Another approach here would be to require `minLpFee > 0` for each whitelisted token. IOW, one would not be able to whitelist a token without also specifying a nonzero minimum LP fee at the same time.

**Comment by istankovic** [comment]
@fredo maybe a dumb question, but what is the purpose of `minLpFee`? I understand that it is (at the very least) to ensure that LPs get paid _something_ in case the transfer amount is not big enough. But are there any other considerations here?
IOW, do we have additional constraints/criteria for `minLpFee` that need to be satisfied?

How exactly is important relation to fiat USD?

**Comment by fredo** [comment]
> @fredo maybe a dumb question, but what is the purpose of `minLpFee`? I understand that it is (at the very least) to ensure that LPs get paid _something_ in case the transfer amount is not big enough. But are there any other considerations here? IOW, do we have additional constraints/criteria for `minLpFee` that need to be satisfied?
> 
> How exactly is important relation to fiat USD?

The purpose of the minLpFee is to cover the cost of the transactions the LP did. So basically, a reimbursement for the tx_cost. So it ultimately depends on the gas prices of the rollups and the conversion rate of the rollup's native token to the transfer token (typically ETH/USD).

**Comment by fredo** [comment]
We should also consider setting a transfer limit on a per token basis

**Comment by fredo** [comment]
Lets try to get an overview: 

* minLpFee
Should cover the cost of the LPs transfers plus some profit.
Depends on gas prices and native token to transfer token conversion.

* transfer limit


* Adding more tokens: 
If we plan to add more tokens and especially other than stable coins we have to go with option 2. 


Open question: What do we do with unregistered tokens? If we deny the transfer then we implicitly introduced a whitelist of allowed tokens. Might be of interest also for the protocol owners as they earn in transfer token, but limits the functionality of the bridge.

**Comment by fredo** [comment]
Let me try to give a summary, taking into account that we want this feature for the lifetime of V2.

We have several values in the request manager which are in context of the token transferred.

* fees
  * protocol fee (percentage)
  * lp fee (percentage)
  * min lp fee (absolute value)
* transfer limit

Currently, all the above are determined on a contract basis and not per token. This means we have one value for all possible tokens.
Now, I consider three relevant properties of tokens which influence the above.
* conversion rate to native token (mostly all of the cases ETH)
* (conversion rate to USD) (maybe not so relevant)
* number of decimals defined in the token contract

Why do I consider these three propoerties relevant?
For one, we have to have a look at the purpose of min lp fee. Each LP will perform 3 transactions per transfer (fill, claim, withdraw). One of them happens on the target rollup, the other two on the source rollup. In order to become profitable for the agent, we set this parameter, so that even small transfers cover the cost of the three transactions + the opportunity costs for the locked tokens for 24h.
Since the fee is paid in the transferred token but the transactions are paid in ETH, the conversion rate is somewhat relevant.
Additionally, we always set the fee (as best practice) in the lowest unit of the token (basically fixed point representation including all decimals). With different decimals this value differs typically with the number of padded zeros.
The conversion rate to USD might only be a convienient one when it comes to transfer limits. We typically restrict the transfers or also measure the transfers in USD terms. But it's not really that relevant IMO.

## What are our options
It looks clear that once we want to support multiple tokens which are not stable to each other (i.e. USDC, ETH, Shitcoin), then we need different min LP fees and transfer limits. I think the percentage fees are fine in any case. It would be just an additional feature to set them per token (but could be relevant if one token is of higher volatility as another and agents and the protocol owners want to reflect the risk of holding the token in the fees). 
If we had a mapping like this on a per token basis, naturally the question comes up, what do we do with tokens which are not in the mapping?
1) We do not allow transferring it. This would mean that we effectively have a whitelist of tokens which whoever is allowed to set the value has the control over the tokens which can be transferred. Actually, from the DAOs perspective this might make sense (the dao could decide not wanting to receive funds in a specific token).
 The drawback is that we have another controlling point in the system
1a) We could try to come up with a default value for tokens which are not in the mapping but I doubt that we can come up with some values which are useful to all the tokens.
2) We could solve the decimal problem by calling the token contract for the number of decimals and convert the min LP fee and transfer limit to the correct values. This does not solve the other issues with adding tokens which have a different conversion rate to the native token.

IMO, having a whitelist is a cleaner way of handling the above issues and gives us some sort of control which might even be of interest in the future dao. This results in the restriction that not all tokens can be transferred even if there is an agent which would like to provide liquidity for it.
Additional Note: This could be solved externally by plugging in a dex i.e. uniswap, swapping the tokens into a transferrable token and then doing the request, same on the other side upon fill. This could be done by an external "router contract" similar to what Uniswap is doing to keep the core protocol untouched for this kind of feature.

**Comment by andfletcher** [comment]
@fredo I agree with the cleaner way of having a whitelist. It could be very beneficial to the DAO to decide on these decisions since it will also receive the fee in that token. So ownership of the whitelist could be transferred to the DAO and let them make the decisions.

**Comment by istankovic** [comment]
Another possible option would be to let the user decide on the fee i.e. the protocol and the bridge itself would not care. Such an approach would open up a "market" (ugh...) and agents would decide individually what
- tokens they accept
- fees they accept, per token and request

Could result in interesting things and the bridge would only be concerned with providing a safe facility for transfers (it still would collect protocol fee based on the finally accepted fee, for each request).

In general I don't really like this approach, for various reasons, but felt like mentioning it so that maybe helps someone come up  with an additional idea.

**Comment by fredo** [comment]
Agreed on the following: 

We are gonna have a mapping on a per token basis:
- values: protocolFee, lpFee, minLpFee, transferLimit
- function: addToken, removeToken (onlyOwner)
- events: TokenAdded, TokenRemoved

Open question: 
I would also like to add a tokenChanged event. This should reflect whenever fees were changed. I had a discussion the other day with an agent how to reflect the owned fees, and we actually never know when fees were changed. By having this event, we always no the current fees when a request was created by processing the tokenChanged event.
(Could also be done by emitting another TokenAdded event, I don't have strong opinions on that).
