### ISSUE TITLE
Create a deployment process

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#961]
We need to create a process for deployment.

Reason is that we have a central point where the source of parameters is and a concept of double checking that everything is correct. 

There should be a at least 4  eyes concept of checking parameters before the deployment and checking the correct configuration of deployed contracts. 
Ideally we have a sheet where responsible persons are assigned and report their findings.
This process is to be repeated for every deployment

**Comment by istankovic** [comment]
Ideally, we would come up with a checklist for deployment. Yesterday's checklist was of great help.

**Comment by andfletcher** [comment]
closed since merged into #1075
