### ISSUE TITLE
frontend: Background color changes to white if I take my browsers suggestion 

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#962]
Browser: Chrome

![browser-options](https://user-images.githubusercontent.com/10088275/186603659-3fa6dacd-c7cb-4480-905e-63950f0cae03.png)

![browser-chosen](https://user-images.githubusercontent.com/10088275/186603676-d0db25dd-e37a-4fc2-b117-843cad45d4fb.png)

**Comment by GabrielBuragev** [comment]
Solutions:
- Firefox: https://stackoverflow.com/questions/55228377/remove-new-firefox-autofill-color
- Chrome: https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete
