### ISSUE TITLE
To click somewhere on the screen to be able to cancel certain action

### ISSUE THREAD

**Issue by DocSmoove** [beamer-bridge/beamer#967]
Video Example

https://user-images.githubusercontent.com/107990484/186610271-7fae97de-5957-43aa-bc15-69ead87823bd.mov

# Rationale

Why should this feature exist?
It is a natural human instinct to click in a blank space to go back.

What are the use-cases?
Every time we make a mistake and want to fix it before we go to the next step.

# Implementation

Do you have ideas regarding the implementation of this feature?
Nope, sorry 

Are you willing to implement this feature?
If I can code, yes :D

**Comment by GabrielBuragev** [comment]
Thanks for your testing @DocSmoove !
It is a must to implement an escape hatch for situations like this!
We already discussed this and aligned the designs for it, issue was already created and soon to be implemented.

Closing in favor of #898
