### ISSUE TITLE
Implement beamer deployment and configuration commands

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#972]
Make sure to use `apischema` to model deployment configuration and artifacts. Validation should occur immediately after reading deployment configuration and artifacts.

Tasks:  
- [x] Implement the `beamer deploy-base` command
- [x] Implement the `beamer deploy` command
- [ ] Implement the `beamer configure` command
- [x] Store transaction hashes for each contract deployment in the deployment file
- [ ] Update documentation
- [ ] Update instructions in [beamer-bridge/run-your-own-agent#](https://github.com/beamer-bridge/run-your-own-agent)

**Comment by istankovic** [comment]
Tasks:
- [ ] Implement the `deploy` command
- [ ] Implement the `configure-call-chain` command
- [ ] Implement the `configure-finality-periods` command
- [ ] Update Optimism e2e test script
- [ ] Update Arbitrum e2e test script
- [ ] Update documentation
- [ ] Update instructions in [beamer-bridge/run-your-own-agent#](https://github.com/beamer-bridge/run-your-own-agent)

**Comment by fredo** [comment]
for consistency, I would rename `layer1.json` to `1-ethereum.json`

**Comment by GabrielBuragev** [comment]
It would be nice to have the following functionality of the `configure` script:
`Have a function/command to display the currently set fee values in the contract`
