### ISSUE TITLE
Create RPC file 

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#980]
Tasks:
- [ ] create `rpc.json` files for goerli and mainnet deployment (RPC endpoints should be left blank)

Example file:
```
{
  "CHAINID": "RPC_ENDPOINT",
  ....
}
```

**Comment by andfletcher** [comment]
move to other issues:
- [ ] create an example RPC file at `beamer/agent/data/rpc.json.example`, using public RPC endpoints
- [ ] introduce a new, mandatory agent CLI flag, `--rpc-file`, to configure the source of RPC information 
- [ ] introduce a new, mandatory health CLI flag, `--rpc-file`, to configure the source of RPC information

**Comment by bilbeyt** [comment]
Closing as implemented in #981
