### ISSUE TITLE
Frontend: loading indicators are not shown correctly

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#982]
#### System information

OS & Version: All
Browser & Version: All
Commit hash: when using checkout

#### Expected behavior
Loading indicator should be present on page load & when a transfer is being created inside the "Transfer Funds" button.

#### Actual behavior
Loading indicator is not visible in the aforementioned cases.

I believe this happened as a result of [refactoring the Spinner component](https://github.com/beamer-bridge/beamer/pull/901/files#diff-17c9d2ca53192f5a0cd1e2f020845563b4c3a4b892b3c0b7d3578cef7aa7f94aR18) to use string concatenation for applying tailwind classes to the DOM elements inside the Spinner component

Reading the tailwinds docs, the classes should exist as complete strings inside the codebase so the tailwind engine can recognize and pick them up for the final bundle. More info can be found [here](https://v2.tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support)

**Comment by GabrielBuragev** [comment]
Update: loading indicators are now showing but only because [one of the parent components](https://github.com/beamer-bridge/beamer/pull/1017/commits/2578cabd81a96a37ddabde14ed86505fa896225a#diff-ea7f86544da4da836c8b5881ef9e8de9f02e9f4befe7098cb7cff148331639cbR16-R19) of `<Spinner>` is assigning the `border` & `size` classes inline.

For this reason, i am removing the bug label and adding an optimization label as the code inside `Spinner` component needs to be refactored to avoid this behavior

**Comment by andfletcher** [comment]
#1219 fixed it
