### ISSUE TITLE
Make a new agent release and testnet deployment 

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#985]
We should do a new testnet deployment once #972 is done.
This will also validate the new deployment scripts.

https://docs.beamerbridge.com/releasing.html

- [x] mAke new testnet deployment
- [x] Make a new agent release which is able to consume new deployment files
- [x] update changelog
- [x] make a new bug fix release
- [x] update run your own agent
- [x] notifiy agents

This is the last issue of the epic #769

**Comment by istankovic** [comment]
@fredo if we notified agents, this is now done, right?

**Comment by fredo** [comment]
was wondering the same thign before reading your comment, yes I assume this can be closed. All outstanding issues in the EPIC do not change the agent.
