### ISSUE TITLE
Transaction details disappear once you scroll down and up again

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#988]
#### System information

OS & Version: Windows
Browser & Version: Chrome

#### Expected behavior
If I open a transaction detail view and scroll down and up again the details should still show OR it should not show but without a big gap between 2 transactions

#### Actual behavior
![image](https://user-images.githubusercontent.com/39694712/187711649-26efef48-68ce-461c-88c7-22cac7e0569b.png)

scroll down and up again

![image](https://user-images.githubusercontent.com/39694712/187711733-e9711a42-5324-44dd-a5ae-2536f3a50a5a.png)

#### Steps to reproduce the behavior

1. Have enough transactions that you can scroll
2. open detailed view of the transaction
3. scroll down, so details don't show
4. scroll up again and see bug

**Comment by czepluch** [comment]
@GabrielBuragev can you give an estimate on this? I will prioritize it.

**Comment by GabrielBuragev** [comment]
I would say 3, same as #965, since its closely related to the implementation of the element position tracking (via observers).

**Comment by GabrielBuragev** [comment]
What is the criteria for this issue to be marked as resolved?
Is it enough that we fix the big gap between transactions?

From my understanding of the description that would be enough.
If so, this issue will be fixed with the PR #999.

**Comment by czepluch** [comment]
Yes, I think so. I don't care if they collapse or stay open. I think it's most intuitive if they stay "open" with the detailed data though.
