### ISSUE TITLE
Restructuring Request Manager/Resolution Registry

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#989]
This epic is about restructuring the request manager storage management, and enabled by the the unification of the Request Manager and the Resolution Registry.

The structure of the RequestManager is organized by a mapping from the request id which is a simple counter to a request object containing all information for one request. 

## Restructuring Request Manager Storage
The above structure is unfortunate because L1 resolution always identifies a request by its hash. This means when comparing a request to a resolution registry entry we have to recreate the request hash on the Request Manager side and look for entries.
This inconvinience came already up in the agent code when processing L1 resolution events. Here the agent needs to iterate over all internal request representations until he finds the correct request hash.

Furthermore, the request id does not provide any information other than identifying an object. This is something the request hash could do as well, as long as there can never be two requests with the same request hash.

### Using Request hash as identifier for a request
The proposed change is to use the request hash as the key in the mapping and have it as the unique identifier for any request object. In order to achieve uniqueness we still need the old "requestId" as a nonce to obtain two different request hashes for two requests with the same properties. We should rename it to `requestNonce`.

### Removing unused information
Not all information of a request are used in the RequestManager but for the creation of the request hash. We can remove storing `targetTokenAddress`, `targetReceiverAddress`, `targetChainId` and the new `requestNonce`, by having the RequestHash stored as the key of the mapping.

## Unifying Resolution Registry and Request Manager
We now have a mapping from `request hash => request` in the Request Manager and `request hash => fillIInfo` in the Resolution Registry. We can now unify the mappings and merge the resolution registry into the Request Manager.

### Removing FillInfo
No need for this struct anymore as it is nly used inside the Request Manager

### Storing Filler Info
The L1 resolved data can be stored directly in the request's struct.

### Storing invalid fillhashes
A fill hash is a tuple of request hash and fill id. The invalidation of such can be again stored in the requests struct. The request is already assigned to its key, the request hash. 
Since there can be multiple fill id invalidations associated to the request, we need a mapping

`request.invalidFillIds = mapping (fillId => bool)`

This removes the concept of fill hashes.

### Storing fill id in the fill manager
Since the concept of fill hash is not used anymore the mapping in the FillManager is changed to be

`fills = mapping(requestHash => fillId)`

## Adapting peripheral software
Just that it gets not lost, all software associated to the beamer protocol must be updated to accept the request hash as the identifier.

**Comment by istankovic** [comment]
We can also consider converting the `claimId` to be a hash of `(request hash, fillId, block.timestamp)`:

```
 claimCounter += 1;                                
                                                  
Claim storage claim = claims[claimCounter];       
claim.requestId = requestId;                      
claim.claimer = msg.sender;                       
claim.claimerStake = claimStake;                  
claim.lastChallenger = address(0);                
claim.challengerStakeTotal = 0;                   
claim.withdrawnAmount = 0;                        
claim.termination = block.timestamp + claimPeriod;
claim.fillId = fillId;                            
```
This would allow us to remove `claimCounter`.

**Comment by andfletcher** [comment]
@fredo Is there more to be done to finish this epic? I currently see no further issues connected, so I would assume we finished the epic. Please do let me know if there is more to do so we can make sure to create / link the issues.

**Comment by fredo** [comment]
Only updating the docs, but since it is in this sprint I dont mind that the epic can be closed

**Comment by andfletcher** [comment]
@fredo can you link the issue regarding the docs to this issue. I can not find it.

**Comment by fredo** [comment]
added it to the epic, it's already completed. Closing this epic
