### ISSUE TITLE
Rework ProofSubmitter to only generate fill IDs

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#991]
Currently the proof submitter ocntains code to send the proofs via messengers. We should move that code out of the proof submitter and leave only code that generates fill IDs. We should also rename the proof submitter to something like `FillIdGenerator`.

**Comment by fredo** [comment]
@istankovic I thought a bit more about the discussion of blockhash and also consulted @cducrest. 
I'm leaning more towards moving the fill id generation into the fill manager and get rid of the FillIdGenerator. 

If for whatever reason the fill id needs to be generated roll up specifically, we need to pivot. Do you agree?

**Comment by istankovic** [comment]
> @istankovic I thought a bit more about the discussion of blockhash and also consulted @cducrest. I'm leaning more towards moving the fill id generation into the fill manager and get rid of the FillIdGenerator.
> 
> If for whatever reason the fill id needs to be generated roll up specifically, we need to pivot. Do you agree?

Fully. :+1:
